# Phase 3 — RAG Retrieval Prototype

This notebook builds and evaluates the scientific retrieval layer.

Pipeline:

1. Load the validated scientific corpus
2. Remove empty pages
3. Clean extraction artifacts
4. Chunk scientific text
5. Generate stable chunk IDs
6. Preserve source/page metadata
7. Generate semantic embeddings
8. Store embeddings in ChromaDB
9. Implement top-k retrieval
10. Evaluate retrieval against golden cases

The retrieval system must achieve at least an 80% top-3 retrieval hit rate
before downstream LLM reasoning is added.

Our 5 PDFs
     ↓
Break them into sensible pieces
     ↓
Give every piece an ID
     ↓
Remember its PDF + page number
     ↓
MiniLM understands the meaning
     ↓
Store everything in ChromaDB
     ↓
Ask a question
     ↓
Find the 3 most relevant pieces
     ↓
Test using GC01–GC07
     ↓
At least 6/7 work correctly
     ↓
PHASE 3 COMPLETE ✅

## 1. Load and Prepare Scientific Corpus

The validated page-level scientific corpus created during Phase 2 is loaded
for retrieval preparation. Empty or non-extractable pages are excluded from
the retrieval corpus while the original processed corpus remains unchanged.

In [1]:
import pandas as pd

corpus_path = "../data/processed/scientific_corpus_pages.csv"

corpus_df = pd.read_csv(corpus_path)

print("Corpus loaded successfully.")
print("Shape:", corpus_df.shape)
print("\nColumns:")
print(corpus_df.columns.tolist())

corpus_df.head()

Corpus loaded successfully.
Shape: (1377, 4)

Columns:
['source_id', 'filename', 'page_number', 'text']

,source_id,filename,page_number,text
0,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,1,STATE of KNOWLEDGE\r\nof SOIL BIODIVERSITY\r\n...
1,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,2,NaN
2,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,3,STATE of KNOWLEDGE\r\nof SOIL BIODIVERSITY\r\n...
3,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,4,"Required citation\r\nFAO, ITPS, GSBI, CBD and ..."
4,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,5,III\r\nCONTENTS\r\nContributors\r\nXVI\r\nFor...

In [2]:
print("Total page records:", len(corpus_df))
print("Sources:", sorted(corpus_df["source_id"].unique()))

print("\nMissing values:")
print(corpus_df.isnull().sum())

Total page records: 1377
Sources: ['SRC01', 'SRC02', 'SRC03', 'SRC04', 'SRC05']

Missing values:
source_id       0
filename        0
page_number     0
text           25
dtype: int64

In [3]:
retrieval_df = corpus_df.copy()

# Remove pages with no extracted text
retrieval_df = retrieval_df.dropna(subset=["text"])

# Remove whitespace-only text
retrieval_df["text"] = retrieval_df["text"].astype(str).str.strip()
retrieval_df = retrieval_df[retrieval_df["text"] != ""].copy()

# Reset row numbers
retrieval_df.reset_index(drop=True, inplace=True)

In [4]:
print("Original pages:", len(corpus_df))
print("Retrievable pages:", len(retrieval_df))
print("Removed empty pages:", len(corpus_df) - len(retrieval_df))

print("\nPages remaining per source:")
print(retrieval_df.groupby("source_id").size())

print("\nRemaining null text:", retrieval_df["text"].isnull().sum())
print(
    "Remaining empty text:",
    (retrieval_df["text"].str.strip() == "").sum()
)

Original pages: 1377
Retrievable pages: 1352
Removed empty pages: 25

Pages remaining per source:
source_id
SRC01    613
SRC02    560
SRC03    166
SRC04      5
SRC05      8
dtype: int64

Remaining null text: 0
Remaining empty text: 0

## 2. Text Cleaning and Sentence-Aware Chunking

Extracted PDF text is cleaned conservatively to normalize whitespace while
preserving scientific values, units, citations, and terminology.

The cleaned text is then divided into sentence-aware chunks so that scientific
statements are not unnecessarily split in the middle of a sentence.

In [5]:
import re

def clean_text(text):
    # Replace line breaks/tabs/repeated whitespace with a single space
    text = re.sub(r"\s+", " ", text)

    return text.strip()


retrieval_df["clean_text"] = retrieval_df["text"].apply(clean_text)

In [6]:
print("Empty cleaned text:",
      (retrieval_df["clean_text"] == "").sum())

print("\nExample BEFORE:\n")
print(retrieval_df.iloc[0]["text"][:500])

print("\nExample AFTER:\n")
print(retrieval_df.iloc[0]["clean_text"][:500])

Empty cleaned text: 0

Example BEFORE:

STATE of KNOWLEDGE
of SOIL BIODIVERSITY
Status, challenges and potentialities
Report
2020
﻿

Example AFTER:

STATE of KNOWLEDGE of SOIL BIODIVERSITY Status, challenges and potentialities Report 2020 ﻿

In [7]:
def split_into_sentences(text):
    sentences = re.split(
        r'(?<=[.!?])\s+(?=[A-Z0-9])',
        text
    )

    return [
        sentence.strip()
        for sentence in sentences
        if sentence.strip()
    ]

In [8]:
sample_text = retrieval_df.iloc[10]["clean_text"]

sample_sentences = split_into_sentences(sample_text)

print("Number of sentences:", len(sample_sentences))

for sentence in sample_sentences[:10]:
    print("\n-", sentence)

Number of sentences: 1

- X 7.1 | Assessment of soil biodiversit 430 7.1.1 | Contributions of soil biodiversity to ecosystems services 430 7.1.2 | National assessment 430 7.1.3 | Practical applications of soil biodiversit 431 7.1.4 | Major practices negatively impacting soil biodiversit 431 7.1.5 | Invasive alien species (IAS 431 7.1.6 | Monitoring soil biodiversit 432 7.1.7 | Indicators used to evaluate soil biodiversit 432 7.2 | Research, capacity development and awareness raisin 433 7.3 | Mainstreaming: policies, programmes, regulations and governmental framework 433 7.4 | Analysis of the main gaps, barriers and opportunities in the conservation and sustainable use of soil biodiversit 434 Annex II National Survey on Status of Soil Biodiversity: Knowledge, Challenges and Opportunitie 437 I | Assessmen 439 II | Research, capacity development and awareness raisin 442 III | Mainstreaming: policies, regulations and governmental framework 442 IV | Analysis of gaps and opportunities 443 Annex III List of countries that responded to the surve 445 Reference 447

In [9]:
sample_row = retrieval_df[
    (retrieval_df["source_id"] == "SRC01") &
    (retrieval_df["page_number"] == 100)
].iloc[0]

sample_text = sample_row["clean_text"]

print("Source:", sample_row["source_id"])
print("Page:", sample_row["page_number"])
print("\nTEXT SAMPLE:\n")
print(sample_text[:1500])

Source: SRC01
Page: 100

TEXT SAMPLE:

State of knowledge of soil biodiversity 70 beetle abundance may be more important for ecosystem functioning than species richness (Manning and Cutler, 2018; Alvarado et al., 2019). However, functional group richness, species composition and maintenance of interactions among co-occurring species (such as tunnelling and dwelling dung beetles; Nervo et al., 2017) have been shown to be important for ecosystem function (Larsen et al., 2005; Milotić et al., 2018; Menéndez et al., 2016) and for sustaining multiple ecosystem functions (O’hea et al., 2010; Nervo et al., 2017; Manning et al., 2016; Piccini et al., 2018; Santos-Heredia et al., 2018) in both perturbed (Beynon et al., 2012) and unperturbed systems (Manning et al., 2017; Beynon et al., 2012). In addition to their direct consumptive and shredding activities, macrofauna can indirectly affect soil C dynamics by altering the abundance and activity of their prey and/ or regulating the activity or composition of soil microbial communities. For example, recent studies have shown that grazing isopods modify the composition and activity of fungal communities (Crowther and A’Bear, 2012; Crowther et al., 2013) and thereby alter fungal-mediated wood decomposition rates (Crowther et al., 2015). These impacts vary according to environmental context, whereby isopod control over fungal decomposer activity increases with increasing inorganic soil nitrogen availability (Crowther et al., 2015). Larger invertebrate predators, such as predator

In [10]:
sample_sentences = split_into_sentences(sample_text)

print("Number of sentences:", len(sample_sentences))

for i, sentence in enumerate(sample_sentences[:10], start=1):
    print(f"\nSentence {i}:")
    print(sentence)

Number of sentences: 13

Sentence 1:
State of knowledge of soil biodiversity 70 beetle abundance may be more important for ecosystem functioning than species richness (Manning and Cutler, 2018; Alvarado et al., 2019).

Sentence 2:
However, functional group richness, species composition and maintenance of interactions among co-occurring species (such as tunnelling and dwelling dung beetles; Nervo et al., 2017) have been shown to be important for ecosystem function (Larsen et al., 2005; Milotić et al., 2018; Menéndez et al., 2016) and for sustaining multiple ecosystem functions (O’hea et al., 2010; Nervo et al., 2017; Manning et al., 2016; Piccini et al., 2018; Santos-Heredia et al., 2018) in both perturbed (Beynon et al., 2012) and unperturbed systems (Manning et al., 2017; Beynon et al., 2012).

Sentence 3:
In addition to their direct consumptive and shredding activities, macrofauna can indirectly affect soil C dynamics by altering the abundance and activity of their prey and/ or regulating the activity or composition of soil microbial communities.

Sentence 4:
For example, recent studies have shown that grazing isopods modify the composition and activity of fungal communities (Crowther and A’Bear, 2012; Crowther et al., 2013) and thereby alter fungal-mediated wood decomposition rates (Crowther et al., 2015).

Sentence 5:
These impacts vary according to environmental context, whereby isopod control over fungal decomposer activity increases with increasing inorganic soil nitrogen availability (Crowther et al., 2015).

Sentence 6:
Larger invertebrate predators, such as predatory beetles and spiders, can also have cascading effects through the food web that affect carbon transformations.

Sentence 7:
Notably, as with some of the other examples above, the direction and magnitude of predator effects are variable (positive, negative, or neutral) depending on the species present and environmental context.

Sentence 8:
For example, the presence of some predatory beetles (Wu et al., 2011) and web-building spiders (Liu et al., 2014) sometimes results in slower decomposition rates (but see Miyashita and Niwa, 2006 for an example of web-building spiders having no effect on decomposition), while wolf spiders in tropical, temperate and arctic ecosystems can indirectly enhance decomposition (Lawrence and Wise, 2004; Koltz et al., 2018; Liu et al., 2015).

Sentence 9:
However, changes in environmental conditions such as moisture availability, warming, or fertilization can alter or even reverse predator effects on decomposition and soil respiration (Lensing and Wise, 2006; Wu et al., 2011; Koltz et al., 2018; Maran et al., 2016; Melguizo-Ruiz et al., 2019; Kashmeera and Sudhikumar, 2018; Liu et al., 2018; Liu et al., 2015).

Sentence 10:
Studies of predator effects on carbon transformations have been limited to very few taxonomic groups; this is an area that requires further study.

In [14]:
def create_chunks(text, target_size=1200, overlap_sentences=2):
    sentences = split_into_sentences(text)

    if not sentences:
        return []

    # Fallback:
    # If sentence splitting produces one extremely long block
    # (common for TOCs, lists, or badly structured PDF text),
    # split it safely by character windows.
    if len(sentences) == 1 and len(sentences[0]) > target_size:
        chunks = []
        start = 0
        overlap_chars = 200

        while start < len(text):
            end = start + target_size
            chunk = text[start:end].strip()

            if chunk:
                chunks.append(chunk)

            if end >= len(text):
                break

            start = end - overlap_chars

        return chunks

    # Normal sentence-aware chunking
    chunks = []
    current_sentences = []

    for sentence in sentences:
        candidate = " ".join(current_sentences + [sentence])

        if len(candidate) <= target_size or not current_sentences:
            current_sentences.append(sentence)

        else:
            chunk = " ".join(current_sentences).strip()

            if chunk:
                chunks.append(chunk)

            current_sentences = (
                current_sentences[-overlap_sentences:]
                if overlap_sentences > 0
                else []
            )

            current_sentences.append(sentence)

    if current_sentences:
        chunk = " ".join(current_sentences).strip()

        if chunk:
            chunks.append(chunk)

    return chunks

In [13]:
sample_chunks = create_chunks(sample_text)

print("Number of chunks:", len(sample_chunks))

for i, chunk in enumerate(sample_chunks, start=1):
    print(f"\nCHUNK {i} — {len(chunk)} characters")
    print(chunk[:250])

Number of chunks: 6

CHUNK 1 — 1001 characters
State of knowledge of soil biodiversity 70 beetle abundance may be more important for ecosystem functioning than species richness (Manning and Cutler, 2018; Alvarado et al., 2019). However, functional group richness, species composition and maintenan

CHUNK 2 — 1073 characters
However, functional group richness, species composition and maintenance of interactions among co-occurring species (such as tunnelling and dwelling dung beetles; Nervo et al., 2017) have been shown to be important for ecosystem function (Larsen et al

CHUNK 3 — 1060 characters
In addition to their direct consumptive and shredding activities, macrofauna can indirectly affect soil C dynamics by altering the abundance and activity of their prey and/ or regulating the activity or composition of soil microbial communities. For

CHUNK 4 — 1162 characters
Larger invertebrate predators, such as predatory beetles and spiders, can also have cascading effects through the food web that affect carbon transformations. Notably, as with some of the other examples above, the direction and magnitude of predator

CHUNK 5 — 1196 characters
For example, the presence of some predatory beetles (Wu et al., 2011) and web-building spiders (Liu et al., 2014) sometimes results in slower decomposition rates (but see Miyashita and Niwa, 2006 for an example of web-building spiders having no effec

CHUNK 6 — 974 characters
Studies of predator effects on carbon transformations have been limited to very few taxonomic groups; this is an area that requires further study. Nutrient cycling - Isopods, millipedes, insects and spiders affect nutrient cycling in a variety of way

In [15]:
normal_chunks = create_chunks(sample_text)

print("Normal scientific page")
print("Number of chunks:", len(normal_chunks))

for i, chunk in enumerate(normal_chunks, 1):
    print(f"Chunk {i}: {len(chunk)} characters")

Normal scientific page
Number of chunks: 6
Chunk 1: 1001 characters
Chunk 2: 1073 characters
Chunk 3: 1060 characters
Chunk 4: 1162 characters
Chunk 5: 1196 characters
Chunk 6: 974 characters

In [16]:
toc_text = retrieval_df.iloc[10]["clean_text"]

print("Sentences detected:", len(split_into_sentences(toc_text)))

toc_chunks = create_chunks(toc_text)

print("TOC chunks:", len(toc_chunks))

for i, chunk in enumerate(toc_chunks, start=1):
    print(f"Chunk {i}: {len(chunk)} characters")

Sentences detected: 1
TOC chunks: 1
Chunk 1: 1081 characters

In [ ]:
## 3. Generate Corpus Chunks and Metadata

The validated retrieval corpus is divided into manageable chunks. Each chunk
receives a deterministic identifier and retains its original source, filename,
page number, and within-page chunk index for provenance and citation tracing.

In [17]:
all_chunks = []

for _, row in retrieval_df.iterrows():

    page_chunks = create_chunks(row["clean_text"])

    for chunk_index, chunk in enumerate(page_chunks, start=1):

        chunk_id = (
            f'{row["source_id"]}_'
            f'P{int(row["page_number"]):04d}_'
            f'C{chunk_index:03d}'
        )

        all_chunks.append({
            "chunk_id": chunk_id,
            "source_id": row["source_id"],
            "filename": row["filename"],
            "page_number": int(row["page_number"]),
            "chunk_index": chunk_index,
            "text": chunk
        })

In [18]:
chunks_df = pd.DataFrame(all_chunks)

print("Total chunks:", len(chunks_df))
print("Columns:", chunks_df.columns.tolist())

chunks_df.head()

Total chunks: 5652
Columns: ['chunk_id', 'source_id', 'filename', 'page_number', 'chunk_index', 'text']

,chunk_id,source_id,filename,page_number,chunk_index,text
0,SRC01_P0001_C001,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,1,1,STATE of KNOWLEDGE of SOIL BIODIVERSITY Status...
1,SRC01_P0003_C001,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,3,1,STATE of KNOWLEDGE of SOIL BIODIVERSITY Status...
2,SRC01_P0004_C001,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,4,1,"Required citation FAO, ITPS, GSBI, CBD and EC...."
3,SRC01_P0004_C002,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,4,2,The views expressed in this information produc...
4,SRC01_P0004_C003,SRC01,SRC01_State of Knowledge of Soil Biodiversity.pdf,4,3,"If a translation of this work is created, it m..."

In [19]:
print("Total chunks:", len(chunks_df))

print("Duplicate chunk IDs:",
      chunks_df["chunk_id"].duplicated().sum())

print("Missing chunk IDs:",
      chunks_df["chunk_id"].isnull().sum())

print("Missing text:",
      chunks_df["text"].isnull().sum())

print("Empty chunks:",
      (chunks_df["text"].str.strip() == "").sum())

print("\nChunks per source:")
print(chunks_df.groupby("source_id").size())

print("\nChunk length statistics:")
print(chunks_df["text"].str.len().describe())

Total chunks: 5652
Duplicate chunk IDs: 0
Missing chunk IDs: 0
Missing text: 0
Empty chunks: 0

Chunks per source:
source_id
SRC01    1985
SRC02    3003
SRC03     573
SRC04      18
SRC05      73
dtype: int64

Chunk length statistics:
count    5652.000000
mean     1062.437721
std       314.554712
min         3.000000
25%       970.000000
50%      1100.000000
75%      1168.000000
max      4828.000000
Name: text, dtype: float64

In [20]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

print("Model loaded successfully.")
print("Maximum sequence length:", embedding_model.max_seq_length)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\shubham chavan\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\shubham chavan\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Model loaded successfully.
Maximum sequence length: 256

In [21]:
tokenizer = embedding_model.tokenizer

def get_token_count(text):
    encoded = tokenizer(
        text,
        add_special_tokens=True,
        truncation=False
    )
    return len(encoded["input_ids"])

chunks_df["token_count"] = chunks_df["text"].apply(get_token_count)

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (269 > 256). Running this sequence through the model will result in indexing errors

In [22]:
print("Token count statistics:")
print(chunks_df["token_count"].describe())

too_long = chunks_df[
    chunks_df["token_count"] > embedding_model.max_seq_length
]

print("\nChunks exceeding 256 tokens:", len(too_long))

print(
    "Percentage exceeding limit:",
    round(len(too_long) / len(chunks_df) * 100, 2),
    "%"
)

print("Maximum token count:", chunks_df["token_count"].max())

Token count statistics:
count    5652.000000
mean      234.959837
std        85.767875
min         3.000000
25%       192.000000
50%       223.000000
75%       259.000000
max       901.000000
Name: token_count, dtype: float64

Chunks exceeding 256 tokens: 1462
Percentage exceeding limit: 25.87 %
Maximum token count: 901

In [23]:
tiny_chunks = chunks_df[
    chunks_df["token_count"] < 20
]

print("Chunks under 20 tokens:", len(tiny_chunks))

tiny_chunks[
    ["chunk_id", "source_id", "page_number", "token_count", "text"]
].head(20)

Chunks under 20 tokens: 33

,chunk_id,source_id,page_number,token_count,text
0,SRC01_P0001_C001,SRC01,1,16,STATE of KNOWLEDGE of SOIL BIODIVERSITY Status...
40,SRC01_P0022_C001,SRC01,22,5,© Andy Murray
57,SRC01_P0030_C001,SRC01,30,5,© Andy Murray
69,SRC01_P0035_C001,SRC01,35,5,© Andy Murray
70,SRC01_P0036_C001,SRC01,36,12,©FAO / Matteo Sala © Andy Murray
278,SRC01_P0121_C001,SRC01,121,15,© Pavel Krásenský Global diversity and distrib...
360,SRC01_P0143_C001,SRC01,143,5,© Andy Murray
361,SRC01_P0144_C001,SRC01,144,5,© Andy Murray
393,SRC01_P0156_C001,SRC01,156,9,©FAO / Matteo Sala
611,SRC01_P0206_C001,SRC01,206,12,State of knowledge of soil biodiversity 176 © ...
612,SRC01_P0207_C001,SRC01,207,12,Contributions of soil biodiversity to ecosyste...
613,SRC01_P0208_C001,SRC01,208,12,State of knowledge of soil biodiversity 178 © ...
614,SRC01_P0209_C001,SRC01,209,12,Contributions of soil biodiversity to ecosyste...
650,SRC01_P0220_C001,SRC01,220,8,©FAO/Ronald Vargas
727,SRC01_P0239_C001,SRC01,239,9,©FAO/Matteo Sala
941,SRC01_P0292_C001,SRC01,292,7,© Guillermo Peralta
1108,SRC01_P0339_C001,SRC01,339,7,© Guillermo Peralta
1109,SRC01_P0340_C001,SRC01,340,7,© Guillermo Peralta
1136,SRC01_P0352_C001,SRC01,352,5,© Andy Murray
1182,SRC01_P0368_C001,SRC01,368,5,© Andy Murray

In [24]:
def create_token_aware_chunks(
    text,
    tokenizer,
    target_tokens=220,
    overlap_sentences=2
):
    sentences = split_into_sentences(text)

    if not sentences:
        return []

    def token_count(value):
        return len(
            tokenizer(
                value,
                add_special_tokens=True,
                truncation=False
            )["input_ids"]
        )

    # --------------------------------------------------
    # Handle a single sentence/block that is too long
    # --------------------------------------------------
    expanded_sentences = []

    for sentence in sentences:

        if token_count(sentence) <= target_tokens:
            expanded_sentences.append(sentence)
            continue

        # Token-level fallback for oversized sentences,
        # TOCs, lists or badly extracted PDF blocks
        token_ids = tokenizer(
            sentence,
            add_special_tokens=False,
            truncation=False
        )["input_ids"]

        # Leave room for special tokens
        safe_size = target_tokens - 2

        for start in range(0, len(token_ids), safe_size):

            token_piece = token_ids[start:start + safe_size]

            piece = tokenizer.decode(
                token_piece,
                skip_special_tokens=True
            ).strip()

            if piece:
                expanded_sentences.append(piece)

    # --------------------------------------------------
    # Pack sentences into token-safe chunks
    # --------------------------------------------------
    chunks = []
    current_sentences = []

    for sentence in expanded_sentences:

        candidate = " ".join(
            current_sentences + [sentence]
        ).strip()

        if (
            not current_sentences
            or token_count(candidate) <= target_tokens
        ):
            current_sentences.append(sentence)

        else:
            chunk = " ".join(current_sentences).strip()

            if chunk:
                chunks.append(chunk)

            # Keep previous sentences for context
            overlap = (
                current_sentences[-overlap_sentences:]
                if overlap_sentences > 0
                else []
            )

            # Make sure overlap itself doesn't make
            # the next chunk exceed the token target
            while overlap:
                candidate = " ".join(
                    overlap + [sentence]
                ).strip()

                if token_count(candidate) <= target_tokens:
                    break

                overlap = overlap[1:]

            current_sentences = overlap + [sentence]

    if current_sentences:
        final_chunk = " ".join(current_sentences).strip()

        if final_chunk:
            chunks.append(final_chunk)

    return chunks

In [25]:
test_chunks = create_token_aware_chunks(
    sample_text,
    tokenizer
)

print("Chunks:", len(test_chunks))

for i, chunk in enumerate(test_chunks, 1):

    tokens = len(
        tokenizer(
            chunk,
            add_special_tokens=True,
            truncation=False
        )["input_ids"]
    )

    print(
        f"Chunk {i}: "
        f"{len(chunk)} characters | "
        f"{tokens} tokens"
    )

Chunks: 7
Chunk 1: 755 characters | 197 tokens
Chunk 2: 820 characters | 206 tokens
Chunk 3: 1060 characters | 207 tokens
Chunk 4: 800 characters | 169 tokens
Chunk 5: 798 characters | 201 tokens
Chunk 6: 759 characters | 175 tokens
Chunk 7: 974 characters | 204 tokens

In [30]:
chunks_df["token_count"] = chunks_df["text"].apply(
    lambda text: len(
        tokenizer(
            text,
            add_special_tokens=True,
            truncation=False
        )["input_ids"]
    )
)

print("Token counts calculated successfully.")
print(chunks_df.columns.tolist())

Token counts calculated successfully.
['chunk_id', 'source_id', 'filename', 'page_number', 'chunk_index', 'text', 'token_count']

In [31]:
all_chunks = []

for _, row in retrieval_df.iterrows():

    page_chunks = create_token_aware_chunks(
        row["clean_text"],
        tokenizer,
        target_tokens=220,
        overlap_sentences=2
    )

    for chunk_index, chunk in enumerate(page_chunks, start=1):

        chunk_id = (
            f'{row["source_id"]}_'
            f'P{int(row["page_number"]):04d}_'
            f'C{chunk_index:03d}'
        )

        all_chunks.append({
            "chunk_id": chunk_id,
            "source_id": row["source_id"],
            "filename": row["filename"],
            "page_number": int(row["page_number"]),
            "chunk_index": chunk_index,
            "text": chunk
        })

chunks_df = pd.DataFrame(all_chunks)

print("New total chunks:", len(chunks_df))

New total chunks: 6876

In [34]:
print("Total chunks:", len(chunks_df))

print("\nIntegrity checks:")
print("Duplicate IDs:", chunks_df["chunk_id"].duplicated().sum())
print("Missing IDs:", chunks_df["chunk_id"].isnull().sum())
print("Missing text:", chunks_df["text"].isnull().sum())
print("Empty chunks:", (chunks_df["text"].str.strip() == "").sum())

print("\nToken statistics:")
print(chunks_df["token_count"].describe())

print("\nChunks > 220:",
      (chunks_df["token_count"] > 220).sum())

print("Chunks > 256:",
      (chunks_df["token_count"] > 256).sum())

print("\nChunks per source:")
print(chunks_df.groupby("source_id").size())

Total chunks: 6876

Integrity checks:
Duplicate IDs: 0
Missing IDs: 0
Missing text: 0
Empty chunks: 0

Token statistics:

KeyError: 'token_count'

In [35]:
print(chunks_df.columns.tolist())

['chunk_id', 'source_id', 'filename', 'page_number', 'chunk_index', 'text']

In [36]:
def count_tokens(text):
    return len(
        tokenizer.encode(
            text,
            add_special_tokens=True,
            truncation=False
        )
    )

chunks_df["token_count"] = chunks_df["text"].apply(count_tokens)

print("Done!")
print(chunks_df.columns.tolist())

Done!
['chunk_id', 'source_id', 'filename', 'page_number', 'chunk_index', 'text', 'token_count']

In [37]:
chunks_df[["chunk_id", "token_count"]].head()

           chunk_id  token_count
0  SRC01_P0001_C001           16
1  SRC01_P0003_C001           27
2  SRC01_P0004_C001          208
3  SRC01_P0004_C002          209
4  SRC01_P0004_C003          187

In [38]:
print("Total chunks:", len(chunks_df))
print("Maximum tokens:", chunks_df["token_count"].max())

print(
    "Chunks > 220:",
    (chunks_df["token_count"] > 220).sum()
)

print(
    "Chunks > 256:",
    (chunks_df["token_count"] > 256).sum()
)

print("\nToken statistics:")
print(chunks_df["token_count"].describe())

Total chunks: 6876
Maximum tokens: 223
Chunks > 220: 8
Chunks > 256: 0

Token statistics:
count    6876.000000
mean      185.630745
std        39.050009
min         3.000000
25%       176.000000
50%       199.000000
75%       212.000000
max       223.000000
Name: token_count, dtype: float64

In [39]:
credit_mask = (
    chunks_df["text"].str.contains(
        r"^\s*©",
        regex=True,
        na=False
    )
    &
    (chunks_df["token_count"] < 20)
)

credit_chunks = chunks_df[credit_mask]

print("Obvious credit/noise chunks:", len(credit_chunks))

credit_chunks[
    ["chunk_id", "source_id", "page_number", "token_count", "text"]
]

Obvious credit/noise chunks: 18

,chunk_id,source_id,page_number,token_count,text
49,SRC01_P0022_C001,SRC01,22,5,© Andy Murray
71,SRC01_P0030_C001,SRC01,30,5,© Andy Murray
85,SRC01_P0035_C001,SRC01,35,5,© Andy Murray
86,SRC01_P0036_C001,SRC01,36,12,©FAO / Matteo Sala © Andy Murray
352,SRC01_P0121_C001,SRC01,121,15,© Pavel Krásenský Global diversity and distrib...
453,SRC01_P0143_C001,SRC01,143,5,© Andy Murray
454,SRC01_P0144_C001,SRC01,144,5,© Andy Murray
495,SRC01_P0156_C001,SRC01,156,9,©FAO / Matteo Sala
796,SRC01_P0220_C001,SRC01,220,8,©FAO/Ronald Vargas
878,SRC01_P0239_C001,SRC01,239,9,©FAO/Matteo Sala
1122,SRC01_P0292_C001,SRC01,292,7,© Guillermo Peralta
1332,SRC01_P0339_C001,SRC01,339,7,© Guillermo Peralta
1333,SRC01_P0340_C001,SRC01,340,7,© Guillermo Peralta
1362,SRC01_P0352_C001,SRC01,352,5,© Andy Murray
1411,SRC01_P0368_C001,SRC01,368,5,© Andy Murray
1821,SRC01_P0466_C001,SRC01,466,9,©FAO/Matteo Sala
1836,SRC01_P0474_C001,SRC01,474,9,©FAO/Matteo Sala
1838,SRC01_P0476_C001,SRC01,476,9,© FAO/Matteo Sala

In [40]:
before_count = len(chunks_df)

chunks_df = chunks_df[~credit_mask].copy()
chunks_df.reset_index(drop=True, inplace=True)

after_count = len(chunks_df)

print("Chunks before cleanup:", before_count)
print("Chunks after cleanup:", after_count)
print("Noise chunks removed:", before_count - after_count)

Chunks before cleanup: 6876
Chunks after cleanup: 6858
Noise chunks removed: 18

In [41]:
print("Final chunks:", len(chunks_df))

print("Duplicate IDs:",
      chunks_df["chunk_id"].duplicated().sum())

print("Missing text:",
      chunks_df["text"].isnull().sum())

print("Empty text:",
      (chunks_df["text"].str.strip() == "").sum())

print("Chunks > 256 tokens:",
      (chunks_df["token_count"] > 256).sum())

print("\nChunks per source:")
print(chunks_df.groupby("source_id").size())

Final chunks: 6858
Duplicate IDs: 0
Missing text: 0
Empty text: 0
Chunks > 256 tokens: 0

Chunks per source:
source_id
SRC01    2620
SRC02    3526
SRC03     589
SRC04      25
SRC05      98
dtype: int64

In [42]:
weird_short = chunks_df[
    chunks_df["token_count"] < 20
][
    ["chunk_id", "source_id", "page_number", "token_count", "text"]
]

weird_short

,chunk_id,source_id,page_number,token_count,text
0,SRC01_P0001_C001,SRC01,1,16,STATE of KNOWLEDGE of SOIL BIODIVERSITY Status...
10,SRC01_P0005_C002,SRC01,5,17,soil biodiversity 98 2. 4. 1 | spatial pattern...
24,SRC01_P0012_C002,SRC01,12,11,responded to the survey 445 references 447
62,SRC01_P0027_C004,SRC01,27,15,of threatened species ld | land degradation ld...
66,SRC01_P0028_C004,SRC01,28,14,##cados pncti | technology and innovation plan
745,SRC01_P0206_C001,SRC01,206,12,State of knowledge of soil biodiversity 176 © ...
746,SRC01_P0207_C001,SRC01,207,12,Contributions of soil biodiversity to ecosyste...
747,SRC01_P0208_C001,SRC01,208,12,State of knowledge of soil biodiversity 178 © ...
748,SRC01_P0209_C001,SRC01,209,12,Contributions of soil biodiversity to ecosyste...
1035,SRC01_P0273_C004,SRC01,273,19,the highest rate of global warming and expansi...
1065,SRC01_P0280_C003,SRC01,280,5,low low low
1339,SRC01_P0347_C003,SRC01,347,17,"special events have been celebrated, including..."
1390,SRC01_P0365_C003,SRC01,365,15,asset from which ecosystem services are produc...
1489,SRC01_P0390_C001,SRC01,390,13,State of knowledge of soil biodiversity 360 or...
1510,SRC01_P0393_C006,SRC01,393,11,##tkatalog _ node. html
1601,SRC01_P0412_C006,SRC01,412,17,% d1 % 8c % 20 2017 % 20ukr. pdf
1805,SRC01_P0465_C001,SRC01,465,3,435
3186,SRC03_P0164_C001,SRC03,164,16,Global guidelines for the restoration of degra...
3205,SRC03_P0171_C001,SRC03,171,3,﻿ 149
3365,SRC02_P0016_C003,SRC02,16,19,251 5. 8 environmental and other benefits of i...
3373,SRC02_P0019_C003,SRC02,19,17,2 examples of sources of incentives to support...
3393,SRC02_P0025_C001,SRC02,25,15,"xxiii PART B – DRIVERS, STATUS AND TRENDS Chap..."
3469,SRC02_P0045_C001,SRC02,45,5,Part A OVERVIEW
3499,SRC02_P0050_C007,SRC02,50,5,ecosystem services.
3884,SRC02_P0107_C001,SRC02,107,9,"Part B Drivers, status and trends"
4622,SRC02_P0233_C001,SRC02,233,7,Part C State of MANAGEMENT
5020,SRC02_P0295_C006,SRC02,295,13,"Source: Willer and Lernoud, 2018."
5728,SRC02_P0403_C007,SRC02,403,7,for mountain biodiversity. ”
5815,SRC02_P0421_C001,SRC02,421,7,Part D enabling frameworks
6232,SRC02_P0487_C001,SRC02,487,5,Part E CONCLUSIONs

### Chunk Quality Control

Obvious standalone copyright and image-credit fragments were removed from the
retrieval corpus. Short chunks were otherwise retained because some represent
meaningful section headings, captions, or scientific statements. Aggressive
length-based filtering was avoided to prevent accidental loss of valid
scientific context.

In [43]:
print("FINAL CHUNK CORPUS")
print("------------------")
print("Total chunks:", len(chunks_df))
print("Sources:", chunks_df["source_id"].nunique())
print("Duplicate IDs:", chunks_df["chunk_id"].duplicated().sum())
print("Missing text:", chunks_df["text"].isnull().sum())
print("Empty text:", (chunks_df["text"].str.strip() == "").sum())
print("Maximum tokens:", chunks_df["token_count"].max())
print("Chunks exceeding MiniLM limit:",
      (chunks_df["token_count"] > embedding_model.max_seq_length).sum())

FINAL CHUNK CORPUS
------------------
Total chunks: 6858
Sources: 5
Duplicate IDs: 0
Missing text: 0
Empty text: 0
Maximum tokens: 223
Chunks exceeding MiniLM limit: 0

## 4. Generate Semantic Embeddings

Each validated scientific chunk is converted into a semantic vector using
the `all-MiniLM-L6-v2` sentence-transformer model.

These embeddings represent the meaning of each chunk and will allow
scientifically relevant passages to be retrieved based on semantic similarity
rather than exact keyword matching.

In [44]:
test_texts = chunks_df["text"].head(3).tolist()

test_embeddings = embedding_model.encode(
    test_texts,
    normalize_embeddings=True
)

print("Number of test embeddings:", len(test_embeddings))
print("Embedding dimensions:", test_embeddings.shape)

Number of test embeddings: 3
Embedding dimensions: (3, 384)

In [45]:
all_embeddings = embedding_model.encode(
    chunks_df["text"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Embedding generation complete.")
print("Embedding matrix shape:", all_embeddings.shape)

Batches:   0%|          | 0/215 [00:00<?, ?it/s]

Embedding generation complete.
Embedding matrix shape: (6858, 384)

In [46]:
import numpy as np

print("Number of chunks:", len(chunks_df))
print("Number of embeddings:", len(all_embeddings))
print("Embedding dimensions:", all_embeddings.shape[1])

print("Contains NaN:", np.isnan(all_embeddings).any())
print("Contains infinity:", np.isinf(all_embeddings).any())

Number of chunks: 6858
Number of embeddings: 6858
Embedding dimensions: 384
Contains NaN: False
Contains infinity: False

In [ ]:
## 5. Store Embeddings in ChromaDB

The validated scientific chunks and their MiniLM embeddings are stored in a
persistent ChromaDB collection.

Each vector retains its stable chunk identifier and provenance metadata,
including source document, filename, page number, and chunk index.

In [47]:
import chromadb

chroma_path = "../chroma_db"

client = chromadb.PersistentClient(
    path=chroma_path
)

print("ChromaDB client created.")

ChromaDB client created.

In [48]:
collection_name = "biodiversity_scientific_knowledge"

try:
    client.delete_collection(collection_name)
    print("Old collection removed.")
except Exception:
    print("No existing collection found.")

collection = client.create_collection(
    name=collection_name,
    metadata={
        "description": "Scientific biodiversity knowledge corpus",
        "embedding_model": "all-MiniLM-L6-v2",
        "chunking": "sentence-aware token-safe",
        "target_tokens": 220
    }
)

print("Fresh collection created.")

No existing collection found.
Fresh collection created.

In [49]:
ids = chunks_df["chunk_id"].tolist()
documents = chunks_df["text"].tolist()

metadatas = chunks_df[
    [
        "source_id",
        "filename",
        "page_number",
        "chunk_index"
    ]
].to_dict("records")

print("IDs:", len(ids))
print("Documents:", len(documents))
print("Metadata records:", len(metadatas))
print("Embeddings:", len(all_embeddings))

IDs: 6858
Documents: 6858
Metadata records: 6858
Embeddings: 6858

In [50]:
batch_size = 500

for start in range(0, len(chunks_df), batch_size):

    end = min(start + batch_size, len(chunks_df))

    collection.add(
        ids=ids[start:end],
        documents=documents[start:end],
        metadatas=metadatas[start:end],
        embeddings=all_embeddings[start:end].tolist()
    )

    print(f"Stored {end}/{len(chunks_df)} chunks")

Stored 500/6858 chunks
Stored 1000/6858 chunks
Stored 1500/6858 chunks
Stored 2000/6858 chunks
Stored 2500/6858 chunks
Stored 3000/6858 chunks
Stored 3500/6858 chunks
Stored 4000/6858 chunks
Stored 4500/6858 chunks
Stored 5000/6858 chunks
Stored 5500/6858 chunks
Stored 6000/6858 chunks
Stored 6500/6858 chunks
Stored 6858/6858 chunks

In [51]:
print("Chunks in DataFrame:", len(chunks_df))
print("Chunks in ChromaDB:", collection.count())

assert collection.count() == len(chunks_df)

print("\nChromaDB validation passed.")

Chunks in DataFrame: 6858
Chunks in ChromaDB: 6858

ChromaDB validation passed.

## 6. Semantic Top-k Retrieval

A semantic retrieval function is implemented to convert a user query into a
MiniLM embedding and search ChromaDB for the most relevant scientific chunks.

The retriever returns the top-k matching chunks together with their stable
chunk IDs, source documents, page numbers, and similarity distances for
traceable scientific evidence retrieval.

In [52]:
def retrieve(query, top_k=3):

    # Convert the question into an embedding
    query_embedding = embedding_model.encode(
        query,
        normalize_embeddings=True
    )

    # Search ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=top_k
    )

    retrieved_chunks = []

    for i in range(len(results["ids"][0])):

        retrieved_chunks.append({
            "chunk_id": results["ids"][0][i],
            "text": results["documents"][0][i],
            "metadata": results["metadatas"][0][i],
            "distance": results["distances"][0][i]
        })

    return retrieved_chunks

In [53]:
query = "How does agricultural diversification affect biodiversity?"

results = retrieve(query, top_k=3)

for rank, result in enumerate(results, start=1):

    print("\n" + "=" * 80)
    print(f"RESULT {rank}")
    print("=" * 80)

    print("Chunk ID:", result["chunk_id"])
    print("Source:", result["metadata"]["source_id"])
    print("Page:", result["metadata"]["page_number"])
    print("Distance:", round(result["distance"], 4))

    print("\nText:")
    print(result["text"])

================================================================================
RESULT 1
================================================================================
Chunk ID: SRC05_P0002_C010
Source: SRC05
Page: 2
Distance: 0.4891

Text:
The most examined diversification practices were organic amendment, re- duced tillage, and crop diversification (146, 118, and 111 effect sizes), whereas noncrop diversification and inoculation, as well as organic farming, were less represented (38, 9, and 34 effect sizes) and need further investigations. Biodiversity and ecosystem service response to diversification The second-order meta-analysis showed that agricultural diversifi- cation strengthens several ecosystem service categories (omnibus test QM = 43.67; P < 0.0001; Fig. 2A) while having a neutral effect on crop yield [lnRR = 0.01; 95% confidence interval (CI) = −0.12 to 0.14].

================================================================================
RESULT 2
================================================================================
Chunk ID: SRC05_P0001_C008
Source: SRC05
Page: 1
Distance: 0.5092

Text:
Functional diversity below ground can also be supported and stimulated through addition of organic inputs (e.g., manure and crop residues) or reducing soil disturbance (e.g., reduced tillage), which lead to soil stratification and thereby more niches (8, 9). Despite a rapidly growing body of research assessing the impacts of agricul- tural diversification practices on biodiversity and related ecosystem services (7, 10–12), there is no comprehensive quantitative synthesis of this information. Consequently, we lack the broader understand- ing of whether diversification practices are actually capable of supporting biodiversity and multiple ecosystem services, including crop yields. We investigated the impact of multiple agricultural diversifica- tion practices on biodiversity and related ecosystem services and compared these with cropping systems with less diverse farming practices typical of mainstream agriculture. First, we systematically reviewed published meta-analyses and summarized the number of reported effect sizes (vote count) to assess the current state of knowledge, identify research gaps, and explore general patterns.

================================================================================
RESULT 3
================================================================================
Chunk ID: SRC05_P0001_C004
Source: SRC05
Page: 1
Distance: 0.5203

Text:
Crop management based on diversification practices that en- hance key elements of biodiversity has been suggested to reduce impacts on the environment without negative effects on crop yields (4). Enhancing the diversity of biological communities, both above and below ground, can increase resource use efficiency and the stability of ecosystem production over time (5–7). Agricultural diversifica- tion is the intentional addition of functional biodiversity to cropping systems at multiple spatial and/or temporal scales, and it aims at regenerating biotic interactions underpinning yield-supporting ecosystem services (8). It embraces a variety of practices encom- passing the management of crops, noncrop habitats, soil, and land- scapes (9).

In [54]:
import pandas as pd

golden_df = pd.read_csv("../data/evaluation/golden_cases.csv")

golden_df

,case_id,question,known_soc,known_rainfall,known_land_use,known_biodiversity,missing_variables,required_knowledge,expected_behavior,forbidden_behavior
0,GC01,"A farm has low soil organic carbon, low rainfa...",0.3%,low,monoculture wheat,low species count,none,SOC <-> soil/ecosystem condition; SOC <-> biod...,Notice SOC + rainfall + land use + biodiversit...,Recommend generic 'plant more trees' without a...
1,GC02,"My land already has good soil carbon, decent r...",1.8%,adequate,agroforestry,high species count,none,Maintenance-level agroforestry/high-biodiversi...,Recognize this is a positive baseline; suggest...,Recommend a drastic intervention when conditio...
2,GC03,Biodiversity is declining on my land. Soil org...,0.4%,unknown,unknown,declining,"rainfall, land use",SOC <-> biodiversity decline indicators; what ...,Ask a targeted clarifying question for rainfal...,Fabricate rainfall or land use to produce an a...
3,GC04,We get decent rainfall but our soil carbon is ...,low,adequate,monoculture wheat,unknown,biodiversity indicator,SOC <-> monoculture interaction effects; how a...,Reason about SOC + land use with rainfall as a...,Assume biodiversity is low without evidence or...
4,GC05,What can I do to improve biodiversity on this ...,unknown,unknown,monoculture wheat,unknown,"soil organic carbon, rainfall, biodiversity in...",General monoculture <-> biodiversity evidence ...,Ask for the missing core variables (at minimum...,"Provide a fully specific, quantified recommend..."
5,GC06,"Rainfall here is high, but soil carbon is very...",very low,high,monoculture corn,moderate/stable,none,How high/non-limiting rainfall expands the ran...,Recognize that high rainfall removes the water...,Ignore rainfall as a relevant factor just beca...
6,GC07,"Semi-arid region, soil organic carbon 0.3%, ra...",0.3%,low,monoculture wheat,unknown,biodiversity indicator (optional),SOC <-> soil/ecosystem condition; rainfall (lo...,Recommend an evidence-supported intervention a...,Invent a quantified estimate or timeframe when...
7,GC08,What's the best fertilizer brand for my lawn?,unknown,unknown,lawn,unknown,not applicable - out of scope,Scope boundary definition for the system; how ...,Recognize the question falls outside the syste...,Fabricate an environmental recommendation for ...

## 7. Golden-Case Retrieval Evaluation

Retrieval quality is evaluated using the predefined Phase 1 golden cases.

For GC01–GC07, a case is considered a top-3 retrieval hit when at least one
of the three retrieved chunks contains scientific evidence relevant to the
case's predefined `required_knowledge`.

The criteria are fixed before inspecting retrieval results to avoid
post-hoc relevance judgments.

GC08 is evaluated separately as an out-of-scope case and is not included
in the scientific top-3 hit-rate calculation.

In [55]:
eval_df = golden_df[
    ["case_id", "question", "required_knowledge"]
].copy()

eval_df

,case_id,question,required_knowledge
0,GC01,"A farm has low soil organic carbon, low rainfa...",SOC <-> soil/ecosystem condition; SOC <-> biod...
1,GC02,"My land already has good soil carbon, decent r...",Maintenance-level agroforestry/high-biodiversi...
2,GC03,Biodiversity is declining on my land. Soil org...,SOC <-> biodiversity decline indicators; what ...
3,GC04,We get decent rainfall but our soil carbon is ...,SOC <-> monoculture interaction effects; how a...
4,GC05,What can I do to improve biodiversity on this ...,General monoculture <-> biodiversity evidence ...
5,GC06,"Rainfall here is high, but soil carbon is very...",How high/non-limiting rainfall expands the ran...
6,GC07,"Semi-arid region, soil organic carbon 0.3%, ra...",SOC <-> soil/ecosystem condition; rainfall (lo...
7,GC08,What's the best fertilizer brand for my lawn?,Scope boundary definition for the system; how ...

In [56]:
scientific_eval_df = eval_df[
    eval_df["case_id"] != "GC08"
].copy()

for _, row in scientific_eval_df.iterrows():
    print("=" * 80)
    print(row["case_id"])
    print("QUESTION:")
    print(row["question"])

    print("\nREQUIRED KNOWLEDGE:")
    print(row["required_knowledge"])
    print()

================================================================================
GC01
QUESTION:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?

REQUIRED KNOWLEDGE:
SOC <-> soil/ecosystem condition; SOC <-> biodiversity; rainfall <-> vegetation establishment; rainfall <-> restoration constraints; monoculture <-> biodiversity; land-use diversification interventions; evidence on expected effects

================================================================================
GC02
QUESTION:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do?

REQUIRED KNOWLEDGE:
Maintenance-level agroforestry/high-biodiversity system evidence; SOC <-> biodiversity stability under good conditions; guidance on when no major intervention is warranted

================================================================================
GC03
QUESTION:
Biodiversity is declining on my land. Soil organic carbon is 0.4%.

REQUIRED KNOWLEDGE:
SOC <-> biodiversity decline indicators; what rainfall data is needed and why; what land-use data is needed and why; clarifying-question triggers for missing variables

================================================================================
GC04
QUESTION:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?

REQUIRED KNOWLEDGE:
SOC <-> monoculture interaction effects; how adequate rainfall changes which interventions are viable (non-limiting case); why a biodiversity indicator is needed for a complete recommendation

================================================================================
GC05
QUESTION:
What can I do to improve biodiversity on this farm? It's wheat monoculture.

REQUIRED KNOWLEDGE:
General monoculture <-> biodiversity evidence usable as context; the minimum variable set required before a specific recommendation can be made; clarifying-question triggers

================================================================================
GC06
QUESTION:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now.

REQUIRED KNOWLEDGE:
How high/non-limiting rainfall expands the range of viable restoration and cover-crop interventions; SOC <-> monoculture corn effects; interpreting a moderate/stable biodiversity reading correctly

================================================================================
GC07
QUESTION:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health?

REQUIRED KNOWLEDGE:
SOC <-> soil/ecosystem condition; rainfall (low) <-> water-limited restoration options; semi-arid intercropping/agroforestry evidence as one possible (not mandatory) intervention; credible quantitative studies (e.g. FAO/IPCC) on SOC improvement, where they exist

In [57]:
golden_retrieval_results = []

for _, row in scientific_eval_df.iterrows():

    results = retrieve(
        row["question"],
        top_k=3
    )

    for rank, result in enumerate(results, start=1):

        golden_retrieval_results.append({
            "case_id": row["case_id"],
            "question": row["question"],
            "required_knowledge": row["required_knowledge"],
            "rank": rank,
            "chunk_id": result["chunk_id"],
            "source_id": result["metadata"]["source_id"],
            "page_number": result["metadata"]["page_number"],
            "distance": result["distance"],
            "text": result["text"]
        })

golden_results_df = pd.DataFrame(golden_retrieval_results)

print(
    "Golden cases tested:",
    golden_results_df["case_id"].nunique()
)

print(
    "Total retrieved chunks:",
    len(golden_results_df)
)

Golden cases tested: 7
Total retrieved chunks: 21

In [58]:
for case_id in scientific_eval_df["case_id"]:

    case_results = golden_results_df[
        golden_results_df["case_id"] == case_id
    ]

    print("\n" + "=" * 100)
    print(case_id)
    print("=" * 100)

    print("\nQUESTION:")
    print(case_results.iloc[0]["question"])

    print("\nREQUIRED KNOWLEDGE:")
    print(case_results.iloc[0]["required_knowledge"])

    for _, result in case_results.iterrows():

        print("\n" + "-" * 80)

        print(
            f'RANK {result["rank"]} | '
            f'{result["chunk_id"]} | '
            f'{result["source_id"]} | '
            f'Page {result["page_number"]} | '
            f'Distance {result["distance"]:.4f}'
        )

        print("\nTEXT:")
        print(result["text"])

====================================================================================================
GC01
====================================================================================================

QUESTION:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?

REQUIRED KNOWLEDGE:
SOC <-> soil/ecosystem condition; SOC <-> biodiversity; rainfall <-> vegetation establishment; rainfall <-> restoration constraints; monoculture <-> biodiversity; land-use diversification interventions; evidence on expected effects

--------------------------------------------------------------------------------
RANK 1 | SRC01_P0270_C005 | SRC01 | Page 270 | Distance 0.7656

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

--------------------------------------------------------------------------------
RANK 2 | SRC02_P0272_C003 | SRC02 | Page 272 | Distance 0.7977

TEXT:
The consequences of this have included decreases in soil organic matter and high discharge of nutrients into the environment in areas where large numbers of animals are raised in intensive units, with neg- ative impacts in turn on aquatic, soil and other biodiversity (see also Chapter 3). Time-series data for such changes are rare. However, data from the above-mentioned Eurostat database on agri- environmental indicators indicate that the number of mixed crop–livestock farms in the European Union declined by 45 percent between 2005 and 2013, and that the area under mixed crop–livestock systems decreased by 26 percent over the same period (Eurostat, 2016). Low-income countries have, in contrast, seen a general trend towards greater integration of crop and livestock production activities as population density has increased and the availability of land has declined (Robinson et al., 2011; Thornton and Herrero, 2001).

--------------------------------------------------------------------------------
RANK 3 | SRC01_P0234_C002 | SRC01 | Page 234 | Distance 0.8004

TEXT:
For example, losses of carbon, soil structure and soil biodiversity can reduce an ecosystem’s ability to sequester carbon (Wiesmeier et al., 2019). Changes in these soil properties also decrease water infiltration capacity, root penetration and access to nutrients for plants. In concert, all of these changes increase the risk of soil erosion, land degradation, compaction and salinization, thus reducing agricultural productivity which threatens the achievements of Sustainable Development Goals, particularly SDG 2 (zero hunger). The excessive use of fertilizers and pesticides affects the quality of water (Foster and Custodio, 2019) posing several threats to other ecosystems, and also poses direct threats to animal and human health. Ecosystem services provided by beneficial crop-associated organisms, such as regulation of pest and diseases (Tamburini et al., 2016) and pollination, are also reduced (Bretagnolle and Gaba, 2015).

====================================================================================================
GC02
====================================================================================================

QUESTION:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do?

REQUIRED KNOWLEDGE:
Maintenance-level agroforestry/high-biodiversity system evidence; SOC <-> biodiversity stability under good conditions; guidance on when no major intervention is warranted

--------------------------------------------------------------------------------
RANK 1 | SRC01_P0469_C001 | SRC01 | Page 469 | Distance 0.7557

TEXT:
National Survey on Status of Soil Biodiversity:Knowledge, Challenges and Opportunities 439 I | ASSESSMENT 2.1 How do you perceive the importance of ecosystem services provided by soil biodiversity to this country over the past 10 years (1 being the lowest important and 5 being the highest). Please provide additional information to support the answers in the comments area below. Soil formation g. Soil formation h. Nutrient cycling i. Control soil erosion j. Atmospheric composition and climate regulation including floods k. Carbon sequestration and climate change responses l. Regulation of water supply and quality m. Pollutant degradation and soil remediation n. Recycling of waste biomass, nutrients and water o. Restoration of degraded lands and ecosystems p. Nitrogen fixation q. Pest and disease regulation r. Landscape support (effects on above-ground biodiversity in agricultural landscapes) s. Enhance agricultural productivity and economic profitability t. Enhance nutritional quality of food u. Natural hazard regulation v. Human health w. None x. Unknown y.

--------------------------------------------------------------------------------
RANK 2 | SRC01_P0189_C004 | SRC01 | Page 189 | Distance 0.7603

TEXT:
General guidelines to make soils more resilient to climate change should include the following: (1) Conservation of C-rich soils like peatlands, forest soils and permanent grasslands should become a priority. (2) Improve SOC pool by adopting less intensive agricultural practices that limit/exclude agrochemical use and maintain a live plant cover (such as conservation agriculture) or use organic amendments such as mulch, compost. (3) Adopting ‘paludiculture’ practices to cultivate organic soils without drainage, whereas land use practices that require drainage should, if possible, be relocated to areas with mineral soils. (4) Increase soil biodiversity by protecting natural areas, keeping habitat heterogeneity and diversifying land use options. The great recent advances in collating and mapping soil biodiversity data at global scales (see for example Tedersoo et al., 2014; van den Hoogen et al., 2019; Phillips et al., 2019) means that it will now be possible to link specific soil biota groups to terrestrial carbon stocks.

--------------------------------------------------------------------------------
RANK 3 | SRC01_P0180_C005 | SRC01 | Page 180 | Distance 0.7932

TEXT:
Healthy soils unify productive and natural systems by focusing on maintaining an intact, diverse below-ground ecosystem that ensures the flow of carbon, nutrients, and energy necessary for resilient landscapes (Kibblewhite et al., 2008). As a terrestrial system accrues soil organic matter, both soil health and soil organic carbon increase and a multitude of co-benefits emerge. Future plans, challenges and gaps While the potential for synergies from harnessing soil biodiversity for climate action with other global agendas is enormous, transformative policies and action and enabling conditions are necessary for success. Existing nature protection policies need to be fully implemented, and there is a pressing need for support and security of tenure for those at the front line of protecting, restoring and caring for land and soil and conserving its biodiversity, including indigenous peoples and local communities. There is also a need for education and awareness raising, capacity strengthening and full engagement across the public and private sector towards overcoming financial barriers and implementing natural capital accounting and payment for ecosystem services.

====================================================================================================
GC03
====================================================================================================

QUESTION:
Biodiversity is declining on my land. Soil organic carbon is 0.4%.

REQUIRED KNOWLEDGE:
SOC <-> biodiversity decline indicators; what rainfall data is needed and why; what land-use data is needed and why; clarifying-question triggers for missing variables

--------------------------------------------------------------------------------
RANK 1 | SRC01_P0324_C001 | SRC01 | Page 324 | Distance 0.5092

TEXT:
State of knowledge of soil biodiversity 294 5.4.3 | SOIL BIODIVERSITY AS A FARMER’S TOOL The adoption of soil conservation practices such as reduced tillage, improved residue management, reduced bare fallow and conservation reserve plantings have stabilized, and partially reversed, soil organic carbon (SOC) loss in North American agricultural soils (Paustian et al., 2016). Improved grazing management, fertilization, and sowing legumes and improved grass species are additional ways to increase soil C by as much as 1 Mg C/ ha/yr in best cases (Conant et al., 2016). Restoration of late-successional grassland plant diversity leads to accelerating annual carbon storage rates on degraded and abandoned agricultural lands that, by the second period (years 13 to 22), are 200 percent greater in the highest diversity treatment than during succession at this site, and 70 percent greater than in monocultures.

--------------------------------------------------------------------------------
RANK 2 | SRC01_P0236_C003 | SRC01 | Page 236 | Distance 0.5830

TEXT:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

--------------------------------------------------------------------------------
RANK 3 | SRC02_P0143_C001 | SRC02 | Page 143 | Distance 0.5835

TEXT:
99 Drivers of change of biodiversity for food and agriculture 3 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE characteristics and the diversity of the local soil fauna and flora. Soil biodiversity is greatly influenced by the quantity and quality of organic matter present in the soil. The biodiversity in overexploited soils is less abundant, dominated by fewer species and characterized by simpler trophic networks (Creamer et al., 2016). Loss of soil organic matter may lead to weaker soil structure, soil sealing, surface crusting and/or compaction, reducing the soil’s capacity to capture and store water, buffer its pH and regulate its salinity. Declines in the soil’s organic-matter and nutri- ent content are caused by misbalances between inputs and outputs. Inputs are provided by plant litter and by the addition of organic matter and nutrients (e.g. in the form of manure – FAO, 2018f). Losses occur through the decomposition of organic matter and soil erosion.

====================================================================================================
GC04
====================================================================================================

QUESTION:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?

REQUIRED KNOWLEDGE:
SOC <-> monoculture interaction effects; how adequate rainfall changes which interventions are viable (non-limiting case); why a biodiversity indicator is needed for a complete recommendation

--------------------------------------------------------------------------------
RANK 1 | SRC01_P0601_C005 | SRC01 | Page 601 | Distance 0.8650

TEXT:
2015. Soil fertility decline at the base of rural poverty in sub-Saharan Africa. Nature Plants, 1: 15101. doi: 10.1038/nplants.2015.101 Vargas-Rojas, R., Cuevas-Corona, R., Yigini, Y., Tong, Y., Bazza, Z. & Wiese, L. 2019. Unlocking the Potential of Soil Organic Carbon: A Feasible Way Forward. Pages 373–395 in T. Ginzky, H. Dooley, E. Heuser, I.L. Kasimbazi, E. Markus, T. Qin, eds. International Yearbook of Soil Law and Policy, 2018, pp. 373-395. Cham, Switzerland. Springer. Vasenev, V. & Kuzyakov, K. 2018. Urban soils as hot spots of anthropogenic carbon accumulation: Review of stocks, mechanisms and driving factors.

--------------------------------------------------------------------------------
RANK 2 | SRC01_P0270_C005 | SRC01 | Page 270 | Distance 0.8686

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

--------------------------------------------------------------------------------
RANK 3 | SRC01_P0588_C001 | SRC01 | Page 588 | Distance 0.8877

TEXT:
State of knowledge of soil biodiversity 558 Smith, P., House, J.I., Bustamante, M., Sobocká, J., Harper, R., Pan, G., West, P.C., et al. 2016. Global Change Pressures on Soils from Land Use and Management. Global Change Biology, 22(3): 1008–28. https://doi.org/10.1111/gcb.13068. Smith, P., Soussana, J., Angers, D., Schipper, L., Chenu, C., Rasse, D.P., Batjes, N.H., et al. 2019. How to measure, report and verify soil carbon change to realize the potential of soil carbon sequestration for atmospheric greenhouse gas removal. Global Change Biology, 26(1): 1–23. Smith, S.E. & Read, D.J. 2008.

====================================================================================================
GC05
====================================================================================================

QUESTION:
What can I do to improve biodiversity on this farm? It's wheat monoculture.

REQUIRED KNOWLEDGE:
General monoculture <-> biodiversity evidence usable as context; the minimum variable set required before a specific recommendation can be made; clarifying-question triggers

--------------------------------------------------------------------------------
RANK 1 | SRC02_P0525_C006 | SRC02 | Page 525 | Distance 0.7333

TEXT:
2016. Herbicides do not ensure for higher wheat yield, but eliminate rare plant species. Scientific Reports, 6: 30112. Gabriel, D., Sait, S.M., Kunin, W.E. & Benton, T.G. 2013. Food production vs. biodiversity: comparing organic and conventional agriculture. Journal of Applied Ecology, 50(2): 355–364. Gadgil, M., Berkes, F. & Folke, C. 1993. Indigenous knowledge for biodiversity conservation. Ambio, 22(2–3): 151–156. Galhena, D.H., Freed, R. & Maredia, K.M. 2013. Home gardens: a promising approach to enhance household food security and wellbeing. Agriculture & Food Security, 2(8). Gallai, N., Salles, J.M., Settele, J. & Vaissière, B.E. 2009. Economic valuation of the vulnerability of world agriculture confronted with pollinator decline.

--------------------------------------------------------------------------------
RANK 2 | SRC05_P0008_C003 | SRC05 | Page 8 | Distance 0.7669

TEXT:
S. Srivastava, S. Naeem, Biodiversity loss and its impact on humanity. Nature 486, 59–67 (2012). 6. C. Wagg, S. F. Bender, F. Widmer, M. G. van der Heijden, Soil biodiversity and soil community composition determine ecosystem multifunctionality. Proc. Natl. Acad. Sci. U.S.A. 111, 5266–5270 (2014). 7. D. Renard, D. Tilman, National food production stabilized by crop diversity. Nature 571, 257–260 (2019). 8. C. Kremen, A. Iles, C. Bacon, Diversified farming systems: An agroecological, systems- based alternative to modern industrial agriculture. Ecol. Soc. 17, 44 (2012). 9. C. Kremen, A. Miles, Ecosystem services in biologically diversified versus conventional farming systems: Benefits, externalities, and trade-offs. Ecol. Soc.

--------------------------------------------------------------------------------
RANK 3 | SRC02_P0157_C001 | SRC02 | Page 157 | Distance 0.7976

TEXT:
113 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Chapter 4 The status and trends of biodiversity for food and agriculture Key messages • Many key components of biodiversity for food and agriculture (BFA) at genetic, species and ecosystem levels are in decline. • Evidence suggests that the proportion of animal breeds at risk of extinction is increasing, and that – for some species and in some areas – crop diversity in farmers’ fields is decreasing and threats to diversity are increasing.

====================================================================================================
GC06
====================================================================================================

QUESTION:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now.

REQUIRED KNOWLEDGE:
How high/non-limiting rainfall expands the range of viable restoration and cover-crop interventions; SOC <-> monoculture corn effects; interpreting a moderate/stable biodiversity reading correctly

--------------------------------------------------------------------------------
RANK 1 | SRC01_P0270_C005 | SRC01 | Page 270 | Distance 0.7429

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

--------------------------------------------------------------------------------
RANK 2 | SRC01_P0273_C002 | SRC01 | Page 273 | Distance 0.7833

TEXT:
Planting of the shrub Haloxylon ammodendron increased the diversity of predators, collembola and fungi, decreased the diversity of insect herbivores and oribatida and did not change bacterial diversity, while Populus gunsuensis planting increased the diversity of virtually all groups in north-west China (Li et al., 2018). A switch over to wheat-maize intercropping from wheat and maize monocultures is leading to more efficient biocontrol (Liu et al., 2018). In India, mixed planting of leguminous and non-leguminous trees resulted in an 8 to 65-fold increase depending on season and taxon (Tripathi et al., 2009) and organic cowpea/maize/Lucerne mixed cropping a 7-26 percent increase in collembola, oribatid mites, nematodes, actinomycetes and fungi populations (Roy et al., 2012). The ecoregion is also facing increasing urbanization and climate change but studies evaluating them are lacking.

--------------------------------------------------------------------------------
RANK 3 | SRC01_P0253_C001 | SRC01 | Page 253 | Distance 0.8324

TEXT:

In [59]:
for case_id in ["GC04", "GC07"]:

    case_results = golden_results_df[
        golden_results_df["case_id"] == case_id
    ]

    print("\n", "=" * 80)
    print(case_id)

    for _, row in case_results.iterrows():
        print(
            row["rank"],
            row["chunk_id"],
            row["source_id"],
            row["page_number"],
            round(row["distance"], 4)
        )

 ================================================================================
GC04
1 SRC01_P0601_C005 SRC01 601 0.865
2 SRC01_P0270_C005 SRC01 270 0.8686
3 SRC01_P0588_C001 SRC01 588 0.8877

 ================================================================================
GC07
1 SRC01_P0344_C001 SRC01 344 0.5801
2 SRC01_P0469_C001 SRC01 469 0.5877
3 SRC01_P0270_C005 SRC01 270 0.6326

In [60]:


for case_id in ["GC04", "GC07"]:

    question = scientific_eval_df.loc[
        scientific_eval_df["case_id"] == case_id,
        "question"
    ].iloc[0]

    diagnostic_results = retrieve(question, top_k=10)

    print("\n" + "=" * 100)
    print(case_id)
    print("=" * 100)

    for rank, result in enumerate(diagnostic_results, start=1):

        print(
            f'\nRANK {rank} | '
            f'{result["chunk_id"]} | '
            f'{result["metadata"]["source_id"]} | '
            f'Page {result["metadata"]["page_number"]} | '
            f'Distance {result["distance"]:.4f}'
        )

        print(result["text"][:500])

====================================================================================================
GC04
====================================================================================================

RANK 1 | SRC01_P0601_C005 | SRC01 | Page 601 | Distance 0.8650
2015. Soil fertility decline at the base of rural poverty in sub-Saharan Africa. Nature Plants, 1: 15101. doi: 10.1038/nplants.2015.101 Vargas-Rojas, R., Cuevas-Corona, R., Yigini, Y., Tong, Y., Bazza, Z. & Wiese, L. 2019. Unlocking the Potential of Soil Organic Carbon: A Feasible Way Forward. Pages 373–395 in T. Ginzky, H. Dooley, E. Heuser, I.L. Kasimbazi, E. Markus, T. Qin, eds. International Yearbook of Soil Law and Policy, 2018, pp. 373-395. Cham, Switzerland. Springer. Vasenev, V. & Kuzyak

RANK 2 | SRC01_P0270_C005 | SRC01 | Page 270 | Distance 0.8686
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low

RANK 3 | SRC01_P0588_C001 | SRC01 | Page 588 | Distance 0.8877
State of knowledge of soil biodiversity 558 Smith, P., House, J.I., Bustamante, M., Sobocká, J., Harper, R., Pan, G., West, P.C., et al. 2016. Global Change Pressures on Soils from Land Use and Management. Global Change Biology, 22(3): 1008–28. https://doi.org/10.1111/gcb.13068. Smith, P., Soussana, J., Angers, D., Schipper, L., Chenu, C., Rasse, D.P., Batjes, N.H., et al. 2019. How to measure, report and verify soil carbon change to realize the potential of soil carbon sequestration for atmosph

RANK 4 | SRC01_P0234_C001 | SRC01 | Page 234 | Distance 0.8989
State of knowledge of soil biodiversity 204 2013), leads to losses of C and N from soil in the form of gases. Furthermore, there may be a decline in the resistance and resilience of food webs to environmental stressors, such as drought (De Vries et al., 2012). Adopting sustainable agricultural practices might lead to recovery of biological communities, but recovery might take years or even decades depending on organisms (de Groot et al., 2016). The threats posed by agricultural intensification a

RANK 5 | SRC01_P0276_C001 | SRC01 | Page 276 | Distance 0.9138
State of knowledge of soil biodiversity 246 The loss of soil organic matter, is especially relevant in Mediterranean soils with semi-arid climate (Novara et al., 2011; Laudicina et al., 2015). According to Turbe et al., (2010) the largest emissions of CO2 from soils are resulting from land use change (for example, from grassland to agricultural fields) and the related drainage of organic soils in Europe. However, precise future estimations are difficult to extract from the literature, given the

RANK 6 | SRC01_P0545_C002 | SRC01 | Page 545 | Distance 0.9183
2015. Restoring soil quality to mitigate soil degradation. Sustainability, 7: 5875-5895. https://doi.org/10.3390/su7055875 Lal, R. 2019. Accelerated soil erosion as a source of atmospheric CO2. Soil and Tillage Research, 188: 35–40. https://doi.org/10.1016/j.still.2018.02.001 Lal, R., Horn, R. & Kosaki, T. 2018. Soil and sustainable development goals. Stuttgart, Germany. Catena-Schweizerbart. 213 pp. Lal, R., Griffin, M., Apt, J., Lave, L. & Morgan, M.G. 2004. Managing Soil Carbon. Science, 304:

RANK 7 | SRC01_P0187_C003 | SRC01 | Page 187 | Distance 0.9252
Global estimates indicate that soil organic carbon is being lost at a rate equivalent to 10 to 20 percent of total global carbon dioxide emissions (Olivier et al., 2015). Since organic matter decays faster with increasing temperatures, the areas surrounding the pan-Arctic region (including tundra, boreal forests and peatlands ecosystems) are of special concern because they store vast amounts of carbon that can be released into the atmosphere (~1700 Pg total C; Parish et al., 2008; Tarnocai et al

RANK 8 | SRC03_P0068_C002 | SRC03 | Page 68 | Distance 0.9293
Millet and groundnut yields on these soils are over 50 percent higher than on other croplands (CIRAD-CTFT, 1989). The application of organic amendments such as sewage sludge has been used widely in agriculture and commercial forestry as a way of improving soil fertility and water availability, promoting biological activity and facilitating seedling establishment. Another treatment that promotes growth is the incorporation of fresh organic waste (rather than composted waste) into plantation furro

RANK 9 | SRC01_P0545_C001 | SRC01 | Page 545 | Distance 0.9310
References 515 Ladeiro, B. 2012. Saline Agriculture in the 21st Century: Using Salt Contaminated Resources to Cope Food Requirements. Journal of Botany, 2012: Article 310705. Lal, R. 2001. Soil degradation by erosion. Land Degradation and Development, 12: 519–539. Lal, R. 2004. Soil carbon sequestration impacts on global climate change and food security. Science, 304(5677): 1623-1627. DOI: 10.1126/science.1097396. Lal, R. 2010a. Beyond Copenhagen: mitigating climate change and achieving food sec

RANK 10 | SRC01_P0609_C006 | SRC01 | Page 609 | Distance 0.9346
Soil carbon sequestration accelerated by restoration of grassland biodiversity. Nature Communications, 10: 718. Yang, G., Liu, N., Lu, W., Wang, S., Kan, H., Zhang, Y., Xu, L., & Chen, Y. 2014. The interaction between arbuscular mycorrhizal fungi and soil phosphorus availability influences plant community productivity and ecosystem stability. Journal of Ecology, 2014, 102, 1072–1082

====================================================================================================
GC07
====================================================================================================

RANK 1 | SRC01_P0344_C001 | SRC01 | Page 344 | Distance 0.5801
State of knowledge of soil biodiversity 314 10 0 20 What are the major practices in this country that might have negatively impacted soil biodiversity in the last 10 years (1 being the lowest important and 5 being the highest)?

RANK 2 | SRC01_P0469_C001 | SRC01 | Page 469 | Distance 0.5877
National Survey on Status of Soil Biodiversity:Knowledge, Challenges and Opportunities 439 I | ASSESSMENT 2.1 How do you perceive the importance of ecosystem services provided by soil biodiversity to this country over the past 10 years (1 being the lowest important and 5 being the highest). Please provide additional information to support the answers in the comments area below. Soil formation g. Soil formation h. Nutrient cycling i. Control soil erosion j. Atmospheric composition and climate reg

RANK 3 | SRC01_P0270_C005 | SRC01 | Page 270 | Distance 0.6326
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low

RANK 4 | SRC01_P0471_C001 | SRC01 | Page 471 | Distance 0.6566
National Survey on Status of Soil Biodiversity:Knowledge, Challenges and Opportunities 441 i. Antimicrobial resistance j. None k. Unknown l. Others (please specify): Additional comments: Please link any relevant publications, documents or websites used in compiling these data. 2.8 What are the major practices in this country that might have negatively impacted soil biodiversity in the last 10 years (1 being the lowest impact and 5 being the highest)? Please specify in the comments area below how

RANK 5 | SRC01_P0449_C004 | SRC01 | Page 449 | Distance 0.6620
For example, the commercial inoculation of crop legumes grown with selected efficient bacteria has been shown to improve overall sustainable crop production and nutrition, while also benefiting the environment (Stagnari, Maggio, Galieni et al., 2017). The United States of America reported that soil biodiversity has a number of practical applications, ranging from biological nitrogen fixation, carbon cycling (including sequestration, but also CH4 and CO2 emissions), to the creation and stabilizat

RANK 6 | SRC01_P0297_C001 | SRC01 | Page 297 | Distance 0.6688
Responses and opportunities 267 Figure 5.1.1 (previous page) | Management of soil biodiversity Along with other strategies, some environmental problems and crop needs can be tackled with nature-based solutions. The development of these types of solutions should be based on comprehensive approaches that consider the interactions of plants with soil biodiversity as well as the management of beneficial and harmful organisms. 5.2 | ECOSYSTEM RESTORATION: STARTING FROM THE GROUND AND LEVERAGING SOIL

RANK 7 | SRC02_P0143_C001 | SRC02 | Page 143 | Distance 0.6720
99 Drivers of change of biodiversity for food and agriculture 3 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE characteristics and the diversity of the local soil fauna and flora. Soil biodiversity is greatly influenced by the quantity and quality of organic matter present in the soil. The biodiversity in overexploited soils is less abundant, dominated by fewer species and characterized by simpler trophic networks (Creamer et al., 2016). Loss of soil organic matter may lead to we

RANK 8 | SRC01_P0302_C001 | SRC01 | Page 302 | Distance 0.6802
State of knowledge of soil biodiversity 272 5.2.2 | NOVEL WHOLE-ECOSYSTEM APPROACHES FOR SOIL RESTORATION AND SOIL MANAGEMENT Human management of agricultural land and other soils is known to reduce soil biodiversity. Examples include negative effects of tillage (Tsiafouli et al., 2015), mineral fertilizers (Ramirez et al., 2012) and pesticides (Thiele-Bruhn et al., 2012) on field level (functional) soil diversity. Insufficient return of organic matter to agricultural soils has led to severe deg

RANK 9 | SRC02_P0191_C001 | SRC02 | Page 191 | Distance 0.6991
147 THE STATus AND TRENDS OF BIODIVERSITY FOR FOOD AND AGRICULTURE 4 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Table 4.8 Summary of regional extent, trends and uncertainties of soil-biodiversity loss presented in the Status of the World’s Soil Resources Condition and trend Confidence Region Summary Very poor Poor Fair Good Very good In condition In trend Sub-Saharan Africa Sub-Saharan Africa suffers a high rate of deforestation. The areas most affected are those in the moist

RANK 10 | SRC01_P0294_C005 | SRC01 | Page 294 | Distance 0.7010
Knowledge on how the physical, chemical and biological components interact is needed in order to restore and manage the integrity and functioning of soils, and how soil biodiversity enhances soil multi-functionality. The FAO and ITPS (2015) Status of the World Soil Resources Report states that 33 percent of land is “moderately to highly degraded.” This calls for immediate action to restore degraded lands through the implementation of sustainable soil management, particularly in regions where fra

In [61]:
diagnostic_queries = [
    "How does low soil organic carbon affect soil biodiversity and soil health?",
    "What restoration practices are suitable under low rainfall or semi-arid conditions?",
    "How can crop diversification, intercropping, or agroforestry improve biodiversity in monoculture farming?"
]

for query in diagnostic_queries:

    print("\n" + "=" * 100)
    print("QUERY:", query)
    print("=" * 100)

    results = retrieve(query, top_k=3)

    for rank, result in enumerate(results, start=1):

        print(
            f'\nRANK {rank} | '
            f'{result["chunk_id"]} | '
            f'{result["metadata"]["source_id"]} | '
            f'Page {result["metadata"]["page_number"]} | '
            f'Distance {result["distance"]:.4f}'
        )

        print(result["text"][:600])

====================================================================================================
QUERY: How does low soil organic carbon affect soil biodiversity and soil health?
====================================================================================================

RANK 1 | SRC01_P0236_C003 | SRC01 | Page 236 | Distance 0.4231
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor exp

RANK 2 | SRC01_P0227_C001 | SRC01 | Page 227 | Distance 0.5185
Threats to soil biodiversity - global and regional trends 197 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 C C C C C C C C C C C Impacts on soil biodiversity Erosion and landslides drivers and effects on soils • Detachment, transport and deposition of soil particles by water or wind. • Loss of organic matter and changes in soil physical and chemical properties. • Creation of degraded and enriched depositional environments. • Inhabitants of upper soil layers may be eliminated or displaced. • Loss of habitat and decrese in its quality for soil biota. • Spread of pests and pathogens. • Reduced soi

RANK 3 | SRC01_P0550_C001 | SRC01 | Page 550 | Distance 0.5234
State of knowledge of soil biodiversity 520 Jordán López, A., García Moreno, J., Gordillo Rivero, Á.J., Martínez Zavala, L.M. & Cerdá García, A. 2014. Organic carbon, water repellency and soil stability to slaking under different crops and managements: a case study at aggregate and intra-aggregate scales. Soil Discuss, (1): 295-325. Lorenz, K. & Lal, R. 2009. Biogeochemical C and N cycles in urban soils. Environment International, 35: 1–8. doi: https://doi.org/10.1016/j.envint.2008.05.006 Lorenz, K., Lal, R. & Ehlers, K. 2019. Soil organic carbon stocks as an indicator for monitoring land ans

====================================================================================================
QUERY: What restoration practices are suitable under low rainfall or semi-arid conditions?
====================================================================================================

RANK 1 | SRC03_P0065_C002 | SRC03 | Page 65 | Distance 0.6858
In other words, the restored ecosystem is expected to eventually emulate the attributes and species composition of the reference site(s), and the goals and strategies of the restoration project should be developed largely in light of that expectation. Deciding on the most cost-effective restoration strategy Diverse restoration strategies should be promoted, and planting is often only one of several possible activities (see Box 4.1). In many cases, the restoration of forests and other degraded lands in drylands requires a combination of protection and management actions. Protection measures may

RANK 2 | SRC03_P0085_C004 | SRC03 | Page 85 | Distance 0.7065
The involved organizations and partners are identified, along with the nature of their contributions Area description Users characterize the restoration area according to five criteria: 1. climatic conditions, such as rainfall and temperature, wind, extreme weather events and climate-change impacts; 2. geomorphological and pedological properties, such as topography, altitude, hydrographic features and soil types; 3. ecological features, such as faunal and floral species, biotic interactions, and vegetation structure and cover; 4. socioeconomic properties, such as land use, land rights (e.g. ow

RANK 3 | SRC03_P0128_C001 | SRC03 | Page 128 | Distance 0.7204
Global guidelines for the restoration of degraded forests and landscapes in drylands 106 recovery were low water availability (370 mm annual precipitation, 20 percent of which occurs in summer), high summer temperatures, light soils (loamy-sandy texture), and steep slopes (40–60 percent). Approach The satisfactory restoration of degraded ecosystems in semi-arid conditions requires cost-effective techniques with the following features: • sustained increase in soil water available to plants; • minimum labour investment during installation/application and maintenance; • applicability in remote, p

====================================================================================================
QUERY: How can crop diversification, intercropping, or agroforestry improve biodiversity in monoculture farming?
====================================================================================================

RANK 1 | SRC02_P0080_C010 | SRC02 | Page 80 | Distance 0.4292
Diversification to promote sustainable intensification There are many ways in which increasing the diversity of the biological components within production systems can contribute to sustainable intensification. This may involve specific practices (e.g. intercropping), as well as broader integrated approaches such as agroecology (see Section 5.3). Diversification may involve utilizing a wider range of species, varieties or breeds from within a given sector (crops, livestock, forest, aquaculture, etc.), promoting positive interactions or complementar- ities between species from different sectors

RANK 2 | SRC05_P0001_C003 | SRC05 | Page 1 | Distance 0.4358
Most often, diversification practices resulted in win-win support of services and crop yields. Variability in responses and occurrence of trade-offs highlight the context dependency of outcomes. Widespread adoption of diversification practices shows promise to contribute to biodiversity conservation and food security from local to global scales. INTRODUCTION Agricultural expansion and intensification are considered major drivers of habitat and biodiversity loss, soil and freshwater degradation, environmental pollution, and greenhouse gas emissions worldwide (1, 2). Implementation of a new crop

RANK 3 | SRC05_P0004_C008 | SRC05 | Page 4 | Distance 0.4552
Large areas of cropland with monocultures in vast crop fields, such as in Australia, and North and South America (3), could benefit by the implementation of longer crop rotations, intercropping, and higher noncrop species diversity that enhance aboveground bio- diversity and the provisioning of regulating services, such as pollina- tion, pest control, and water regulation. Belowground biodiversity and services associated with soil quality are mainly supported by organic amendment and reduced tillage. Further, our results indicate that combining diversification practices is potentially advantag

### Multi-Query Retrieval

Complex user questions may contain several environmental factors whose relevant
evidence occurs in different scientific sources. A single query embedding can
underrepresent some of these factors.

The retriever therefore decomposes complex questions into focused evidence
queries covering soil organic carbon, rainfall/climate constraints, land-use
management, and biodiversity where applicable. Results are merged and
deduplicated using their stable chunk IDs.

In [67]:
def decompose_query(question):
    q = question.lower()

    queries = {
        "original": question
    }

    if any(term in q for term in [
        "soil carbon",
        "soil organic carbon",
        "soc"
    ]):
        queries["soc"] = (
            "How does soil organic carbon affect soil biodiversity "
            "and soil health?"
        )

    if any(term in q for term in [
        "rainfall",
        "semi-arid",
        "semi arid",
        "dryland",
        "drought"
    ]):
        queries["rainfall"] = (
            "How do rainfall and water availability affect "
            "restoration and vegetation establishment?"
        )

    if any(term in q for term in [
        "monoculture",
        "wheat",
        "corn",
        "maize",
        "agroforestry"
    ]):
        queries["land_use"] = (
            "How do agricultural land-use diversification, "
            "intercropping and agroforestry affect biodiversity?"
        )

    if any(term in q for term in [
        "biodiversity",
        "species",
        "species count",
        "species diversity"
    ]):
        queries["biodiversity"] = (
            "What agricultural management practices support "
            "biodiversity and ecosystem health?"
        )

    return queries

In [63]:
for case_id in ["GC01", "GC04", "GC07"]:

    question = scientific_eval_df.loc[
        scientific_eval_df["case_id"] == case_id,
        "question"
    ].iloc[0]

    print("\n", case_id)

    for query in decompose_query(question):
        print(" -", query)

 GC01
 - A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?
 - How does soil organic carbon affect soil biodiversity and soil health?
 - How do rainfall and water availability affect restoration and vegetation establishment?
 - How do agricultural land-use diversification, intercropping and agroforestry affect biodiversity?
 - What agricultural management practices support biodiversity and ecosystem health?

 GC04
 - We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?
 - How does soil organic carbon affect soil biodiversity and soil health?
 - How do rainfall and water availability affect restoration and vegetation establishment?
 - How do agricultural land-use diversification, intercropping and agroforestry affect biodiversity?

 GC07
 - Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health?
 - How does soil organic carbon affect soil biodiversity and soil health?
 - How do rainfall and water availability affect restoration and vegetation establishment?
 - How do agricultural land-use diversification, intercropping and agroforestry affect biodiversity?
 - What agricultural management practices support biodiversity and ecosystem health?

In [64]:
def retrieve_multi_query(question, top_k=3, per_query_k=5, rrf_k=60):

    queries = decompose_query(question)

    fused = {}

    for query in queries:

        results = retrieve(query, top_k=per_query_k)

        for rank, result in enumerate(results, start=1):

            chunk_id = result["chunk_id"]

            # Reciprocal Rank Fusion score
            score = 1 / (rrf_k + rank)

            if chunk_id not in fused:
                fused[chunk_id] = {
                    "chunk_id": chunk_id,
                    "text": result["text"],
                    "metadata": result["metadata"],
                    "rrf_score": 0.0,
                    "best_distance": result["distance"],
                    "matched_queries": []
                }

            fused[chunk_id]["rrf_score"] += score

            fused[chunk_id]["best_distance"] = min(
                fused[chunk_id]["best_distance"],
                result["distance"]
            )

            fused[chunk_id]["matched_queries"].append(query)

    ranked_results = sorted(
        fused.values(),
        key=lambda x: (
            -x["rrf_score"],
            x["best_distance"]
        )
    )

    return ranked_results[:top_k]

In [66]:
gc07_question = scientific_eval_df.loc[
    scientific_eval_df["case_id"] == "GC07",
    "question"
].iloc[0]

results = retrieve_multi_query(
    gc07_question,
    top_k=3
)

for rank, result in enumerate(results, start=1):

    print("\n" + "=" * 80)
    print(f"RESULT {rank}")
    print("=" * 80)

    print("Chunk ID:", result["chunk_id"])
    print("Source:", result["metadata"]["source_id"])
    print("Page:", result["metadata"]["page_number"])
    print("RRF Score:", round(result["rrf_score"], 6))
    print("Best Distance:", round(result["best_distance"], 4))
    print("Matched Queries:", len(result["matched_queries"]))

    print("\nText:")
    print(result["text"])

================================================================================
RESULT 1
================================================================================
Chunk ID: SRC01_P0236_C003
Source: SRC01
Page: 236
RRF Score: 0.016393
Best Distance: 0.4176
Matched Queries: 1

Text:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

================================================================================
RESULT 2
================================================================================
Chunk ID: SRC05_P0001_C008
Source: SRC05
Page: 1
RRF Score: 0.016393
Best Distance: 0.4716
Matched Queries: 1

Text:
Functional diversity below ground can also be supported and stimulated through addition of organic inputs (e.g., manure and crop residues) or reducing soil disturbance (e.g., reduced tillage), which lead to soil stratification and thereby more niches (8, 9). Despite a rapidly growing body of research assessing the impacts of agricul- tural diversification practices on biodiversity and related ecosystem services (7, 10–12), there is no comprehensive quantitative synthesis of this information. Consequently, we lack the broader understand- ing of whether diversification practices are actually capable of supporting biodiversity and multiple ecosystem services, including crop yields. We investigated the impact of multiple agricultural diversifica- tion practices on biodiversity and related ecosystem services and compared these with cropping systems with less diverse farming practices typical of mainstream agriculture. First, we systematically reviewed published meta-analyses and summarized the number of reported effect sizes (vote count) to assess the current state of knowledge, identify research gaps, and explore general patterns.

================================================================================
RESULT 3
================================================================================
Chunk ID: SRC02_P0492_C004
Source: SRC02
Page: 492
RRF Score: 0.016393
Best Distance: 0.4833
Matched Queries: 1

Text:
This appears to be the case, for example, for organic agriculture, low external input agriculture, man- agement practices implemented with the aim of preserving and enhancing soil biodiversity, conservation agriculture, integrated plant nutri- ent management, integrated pest management, pollination management and sustainable forest management practices. Nevertheless, the avail- ability of global data on the levels of imple- mentation of many of these practices remains limited, and knowledge of their impacts on BFA and the supply of ecosystem services needs to be improved. Biodiversity-based and biodiversity-friendly management practices generally require detailed knowledge of local production systems and eco- systems and are often relatively labour inten- sive. Consequently, their implementation tends to require the active participation of producers and their organizations, as well as the presence of effective extension services. Management interventions often need to extend beyond farm boundaries into the broader landscape or sea- scape. Attention needs to be paid to maintaining or restoring ecosystems that deliver services to food and agriculture and conserving the species and genetic diversity that will allow adaptation to changing conditions.

In [68]:
def retrieve_coverage_aware(question, top_k=3, per_aspect_k=3):
    queries = decompose_query(question)

    # We prefer specific evidence aspects over the original broad query
    aspect_priority = [
        "soc",
        "rainfall",
        "land_use",
        "biodiversity"
    ]

    selected = []
    selected_ids = set()

    # STEP 1:
    # Select the best unique result from each relevant aspect
    for aspect in aspect_priority:

        if aspect not in queries:
            continue

        results = retrieve(
            queries[aspect],
            top_k=per_aspect_k
        )

        for result in results:

            if result["chunk_id"] not in selected_ids:

                selected.append({
                    **result,
                    "retrieval_aspect": aspect
                })

                selected_ids.add(result["chunk_id"])
                break

        if len(selected) == top_k:
            return selected

    # STEP 2:
    # If fewer than top_k results were found,
    # use the original question to fill remaining slots
    if len(selected) < top_k:

        original_results = retrieve(
            queries["original"],
            top_k=per_aspect_k
        )

        for result in original_results:

            if result["chunk_id"] not in selected_ids:

                selected.append({
                    **result,
                    "retrieval_aspect": "original"
                })

                selected_ids.add(result["chunk_id"])

            if len(selected) == top_k:
                break

    return selected

In [69]:
gc07_question = scientific_eval_df.loc[
    scientific_eval_df["case_id"] == "GC07",
    "question"
].iloc[0]

results = retrieve_coverage_aware(
    gc07_question,
    top_k=3
)

for rank, result in enumerate(results, start=1):

    print("\n" + "=" * 80)
    print(f"RESULT {rank}")
    print("=" * 80)

    print("Aspect:", result["retrieval_aspect"])
    print("Chunk ID:", result["chunk_id"])
    print("Source:", result["metadata"]["source_id"])
    print("Page:", result["metadata"]["page_number"])
    print("Distance:", round(result["distance"], 4))

    print("\nText:")
    print(result["text"])

================================================================================
RESULT 1
================================================================================
Aspect: soc
Chunk ID: SRC01_P0236_C003
Source: SRC01
Page: 236
Distance: 0.4176

Text:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

================================================================================
RESULT 2
================================================================================
Aspect: rainfall
Chunk ID: SRC03_P0144_C001
Source: SRC03
Page: 144
Distance: 0.669

Text:
Global guidelines for the restoration of degraded forests and landscapes in drylands 122 Drought (UNCCD) A naturally occurring phenomenon that exists when precipitation has been significantly below normal recorded levels, causing serious hydrological imbalances that adversely affect land resource production systems Drylands (MEA) Areas with an aridity index value of less than 0.65 – that is, areas in which annual mean potential evapotranspiration is at least 1.5 times greater than annual mean precipitation Ecological restoration (Society for Ecological Restoration) The process of assisting the recovery of an ecosystem that has been degraded, damaged or destroyed Enabling environment (FAO, 2010a) The context in which individuals and organizations put their capabilities into action and where capacity development processes take place.

================================================================================
RESULT 3
================================================================================
Aspect: land_use
Chunk ID: SRC05_P0001_C008
Source: SRC05
Page: 1
Distance: 0.4716

Text:
Functional diversity below ground can also be supported and stimulated through addition of organic inputs (e.g., manure and crop residues) or reducing soil disturbance (e.g., reduced tillage), which lead to soil stratification and thereby more niches (8, 9). Despite a rapidly growing body of research assessing the impacts of agricul- tural diversification practices on biodiversity and related ecosystem services (7, 10–12), there is no comprehensive quantitative synthesis of this information. Consequently, we lack the broader understand- ing of whether diversification practices are actually capable of supporting biodiversity and multiple ecosystem services, including crop yields. We investigated the impact of multiple agricultural diversifica- tion practices on biodiversity and related ecosystem services and compared these with cropping systems with less diverse farming practices typical of mainstream agriculture. First, we systematically reviewed published meta-analyses and summarized the number of reported effect sizes (vote count) to assess the current state of knowledge, identify research gaps, and explore general patterns.

In [70]:
coverage_results = []

for _, row in scientific_eval_df.iterrows():

    results = retrieve_coverage_aware(
        row["question"],
        top_k=3
    )

    for rank, result in enumerate(results, start=1):

        coverage_results.append({
            "case_id": row["case_id"],
            "question": row["question"],
            "required_knowledge": row["required_knowledge"],
            "rank": rank,
            "aspect": result["retrieval_aspect"],
            "chunk_id": result["chunk_id"],
            "source_id": result["metadata"]["source_id"],
            "page_number": result["metadata"]["page_number"],
            "distance": result["distance"],
            "text": result["text"]
        })

coverage_results_df = pd.DataFrame(coverage_results)

print(
    "Golden cases tested:",
    coverage_results_df["case_id"].nunique()
)

print(
    "Total retrieved chunks:",
    len(coverage_results_df)
)

Golden cases tested: 7
Total retrieved chunks: 21

In [71]:
for case_id in scientific_eval_df["case_id"]:

    case_results = coverage_results_df[
        coverage_results_df["case_id"] == case_id
    ]

    print("\n" + "=" * 100)
    print(case_id)
    print("=" * 100)

    print("\nQUESTION:")
    print(case_results.iloc[0]["question"])

    print("\nREQUIRED KNOWLEDGE:")
    print(case_results.iloc[0]["required_knowledge"])

    for _, result in case_results.iterrows():

        print("\n" + "-" * 80)

        print(
            f'RANK {result["rank"]} | '
            f'Aspect: {result["aspect"]} | '
            f'{result["chunk_id"]} | '
            f'{result["source_id"]} | '
            f'Page {result["page_number"]} | '
            f'Distance {result["distance"]:.4f}'
        )

        print("\nTEXT:")
        print(result["text"])

====================================================================================================
GC01
====================================================================================================

QUESTION:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?

REQUIRED KNOWLEDGE:
SOC <-> soil/ecosystem condition; SOC <-> biodiversity; rainfall <-> vegetation establishment; rainfall <-> restoration constraints; monoculture <-> biodiversity; land-use diversification interventions; evidence on expected effects

--------------------------------------------------------------------------------
RANK 1 | Aspect: soc | SRC01_P0236_C003 | SRC01 | Page 236 | Distance 0.4176

TEXT:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

--------------------------------------------------------------------------------
RANK 2 | Aspect: rainfall | SRC03_P0144_C001 | SRC03 | Page 144 | Distance 0.6690

TEXT:
Global guidelines for the restoration of degraded forests and landscapes in drylands 122 Drought (UNCCD) A naturally occurring phenomenon that exists when precipitation has been significantly below normal recorded levels, causing serious hydrological imbalances that adversely affect land resource production systems Drylands (MEA) Areas with an aridity index value of less than 0.65 – that is, areas in which annual mean potential evapotranspiration is at least 1.5 times greater than annual mean precipitation Ecological restoration (Society for Ecological Restoration) The process of assisting the recovery of an ecosystem that has been degraded, damaged or destroyed Enabling environment (FAO, 2010a) The context in which individuals and organizations put their capabilities into action and where capacity development processes take place.

--------------------------------------------------------------------------------
RANK 3 | Aspect: land_use | SRC05_P0001_C008 | SRC05 | Page 1 | Distance 0.4716

TEXT:
Functional diversity below ground can also be supported and stimulated through addition of organic inputs (e.g., manure and crop residues) or reducing soil disturbance (e.g., reduced tillage), which lead to soil stratification and thereby more niches (8, 9). Despite a rapidly growing body of research assessing the impacts of agricul- tural diversification practices on biodiversity and related ecosystem services (7, 10–12), there is no comprehensive quantitative synthesis of this information. Consequently, we lack the broader understand- ing of whether diversification practices are actually capable of supporting biodiversity and multiple ecosystem services, including crop yields. We investigated the impact of multiple agricultural diversifica- tion practices on biodiversity and related ecosystem services and compared these with cropping systems with less diverse farming practices typical of mainstream agriculture. First, we systematically reviewed published meta-analyses and summarized the number of reported effect sizes (vote count) to assess the current state of knowledge, identify research gaps, and explore general patterns.

====================================================================================================
GC02
====================================================================================================

QUESTION:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do?

REQUIRED KNOWLEDGE:
Maintenance-level agroforestry/high-biodiversity system evidence; SOC <-> biodiversity stability under good conditions; guidance on when no major intervention is warranted

--------------------------------------------------------------------------------
RANK 1 | Aspect: soc | SRC01_P0236_C003 | SRC01 | Page 236 | Distance 0.4176

TEXT:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

--------------------------------------------------------------------------------
RANK 2 | Aspect: rainfall | SRC03_P0144_C001 | SRC03 | Page 144 | Distance 0.6690

TEXT:
Global guidelines for the restoration of degraded forests and landscapes in drylands 122 Drought (UNCCD) A naturally occurring phenomenon that exists when precipitation has been significantly below normal recorded levels, causing serious hydrological imbalances that adversely affect land resource production systems Drylands (MEA) Areas with an aridity index value of less than 0.65 – that is, areas in which annual mean potential evapotranspiration is at least 1.5 times greater than annual mean precipitation Ecological restoration (Society for Ecological Restoration) The process of assisting the recovery of an ecosystem that has been degraded, damaged or destroyed Enabling environment (FAO, 2010a) The context in which individuals and organizations put their capabilities into action and where capacity development processes take place.

--------------------------------------------------------------------------------
RANK 3 | Aspect: land_use | SRC05_P0001_C008 | SRC05 | Page 1 | Distance 0.4716

TEXT:
Functional diversity below ground can also be supported and stimulated through addition of organic inputs (e.g., manure and crop residues) or reducing soil disturbance (e.g., reduced tillage), which lead to soil stratification and thereby more niches (8, 9). Despite a rapidly growing body of research assessing the impacts of agricul- tural diversification practices on biodiversity and related ecosystem services (7, 10–12), there is no comprehensive quantitative synthesis of this information. Consequently, we lack the broader understand- ing of whether diversification practices are actually capable of supporting biodiversity and multiple ecosystem services, including crop yields. We investigated the impact of multiple agricultural diversifica- tion practices on biodiversity and related ecosystem services and compared these with cropping systems with less diverse farming practices typical of mainstream agriculture. First, we systematically reviewed published meta-analyses and summarized the number of reported effect sizes (vote count) to assess the current state of knowledge, identify research gaps, and explore general patterns.

====================================================================================================
GC03
====================================================================================================

QUESTION:
Biodiversity is declining on my land. Soil organic carbon is 0.4%.

REQUIRED KNOWLEDGE:
SOC <-> biodiversity decline indicators; what rainfall data is needed and why; what land-use data is needed and why; clarifying-question triggers for missing variables

--------------------------------------------------------------------------------
RANK 1 | Aspect: soc | SRC01_P0236_C003 | SRC01 | Page 236 | Distance 0.4176

TEXT:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

--------------------------------------------------------------------------------
RANK 2 | Aspect: biodiversity | SRC02_P0492_C004 | SRC02 | Page 492 | Distance 0.4833

TEXT:
This appears to be the case, for example, for organic agriculture, low external input agriculture, man- agement practices implemented with the aim of preserving and enhancing soil biodiversity, conservation agriculture, integrated plant nutri- ent management, integrated pest management, pollination management and sustainable forest management practices. Nevertheless, the avail- ability of global data on the levels of imple- mentation of many of these practices remains limited, and knowledge of their impacts on BFA and the supply of ecosystem services needs to be improved. Biodiversity-based and biodiversity-friendly management practices generally require detailed knowledge of local production systems and eco- systems and are often relatively labour inten- sive. Consequently, their implementation tends to require the active participation of producers and their organizations, as well as the presence of effective extension services. Management interventions often need to extend beyond farm boundaries into the broader landscape or sea- scape. Attention needs to be paid to maintaining or restoring ecosystems that deliver services to food and agriculture and conserving the species and genetic diversity that will allow adaptation to changing conditions.

--------------------------------------------------------------------------------
RANK 3 | Aspect: original | SRC01_P0324_C001 | SRC01 | Page 324 | Distance 0.5092

TEXT:
State of knowledge of soil biodiversity 294 5.4.3 | SOIL BIODIVERSITY AS A FARMER’S TOOL The adoption of soil conservation practices such as reduced tillage, improved residue management, reduced bare fallow and conservation reserve plantings have stabilized, and partially reversed, soil organic carbon (SOC) loss in North American agricultural soils (Paustian et al., 2016). Improved grazing management, fertilization, and sowing legumes and improved grass species are additional ways to increase soil C by as much as 1 Mg C/ ha/yr in best cases (Conant et al., 2016). Restoration of late-successional grassland plant diversity leads to accelerating annual carbon storage rates on degraded and abandoned agricultural lands that, by the second period (years 13 to 22), are 200 percent greater in the highest diversity treatment than during succession at this site, and 70 percent greater than in monocultures.

====================================================================================================
GC04
====================================================================================================

QUESTION:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?

REQUIRED KNOWLEDGE:
SOC <-> monoculture interaction effects; how adequate rainfall changes which interventions are viable (non-limiting case); why a biodiversity indicator is needed for a complete recommendation

--------------------------------------------------------------------------------
RANK 1 | Aspect: soc | SRC01_P0236_C003 | SRC01 | Page 236 | Distance 0.4176

TEXT:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

--------------------------------------------------------------------------------
RANK 2 | Aspect: rainfall | SRC03_P0144_C001 | SRC03 | Page 144 | Distance 0.6690

TEXT:
Global guidelines for the restoration of degraded forests and landscapes in drylands 122 Drought (UNCCD) A naturally occurring phenomenon that exists when precipitation has been significantly below normal recorded levels, causing serious hydrological imbalances that adversely affect land resource production systems Drylands (MEA) Areas with an aridity index value of less than 0.65 – that is, areas in which annual mean potential evapotranspiration is at least 1.5 times greater than annual mean precipitation Ecological restoration (Society for Ecological Restoration) The process of assisting the recovery of an ecosystem that has been degraded, damaged or destroyed Enabling environment (FAO, 2010a) The context in which individuals and organizations put their capabilities into action and where capacity development processes take place.

--------------------------------------------------------------------------------
RANK 3 | Aspect: land_use | SRC05_P0001_C008 | SRC05 | Page 1 | Distance 0.4716

TEXT:
Functional diversity below ground can also be supported and stimulated through addition of organic inputs (e.g., manure and crop residues) or reducing soil disturbance (e.g., reduced tillage), which lead to soil stratification and thereby more niches (8, 9). Despite a rapidly growing body of research assessing the impacts of agricul- tural diversification practices on biodiversity and related ecosystem services (7, 10–12), there is no comprehensive quantitative synthesis of this information. Consequently, we lack the broader understand- ing of whether diversification practices are actually capable of supporting biodiversity and multiple ecosystem services, including crop yields. We investigated the impact of multiple agricultural diversifica- tion practices on biodiversity and related ecosystem services and compared these with cropping systems with less diverse farming practices typical of mainstream agriculture. First, we systematically reviewed published meta-analyses and summarized the number of reported effect sizes (vote count) to assess the current state of knowledge, identify research gaps, and explore general patterns.

====================================================================================================
GC05
====================================================================================================

QUESTION:
What can I do to improve biodiversity on this farm? It's wheat monoculture.

REQUIRED KNOWLEDGE:
General monoculture <-> biodiversity evidence usable as context; the minimum variable set required before a specific recommendation can be made; clarifying-question triggers

--------------------------------------------------------------------------------
RANK 1 | Aspect: land_use | SRC05_P0001_C008 | SRC05 | Page 1 | Distance 0.4716

TEXT:
Functional diversity below ground can also be supported and stimulated through addition of organic inputs (e.g., manure and crop residues) or reducing soil disturbance (e.g., reduced tillage), which lead to soil stratification and thereby more niches (8, 9). Despite a rapidly growing body of research assessing the impacts of agricul- tural diversification practices on biodiversity and related ecosystem services (7, 10–12), there is no comprehensive quantitative synthesis of this information. Consequently, we lack the broader understand- ing of whether diversification practices are actually capable of supporting biodiversity and multiple ecosystem services, including crop yields. We investigated the impact of multiple agricultural diversifica- tion practices on biodiversity and related ecosystem services and compared these with cropping systems with less diverse farming practices typical of mainstream agriculture. First, we systematically reviewed published meta-analyses and summarized the number of reported effect sizes (vote count) to assess the current state of knowledge, identify research gaps, and explore general patterns.

--------------------------------------------------------------------------------
RANK 2 | Aspect: biodiversity | SRC02_P0492_C004 | SRC02 | Page 492 | Distance 0.4833

TEXT:
This appears to be the case, for example, for organic agriculture, low external input agriculture, man- agement practices implemented with the aim of preserving and enhancing soil biodiversity, conservation agriculture, integrated plant nutri- ent management, integrated pest management, pollination management and sustainable forest management practices. Nevertheless, the avail- ability of global data on the levels of imple- mentation of many of these practices remains limited, and knowledge of their impacts on BFA and the supply of ecosystem services needs to be improved. Biodiversity-based and biodiversity-friendly management practices generally require detailed knowledge of local production systems and eco- systems and are often relatively labour inten- sive. Consequently, their implementation tends to require the active participation of producers and their organizations, as well as the presence of effective extension services. Management interventions often need to extend beyond farm boundaries into the broader landscape or sea- scape. Attention needs to be paid to maintaining or restoring ecosystems that deliver services to food and agriculture and conserving the species and genetic diversity that will allow adaptation to changing conditions.

--------------------------------------------------------------------------------

### Additional Retrieval Noise Analysis

Inspect structural PDF content that may harm semantic retrieval,
including bibliography entries, questionnaire material, contents fragments,
and other non-evidence text.

In [2]:
import pandas as pd

corpus_df = pd.read_csv(
    "../data/processed/scientific_corpus_pages.csv"
)

print("Corpus loaded:", corpus_df.shape)

Corpus loaded: (1377, 4)

In [3]:
import pandas as pd
import re
from sentence_transformers import SentenceTransformer

# ============================================================
# 1. LOAD CORPUS
# ============================================================

corpus_df = pd.read_csv(
    "../data/processed/scientific_corpus_pages.csv"
)

corpus_df["text"] = corpus_df["text"].fillna("").astype(str)

print("Corpus pages loaded:", len(corpus_df))


# ============================================================
# 2. LOAD MINILM TOKENIZER
# ============================================================

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
tokenizer = embedding_model.tokenizer

MAX_CHUNK_TOKENS = 220


# ============================================================
# 3. SENTENCE SPLITTER
# ============================================================

def split_sentences(text):

    text = re.sub(r"\s+", " ", text).strip()

    if not text:
        return []

    sentences = re.split(
        r'(?<=[.!?])\s+(?=[A-Z0-9])',
        text
    )

    return [s.strip() for s in sentences if s.strip()]


# ============================================================
# 4. TOKEN COUNT
# ============================================================

def count_tokens(text):

    return len(
        tokenizer.encode(
            text,
            add_special_tokens=True,
            truncation=False
        )
    )


# ============================================================
# 5. TOKEN-SAFE CHUNKING
# ============================================================

def create_chunks(text, max_tokens=MAX_CHUNK_TOKENS):

    sentences = split_sentences(text)

    if not sentences:
        return []

    chunks = []
    current = []

    for sentence in sentences:

        candidate = " ".join(current + [sentence])

        # Sentence fits into current chunk
        if count_tokens(candidate) <= max_tokens:
            current.append(sentence)
            continue

        # Save current chunk
        if current:
            chunks.append(" ".join(current))

        # Sentence itself is too large
        if count_tokens(sentence) > max_tokens:

            words = sentence.split()
            temp = []

            for word in words:

                candidate = " ".join(temp + [word])

                if count_tokens(candidate) <= max_tokens:
                    temp.append(word)

                else:
                    if temp:
                        chunks.append(" ".join(temp))

                    temp = [word]

            current = temp

        else:
            current = [sentence]

    if current:
        chunks.append(" ".join(current))

    return chunks


# ============================================================
# 6. CREATE CHUNK DATAFRAME
# ============================================================

records = []

for _, row in corpus_df.iterrows():

    text = row["text"].strip()

    if not text:
        continue

    page_chunks = create_chunks(text)

    for chunk_index, chunk_text in enumerate(
        page_chunks,
        start=1
    ):

        chunk_id = (
            f'{row["source_id"]}'
            f'_P{int(row["page_number"]):04d}'
            f'_C{chunk_index:03d}'
        )

        records.append({
            "chunk_id": chunk_id,
            "source_id": row["source_id"],
            "filename": row["filename"],
            "page_number": int(row["page_number"]),
            "chunk_index": chunk_index,
            "text": chunk_text
        })


chunks_df = pd.DataFrame(records)


# ============================================================
# 7. TOKEN COUNTS
# ============================================================

chunks_df["token_count"] = chunks_df["text"].apply(
    count_tokens
)


# ============================================================
# 8. REMOVE VERY SHORT / OBVIOUS NON-CONTENT CHUNKS
# ============================================================

chunks_df = chunks_df[
    chunks_df["token_count"] >= 20
].copy()

chunks_df.reset_index(drop=True, inplace=True)


# ============================================================
# 9. VALIDATION
# ============================================================

print("\nFINAL CHUNK CORPUS")
print("------------------")

print("Total chunks:", len(chunks_df))
print("Sources:", chunks_df["source_id"].nunique())
print(
    "Duplicate IDs:",
    chunks_df["chunk_id"].duplicated().sum()
)
print(
    "Missing text:",
    chunks_df["text"].isnull().sum()
)
print(
    "Empty text:",
    (chunks_df["text"].str.strip() == "").sum()
)
print(
    "Maximum tokens:",
    chunks_df["token_count"].max()
)
print(
    "Chunks exceeding MiniLM limit:",
    (chunks_df["token_count"] > 256).sum()
)

Corpus pages loaded: 1377

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (305 > 256). Running this sequence through the model will result in indexing errors

FINAL CHUNK CORPUS
------------------
Total chunks: 5204
Sources: 5
Duplicate IDs: 0
Missing text: 0
Empty text: 0
Maximum tokens: 220
Chunks exceeding MiniLM limit: 0

In [5]:
# 1. Load corpus
import pandas as pd
import re

corpus_path = "../data/processed/scientific_corpus_pages.csv"
corpus_df = pd.read_csv(corpus_path)

print("Corpus:", corpus_df.shape)

Corpus: (1377, 4)

In [6]:
# 2. Create retrieval dataframe
retrieval_df = corpus_df.copy()

retrieval_df = retrieval_df.dropna(subset=["text"])
retrieval_df["text"] = retrieval_df["text"].astype(str).str.strip()
retrieval_df = retrieval_df[retrieval_df["text"] != ""].copy()
retrieval_df.reset_index(drop=True, inplace=True)

print("Retrieval pages:", len(retrieval_df))

Retrieval pages: 1352

In [7]:
# 3. Clean extracted text
def clean_text(text):
    text = re.sub(r"\s+", " ", text)
    return text.strip()

retrieval_df["clean_text"] = retrieval_df["text"].apply(clean_text)

print(retrieval_df.columns.tolist())

['source_id', 'filename', 'page_number', 'text', 'clean_text']

In [8]:
import re
import pandas as pd


# ============================================================
# 1. SENTENCE SPLITTING
# ============================================================

def split_into_sentences(text):
    sentences = re.split(
        r'(?<=[.!?])\s+(?=[A-Z0-9])',
        text
    )

    return [
        sentence.strip()
        for sentence in sentences
        if sentence.strip()
    ]


# ============================================================
# 2. TOKEN-AWARE CHUNKING
# ============================================================

def create_token_aware_chunks(
    text,
    tokenizer,
    target_tokens=220,
    overlap_sentences=2
):
    sentences = split_into_sentences(text)

    if not sentences:
        return []

    def token_count(value):
        return len(
            tokenizer(
                value,
                add_special_tokens=True,
                truncation=False
            )["input_ids"]
        )

    expanded_sentences = []

    for sentence in sentences:

        if token_count(sentence) <= target_tokens:
            expanded_sentences.append(sentence)
            continue

        token_ids = tokenizer(
            sentence,
            add_special_tokens=False,
            truncation=False
        )["input_ids"]

        safe_size = target_tokens - 2

        for start in range(0, len(token_ids), safe_size):

            token_piece = token_ids[start:start + safe_size]

            piece = tokenizer.decode(
                token_piece,
                skip_special_tokens=True
            ).strip()

            if piece:
                expanded_sentences.append(piece)

    chunks = []
    current_sentences = []

    for sentence in expanded_sentences:

        candidate = " ".join(
            current_sentences + [sentence]
        ).strip()

        if (
            not current_sentences
            or token_count(candidate) <= target_tokens
        ):
            current_sentences.append(sentence)

        else:
            chunk = " ".join(current_sentences).strip()

            if chunk:
                chunks.append(chunk)

            overlap = (
                current_sentences[-overlap_sentences:]
                if overlap_sentences > 0
                else []
            )

            while overlap:
                candidate = " ".join(
                    overlap + [sentence]
                ).strip()

                if token_count(candidate) <= target_tokens:
                    break

                overlap = overlap[1:]

            current_sentences = overlap + [sentence]

    if current_sentences:
        final_chunk = " ".join(current_sentences).strip()

        if final_chunk:
            chunks.append(final_chunk)

    return chunks


# ============================================================
# 3. CREATE CHUNKS
# ============================================================

all_chunks = []

for _, row in retrieval_df.iterrows():

    page_chunks = create_token_aware_chunks(
        row["clean_text"],
        tokenizer,
        target_tokens=220,
        overlap_sentences=2
    )

    for chunk_index, chunk in enumerate(page_chunks, start=1):

        chunk_id = (
            f'{row["source_id"]}_'
            f'P{int(row["page_number"]):04d}_'
            f'C{chunk_index:03d}'
        )

        all_chunks.append({
            "chunk_id": chunk_id,
            "source_id": row["source_id"],
            "filename": row["filename"],
            "page_number": int(row["page_number"]),
            "chunk_index": chunk_index,
            "text": chunk
        })


chunks_df = pd.DataFrame(all_chunks)


# ============================================================
# 4. TOKEN COUNTS
# ============================================================

def count_tokens(text):
    return len(
        tokenizer.encode(
            text,
            add_special_tokens=True,
            truncation=False
        )
    )


chunks_df["token_count"] = chunks_df["text"].apply(
    count_tokens
)


# ============================================================
# 5. ORIGINAL CREDIT CLEANUP
# ============================================================

credit_mask = (
    chunks_df["text"].str.contains(
        r"^\s*©",
        regex=True,
        na=False
    )
    &
    (chunks_df["token_count"] < 20)
)

before_count = len(chunks_df)

chunks_df = chunks_df[~credit_mask].copy()
chunks_df.reset_index(drop=True, inplace=True)

after_count = len(chunks_df)


# ============================================================
# 6. VALIDATE
# ============================================================

print("Before credit cleanup:", before_count)
print("Credit chunks removed:", before_count - after_count)

print("\nFINAL CHUNK CORPUS")
print("------------------")
print("Total chunks:", len(chunks_df))
print("Sources:", chunks_df["source_id"].nunique())
print("Duplicate IDs:", chunks_df["chunk_id"].duplicated().sum())
print("Missing text:", chunks_df["text"].isnull().sum())
print("Empty text:", (chunks_df["text"].str.strip() == "").sum())
print("Maximum tokens:", chunks_df["token_count"].max())
print(
    "Chunks exceeding MiniLM limit:",
    (chunks_df["token_count"] > 256).sum()
)

Before credit cleanup: 6876
Credit chunks removed: 18

FINAL CHUNK CORPUS
------------------
Total chunks: 6858
Sources: 5
Duplicate IDs: 0
Missing text: 0
Empty text: 0
Maximum tokens: 223
Chunks exceeding MiniLM limit: 0

In [9]:
import re

def classify_noise(text):
    text = str(text).strip()
    lower = text.lower()

    flags = []

    # 1. Very short structural fragments
    if len(text.split()) < 8:
        flags.append("very_short")

    # 2. Explicit reference/bibliography headings
    if re.match(r"^(references|bibliography)\b", lower):
        flags.append("reference_heading")

    # 3. DOI-heavy text — often bibliography/reference material
    doi_count = len(
        re.findall(
            r"\bdoi\b|https?://doi\.org",
            lower
        )
    )

    if doi_count >= 2:
        flags.append("doi_heavy")

    # 4. Questionnaire / survey-like material
    survey_terms = [
        "questionnaire",
        "respondent",
        "please indicate",
        "please specify",
        "how do you perceive",
        "national survey"
    ]

    survey_matches = sum(
        term in lower
        for term in survey_terms
    )

    if survey_matches >= 2:
        flags.append("questionnaire")

    return flags


chunks_df["noise_flags"] = chunks_df["text"].apply(
    classify_noise
)

noise_candidates = chunks_df[
    chunks_df["noise_flags"].apply(len) > 0
].copy()

print("Total chunks:", len(chunks_df))
print("Potential noise chunks:", len(noise_candidates))

print("\nNoise type counts:")

all_flags = [
    flag
    for flags in noise_candidates["noise_flags"]
    for flag in flags
]

print(pd.Series(all_flags).value_counts())

display(
    noise_candidates[
        [
            "chunk_id",
            "source_id",
            "page_number",
            "token_count",
            "noise_flags",
            "text"
        ]
    ].head(30)
)

Total chunks: 6858
Potential noise chunks: 183

Noise type counts:
doi_heavy            96
reference_heading    76
very_short           15
questionnaire         4
Name: count, dtype: int64

,chunk_id,source_id,page_number,token_count,noise_flags,text
24,SRC01_P0012_C002,SRC01,12,11,[very_short],responded to the survey 445 references 447
66,SRC01_P0028_C004,SRC01,28,14,[very_short],##cados pncti | technology and innovation plan
1065,SRC01_P0280_C003,SRC01,280,5,[very_short],low low low
1510,SRC01_P0393_C006,SRC01,393,11,[very_short],##tkatalog _ node. html
1805,SRC01_P0465_C001,SRC01,465,3,[very_short],435
1810,SRC01_P0469_C001,SRC01,469,201,[questionnaire],National Survey on Status of Soil Biodiversity...
1814,SRC01_P0471_C001,SRC01,471,200,[questionnaire],National Survey on Status of Soil Biodiversity...
1819,SRC01_P0473_C001,SRC01,473,218,[questionnaire],National Survey on Status of Soil Biodiversity...
1821,SRC01_P0477_C001,SRC01,477,211,[reference_heading],"References 447 REFERENCES A’Bear A.D., Johnson..."
1823,SRC01_P0477_C003,SRC01,477,211,[doi_heavy],"Abinandan, S., Subashchandrabose, S.R., Venkat..."
1832,SRC01_P0479_C001,SRC01,479,195,[reference_heading],"References 449 Al-Karaki, G. 2006. Nursery ino..."
1836,SRC01_P0479_C005,SRC01,479,206,[doi_heavy],Zinc in Soils and Crop Nutrition. Internationa...
1843,SRC01_P0481_C001,SRC01,481,209,[reference_heading],"References 451 Armado, A., Contreras, F. Garcí..."
1855,SRC01_P0483_C001,SRC01,483,213,[reference_heading],"References 453 Baer, S. G., Bach, E.M., Meyer,..."
1857,SRC01_P0483_C003,SRC01,483,211,[doi_heavy],2010. Tradeoffs and thresholds in the effects ...
1866,SRC01_P0485_C001,SRC01,485,212,"[reference_heading, doi_heavy]","References 455 Barnard, J. 2000. Oregon’s mons..."
1867,SRC01_P0485_C002,SRC01,485,217,[doi_heavy],"Soil biota, ecosystem services and land produc..."
1877,SRC01_P0487_C001,SRC01,487,195,[reference_heading],"References 457 Behan-Pelletier, V. 1999. Oriba..."
1889,SRC01_P0489_C001,SRC01,489,177,[reference_heading],"References 459 Bhakta, J.N., Ohnishi, K., Mune..."
1890,SRC01_P0489_C002,SRC01,489,217,[doi_heavy],2015. Temperature-based bioclimatic parameters...
1895,SRC01_P0490_C001,SRC01,490,218,[doi_heavy],State of knowledge of soil biodiversity 460 Bi...
1901,SRC01_P0491_C001,SRC01,491,208,[reference_heading],"References 461 Blouin, M., Hodson, M.E., Delga..."
1912,SRC01_P0493_C001,SRC01,493,220,"[reference_heading, doi_heavy]","References 463 Bradáčová, K., Florea, A.S., Ba..."
1923,SRC01_P0495_C001,SRC01,495,216,[reference_heading],"References 465 Bryan, J.E., Shearman, P.L., As..."
1935,SRC01_P0497_C001,SRC01,497,218,[reference_heading],"References 467 Callaham, M.A., Jr., González, ..."
1944,SRC01_P0498_C005,SRC01,498,216,[doi_heavy],BioRxiv. https://doi.org/10.1101/402438 Carlos...
1946,SRC01_P0499_C001,SRC01,499,202,"[reference_heading, doi_heavy]","References 469 Carroll, J.J. & Viglierchio, D...."
1951,SRC01_P0499_C006,SRC01,499,220,[doi_heavy],2019. A case study of soil food web components...
1953,SRC01_P0500_C001,SRC01,500,219,[doi_heavy],State of knowledge of soil biodiversity 470 Ch...
1954,SRC01_P0500_C002,SRC01,500,186,[doi_heavy],2018. Cyanobacteria Inoculation Improves Soil ...

In [10]:
# ============================================================
# CREATE CLEAN RETRIEVAL CORPUS
# ============================================================

SAFE_NOISE_FLAGS = {
    "very_short",
    "reference_heading",
    "questionnaire"
}

def should_remove(flags):
    return any(
        flag in SAFE_NOISE_FLAGS
        for flag in flags
    )


remove_mask = chunks_df["noise_flags"].apply(
    should_remove
)

removed_chunks_df = chunks_df[
    remove_mask
].copy()

retrieval_chunks_df = chunks_df[
    ~remove_mask
].copy()

retrieval_chunks_df.reset_index(
    drop=True,
    inplace=True
)


print("Original chunks:", len(chunks_df))
print("Removed chunks:", len(removed_chunks_df))
print("Retrieval chunks:", len(retrieval_chunks_df))

print("\nRemoved by reason:")

removed_flags = [
    flag
    for flags in removed_chunks_df["noise_flags"]
    for flag in flags
    if flag in SAFE_NOISE_FLAGS
]

print(pd.Series(removed_flags).value_counts())

Original chunks: 6858
Removed chunks: 95
Retrieval chunks: 6763

Removed by reason:
reference_heading    76
very_short           15
questionnaire         4
Name: count, dtype: int64

In [16]:
def decompose_query(question):
    q = question.lower()

    queries = {
        "original": question
    }

    # ==================================================
    # SOC / SOIL HEALTH
    # ==================================================

    if any(term in q for term in [
        "soil carbon",
        "soil organic carbon",
        "soc"
    ]):

        if any(term in q for term in [
            "very low",
            "low soil carbon",
            "low soil organic carbon",
            "soc 0.3",
            "0.3%",
            "0.4%"
        ]):
            queries["soc"] = (
                f"{question} "
                "Effects of low soil organic carbon on soil health, "
                "soil biodiversity, soil organisms and ecosystem functioning."
            )

        elif any(term in q for term in [
            "good soil carbon",
            "high soil carbon"
        ]):
            queries["soc"] = (
                f"{question} "
                "Healthy soil organic carbon, soil biodiversity, "
                "soil ecosystem stability and maintenance."
            )

        else:
            queries["soc"] = (
                f"{question} "
                "Relationship between soil organic carbon, "
                "soil biodiversity and soil health."
            )

    # ==================================================
    # RAINFALL / WATER
    # ==================================================

    if any(term in q for term in [
        "rainfall",
        "semi-arid",
        "semi arid",
        "dryland",
        "drought"
    ]):

        if any(term in q for term in [
            "low rainfall",
            "semi-arid",
            "semi arid",
            "dryland",
            "drought"
        ]):
            queries["rainfall"] = (
                f"{question} "
                "Low rainfall semi-arid dryland restoration, "
                "water limitation, soil water availability "
                "and vegetation establishment."
            )

        elif (
    "high rainfall" in q
    or "rainfall is high" in q
    or "rainfall here is high" in q
        ):
            queries["rainfall"] = (
                f"{question} "
                "High rainfall non-water-limited agricultural "
                "soil restoration, vegetation and management practices."
          )

        elif any(term in q for term in [
            "decent rainfall",
            "adequate rainfall"
        ]):
            queries["rainfall"] = (
                f"{question} "
                "Adequate rainfall and water availability for "
                "agricultural soil restoration and vegetation establishment."
            )

        else:
            queries["rainfall"] = (
                f"{question} "
                "Rainfall, water availability and restoration."
            )

    # ==================================================
    # LAND USE
    # ==================================================

    if any(term in q for term in [
        "monoculture",
        "wheat",
        "corn",
        "maize",
        "agroforestry"
    ]):

        if "agroforestry" in q:
            queries["land_use"] = (
                f"{question} "
                "Existing agroforestry systems, biodiversity, "
                "soil health, ecosystem services and "
                "sustainable maintenance."
            )

        elif "wheat" in q:
            queries["land_use"] = (
                f"{question} "
                "Wheat monoculture, crop diversification, "
                "crop rotation, intercropping, agroforestry "
                "and biodiversity."
            )

        elif "corn" in q or "maize" in q:
            queries["land_use"] = (
                f"{question} "
                "Corn maize monoculture, crop diversification, "
                "cover crops, intercropping and soil biodiversity."
            )

        else:
            queries["land_use"] = (
                f"{question} "
                "Monoculture, agricultural diversification "
                "and biodiversity."
            )

    # ==================================================
    # BIODIVERSITY
    # ==================================================

    if any(term in q for term in [
        "biodiversity",
        "species",
        "species count",
        "species diversity"
    ]):

        if any(term in q for term in [
            "declining",
            "decline",
            "low species",
            "low species count"
        ]):
            queries["biodiversity"] = (
                f"{question} "
                "Declining or low biodiversity, causes of "
                "biodiversity loss and agricultural practices "
                "that restore biodiversity."
            )

        elif any(term in q for term in [
            "high species",
            "species counts are high",
            "diversity seems fine",
            "moderate",
            "stable"
        ]):
            queries["biodiversity"] = (
                f"{question} "
                "Maintaining existing agricultural biodiversity, "
                "ecosystem stability and sustainable management."
            )

        else:
            queries["biodiversity"] = (
                f"{question} "
                "Agricultural biodiversity, ecosystem health "
                "and biodiversity-friendly management."
            )

    return queries

In [14]:
for case_id in ["GC01", "GC02", "GC04", "GC06", "GC07"]:

    question = scientific_eval_df.loc[
        scientific_eval_df["case_id"] == case_id,
        "question"
    ].iloc[0]

    print("\n" + "=" * 80)
    print(case_id)
    print("=" * 80)

    queries = decompose_query(question)

    for aspect, query in queries.items():
        print(f"\n{aspect.upper()}:")
        print(query)

NameError: name 'scientific_eval_df' is not defined

In [17]:
test_cases = {
    "GC01": (
        "A farm has low soil organic carbon, low rainfall, "
        "monoculture wheat, and low species counts. "
        "What intervention could improve its condition?"
    ),

    "GC02": (
        "My land already has good soil carbon, decent rainfall, "
        "and agroforestry. Species counts are high. "
        "Is there anything more I should do?"
    ),

    "GC04": (
        "We get decent rainfall but our soil carbon is low "
        "and we grow only wheat. What should we do?"
    ),

    "GC06": (
        "Rainfall here is high, but soil carbon is very low "
        "and it's monoculture corn. Species diversity seems fine for now."
    ),

    "GC07": (
        "Semi-arid region, soil organic carbon 0.3%, rainfall is low, "
        "crop is monoculture wheat. "
        "What should I do to improve biodiversity and soil health?"
    )
}


for case_id, question in test_cases.items():

    print("\n" + "=" * 80)
    print(case_id)
    print("=" * 80)

    queries = decompose_query(question)

    for aspect, query in queries.items():
        print(f"\n{aspect.upper()}:")
        print(query)

================================================================================
GC01
================================================================================

ORIGINAL:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?

SOC:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition? Effects of low soil organic carbon on soil health, soil biodiversity, soil organisms and ecosystem functioning.

RAINFALL:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition? Low rainfall semi-arid dryland restoration, water limitation, soil water availability and vegetation establishment.

LAND_USE:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition? Wheat monoculture, crop diversification, crop rotation, intercropping, agroforestry and biodiversity.

BIODIVERSITY:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition? Declining or low biodiversity, causes of biodiversity loss and agricultural practices that restore biodiversity.

================================================================================
GC02
================================================================================

ORIGINAL:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do?

SOC:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do? Healthy soil organic carbon, soil biodiversity, soil ecosystem stability and maintenance.

RAINFALL:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do? Adequate rainfall and water availability for agricultural soil restoration and vegetation establishment.

LAND_USE:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do? Existing agroforestry systems, biodiversity, soil health, ecosystem services and sustainable maintenance.

BIODIVERSITY:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do? Maintaining existing agricultural biodiversity, ecosystem stability and sustainable management.

================================================================================
GC04
================================================================================

ORIGINAL:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?

SOC:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do? Relationship between soil organic carbon, soil biodiversity and soil health.

RAINFALL:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do? Adequate rainfall and water availability for agricultural soil restoration and vegetation establishment.

LAND_USE:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do? Wheat monoculture, crop diversification, crop rotation, intercropping, agroforestry and biodiversity.

================================================================================
GC06
================================================================================

ORIGINAL:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now.

SOC:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now. Effects of low soil organic carbon on soil health, soil biodiversity, soil organisms and ecosystem functioning.

RAINFALL:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now. High rainfall non-water-limited agricultural soil restoration, vegetation and management practices.

LAND_USE:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now. Corn maize monoculture, crop diversification, cover crops, intercropping and soil biodiversity.

BIODIVERSITY:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now. Maintaining existing agricultural biodiversity, ecosystem stability and sustainable management.

================================================================================
GC07
================================================================================

ORIGINAL:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health?

SOC:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health? Effects of low soil organic carbon on soil health, soil biodiversity, soil organisms and ecosystem functioning.

RAINFALL:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health? Low rainfall semi-arid dryland restoration, water limitation, soil water availability and vegetation establishment.

LAND_USE:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health? Wheat monoculture, crop diversification, crop rotation, intercropping, agroforestry and biodiversity.

BIODIVERSITY:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health? Agricultural biodiversity, ecosystem health and biodiversity-friendly management.

In [18]:
texts = retrieval_chunks_df["text"].tolist()

print("Chunks to embed:", len(texts))

clean_embeddings = embedding_model.encode(
    texts,
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("\nEmbedding generation complete.")
print("Embedding matrix shape:", clean_embeddings.shape)

Chunks to embed: 6763

Batches:   0%|          | 0/212 [00:00<?, ?it/s]

Embedding generation complete.
Embedding matrix shape: (6763, 384)

In [19]:
import numpy as np

print("Number of chunks:", len(retrieval_chunks_df))
print("Number of embeddings:", len(clean_embeddings))
print("Embedding dimensions:", clean_embeddings.shape[1])
print("Contains NaN:", np.isnan(clean_embeddings).any())
print("Contains infinity:", np.isinf(clean_embeddings).any())

Number of chunks: 6763
Number of embeddings: 6763
Embedding dimensions: 384
Contains NaN: False
Contains infinity: False

In [20]:
import chromadb
import os

# Persistent ChromaDB folder
chroma_path = "../chroma_db"

client = chromadb.PersistentClient(
    path=chroma_path
)

collection_name = "biodiversity_knowledge_clean"

# Delete ONLY this collection if it already exists
try:
    client.delete_collection(collection_name)
    print("Old clean collection deleted.")
except Exception:
    pass

# Create fresh collection
collection = client.create_collection(
    name=collection_name,
    metadata={"hnsw:space": "cosine"}
)

print("Created collection:", collection_name)

Created collection: biodiversity_knowledge_clean

In [21]:
batch_size = 500

for start in range(0, len(retrieval_chunks_df), batch_size):

    end = min(
        start + batch_size,
        len(retrieval_chunks_df)
    )

    batch_df = retrieval_chunks_df.iloc[start:end]

    batch_embeddings = clean_embeddings[start:end]

    collection.add(
        ids=batch_df["chunk_id"].tolist(),

        documents=batch_df["text"].tolist(),

        embeddings=batch_embeddings.tolist(),

        metadatas=[
            {
                "source_id": row["source_id"],
                "filename": row["filename"],
                "page_number": int(row["page_number"]),
                "chunk_index": int(row["chunk_index"])
            }
            for _, row in batch_df.iterrows()
        ]
    )

    print(
        f"Stored {end}/{len(retrieval_chunks_df)} chunks"
    )

Stored 500/6763 chunks
Stored 1000/6763 chunks
Stored 1500/6763 chunks
Stored 2000/6763 chunks
Stored 2500/6763 chunks
Stored 3000/6763 chunks
Stored 3500/6763 chunks
Stored 4000/6763 chunks
Stored 4500/6763 chunks
Stored 5000/6763 chunks
Stored 5500/6763 chunks
Stored 6000/6763 chunks
Stored 6500/6763 chunks
Stored 6763/6763 chunks

In [22]:
print("Expected chunks:", len(retrieval_chunks_df))
print("Stored in Chroma:", collection.count())

assert collection.count() == len(retrieval_chunks_df)

print("\nClean ChromaDB validation passed.")

Expected chunks: 6763
Stored in Chroma: 6763

Clean ChromaDB validation passed.

In [23]:
def retrieve_all_aspects(question, per_aspect_k=3):
    """
    Search every relevant aspect of the question.

    Returns candidates from ALL aspects instead of stopping
    after the first top_k results.
    """

    decomposed = decompose_query(question)

    candidates = {}

    for aspect, query in decomposed.items():

        # Embed this aspect-specific query
        query_embedding = embedding_model.encode(
            [query],
            convert_to_numpy=True,
            normalize_embeddings=True
        )[0]

        # Search clean Chroma collection
        results = collection.query(
            query_embeddings=[query_embedding.tolist()],
            n_results=per_aspect_k,
            include=[
                "documents",
                "metadatas",
                "distances"
            ]
        )

        ids = results["ids"][0]
        documents = results["documents"][0]
        metadatas = results["metadatas"][0]
        distances = results["distances"][0]

        for rank, (chunk_id, document, metadata, distance) in enumerate(
            zip(ids, documents, metadatas, distances),
            start=1
        ):

            # Deduplicate same chunk appearing for multiple aspects
            if chunk_id not in candidates:
                candidates[chunk_id] = {
                    "chunk_id": chunk_id,
                    "text": document,
                    "source_id": metadata["source_id"],
                    "page_number": metadata["page_number"],
                    "distance": float(distance),
                    "best_distance": float(distance),
                    "matched_aspects": [aspect],
                    "aspect_ranks": {aspect: rank}
                }

            else:
                candidate = candidates[chunk_id]

                candidate["matched_aspects"].append(aspect)
                candidate["aspect_ranks"][aspect] = rank

                candidate["best_distance"] = min(
                    candidate["best_distance"],
                    float(distance)
                )

    return list(candidates.values())

In [24]:
question = test_cases["GC01"]

candidates = retrieve_all_aspects(
    question,
    per_aspect_k=3
)

print("Unique candidates:", len(candidates))

for aspect in decompose_query(question):

    print("\n" + "=" * 80)
    print("ASPECT:", aspect.upper())
    print("=" * 80)

    aspect_results = [
        item
        for item in candidates
        if aspect in item["matched_aspects"]
    ]

    aspect_results.sort(
        key=lambda x: x["aspect_ranks"][aspect]
    )

    for item in aspect_results:
        print(
            item["aspect_ranks"][aspect],
            item["chunk_id"],
            item["source_id"],
            "Page", item["page_number"],
            "Distance", round(item["best_distance"], 4)
        )

        print(item["text"][:500])
        print()

Unique candidates: 11

================================================================================
ASPECT: ORIGINAL
================================================================================
1 SRC01_P0270_C005 SRC01 Page 270 Distance 0.3153
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low

2 SRC02_P0272_C003 SRC02 Page 272 Distance 0.3883
The consequences of this have included decreases in soil organic matter and high discharge of nutrients into the environment in areas where large numbers of animals are raised in intensive units, with neg- ative impacts in turn on aquatic, soil and other biodiversity (see also Chapter 3). Time-series data for such changes are rare. However, data from the above-mentioned Eurostat database on agri- environmental indicators indicate that the number of mixed crop–livestock farms in the European Unio

3 SRC01_P0234_C002 SRC01 Page 234 Distance 0.3588
For example, losses of carbon, soil structure and soil biodiversity can reduce an ecosystem’s ability to sequester carbon (Wiesmeier et al., 2019). Changes in these soil properties also decrease water infiltration capacity, root penetration and access to nutrients for plants. In concert, all of these changes increase the risk of soil erosion, land degradation, compaction and salinization, thus reducing agricultural productivity which threatens the achievements of Sustainable Development Goals, p


================================================================================
ASPECT: SOC
================================================================================
1 SRC02_P0501_C008 SRC02 Page 501 Distance 0.3461
Bengtsson, J., Ahnström, J. & Weibull, A.-C. 2005. The effects of organic agriculture on biodiversity and abundance: a meta-analysis. Journal of Applied Ecology, 42(2): 261–269.

2 SRC01_P0233_C003 SRC01 Page 233 Distance 0.3544
For example, conversion of natural ecosystems to agricultural lands has resulted in substantial environmental costs, including land degradation, increased emissions of greenhouse gases, decreased organic matter in soils, loss of biodiversity and alterations of biogeochemical and hydrological cycles (Balmford et al., 2005). Modern agriculture thus faces great challenges not only in terms of meeting the food, fibre and fuel demands of an ever-increasing human population, but also in mitigating env

3 SRC01_P0234_C002 SRC01 Page 234 Distance 0.3588
For example, losses of carbon, soil structure and soil biodiversity can reduce an ecosystem’s ability to sequester carbon (Wiesmeier et al., 2019). Changes in these soil properties also decrease water infiltration capacity, root penetration and access to nutrients for plants. In concert, all of these changes increase the risk of soil erosion, land degradation, compaction and salinization, thus reducing agricultural productivity which threatens the achievements of Sustainable Development Goals, p


================================================================================
ASPECT: RAINFALL
================================================================================
1 SRC01_P0270_C005 SRC01 Page 270 Distance 0.3153
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low

2 SRC01_P0270_C004 SRC01 Page 270 Distance 0.3715
Rainfall is low and extremely variable ranging from 500 mm to 1 000 mm annually. Due to high temperatures and evapotranspiration rates, these are mostly associated with Arenosols and Cambisols, sandy and loamy sandy soils poor in plant nutrients and with low water-holding capacity. Vegetation cover consists of short annual grasses, legumes, scattered shrubs and trees. The main livelihood activity of the communities living in the drier zone is keeping livestock including sheep, goats, cattle and

3 SRC02_P0303_C003 SRC02 Page 303 Distance 0.3862
table 5. 8 environmental and other benefits of implementing the three principles of conservation agriculture conservation agriculture principle benefits no or minimal soil disturbance soil mulch cover crop diversification increase and maintenance of nitrogen levels in root zone • • • increase of cation - exchange capacity of root zone • • • increase of rate of biomass production • • • maintenance of natural layering of soil horizons by actions of soil biota • • maintenance of supply of soil orga


================================================================================
ASPECT: LAND_USE
================================================================================
1 SRC01_P0270_C005 SRC01 Page 270 Distance 0.3153
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low

2 SRC01_P0421_C004 SRC01 Page 421 Distance 0.3844
Bivariate and multivariate trade-offs were analysed for different crop management strategies (conventional, organic, traditional, crop rotation) and their underlying socioeconomic drivers. There was a clear trade-off between crop yield and soil quality in self-subsistence systems. However, the other expected trade-offs between crop yields and soil quality have not always occurred, probably due to the overall soil quality of the region and the profile of most farms, which use low to medium inputs

3 SRC02_P0272_C003 SRC02 Page 272 Distance 0.3883
The consequences of this have included decreases in soil organic matter and high discharge of nutrients into the environment in areas where large numbers of animals are raised in intensive units, with neg- ative impacts in turn on aquatic, soil and other biodiversity (see also Chapter 3). Time-series data for such changes are rare. However, data from the above-mentioned Eurostat database on agri- environmental indicators indicate that the number of mixed crop–livestock farms in the European Unio


================================================================================
ASPECT: BIODIVERSITY
================================================================================
1 SRC02_P0241_C001 SRC02 Page 241 Distance 0.3328
197 THE STATE OF USE OF BIODIVERSITY FOR FOOD AND AGRICULTURE 5 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Figure 5.1 Perceived impacts on biodiversity for food and agriculture of various management practices and approaches Negative Positive Not known Not reported Neutral 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Landscape management Ecosystem approach to ﬁsheries Restoration practices Diversiﬁcation Home gardens Agroforestry Polyculture/aquaponics Organic agriculture Low e

2 SRC02_P0135_C001 SRC02 Page 135 Distance 0.3382
91 drivers of change of biodiversity for food and agriculture 3 the state of the world ' s biodiversity for food and agriculture production systems where reported ( in decreasing order of frequency ) impact on bfa ( number of responses ) impact on ecosystem services ( number of responses ) species ( latin name ) common english name number of countries negative neutral positive negative neutral positive pistia stratiotes water lettuce 6 self - recruiting capture fisheries, culture - based fisheri

3 SRC01_P0344_C002 SRC01 Page 344 Distance 0.3443
10 0 20 Over-use of chemical control mechanisms (e.g. pesticides, antibiotics, etc.) Monoculture Inappropriate soil management Practices leading to soil and water degradation Inappropriate water management Over-grazing Over-exploitation Changes in land use Over-use of fertilizers or other external inputs Forest clearing and habitat fragmentation 1 2 3 4 5 COUNTRIES THAT REPLIED COUNTRIES THAT REPLIED Figure 6.1.3 | Major practices that have a negative impact on soil biodiversity (Survey Question

In [25]:
def retrieve_balanced_top3(question):
    candidates = retrieve_all_aspects(
        question,
        per_aspect_k=3
    )

    decomposed = decompose_query(question)

    # Original is useful for discovery, but the scientific
    # aspects are more useful for coverage selection.
    aspects = [
        aspect
        for aspect in [
            "soc",
            "rainfall",
            "land_use",
            "biodiversity"
        ]
        if aspect in decomposed
    ]

    selected = []
    used_ids = set()

    # --------------------------------------------------
    # PASS 1:
    # Best unique chunk from each scientific aspect
    # --------------------------------------------------

    for aspect in aspects:

        aspect_candidates = [
            item
            for item in candidates
            if (
                aspect in item["matched_aspects"]
                and item["chunk_id"] not in used_ids
            )
        ]

        if not aspect_candidates:
            continue

        aspect_candidates.sort(
            key=lambda x: x["aspect_ranks"][aspect]
        )

        best = aspect_candidates[0]

        selected.append({
            **best,
            "selected_for": aspect
        })

        used_ids.add(best["chunk_id"])

    # --------------------------------------------------
    # If >3 aspects exist, rank selected evidence
    # by best semantic distance.
    # --------------------------------------------------

    if len(selected) > 3:
        selected.sort(
            key=lambda x: x["best_distance"]
        )
        selected = selected[:3]

    # --------------------------------------------------
    # PASS 2:
    # If fewer than 3, fill remaining positions using
    # best unused candidates from all searches.
    # --------------------------------------------------

    if len(selected) < 3:

        remaining = [
            item
            for item in candidates
            if item["chunk_id"] not in used_ids
        ]

        remaining.sort(
            key=lambda x: x["best_distance"]
        )

        for item in remaining:

            selected.append({
                **item,
                "selected_for": "fill"
            })

            used_ids.add(item["chunk_id"])

            if len(selected) == 3:
                break

    return selected

In [26]:
results = retrieve_balanced_top3(
    test_cases["GC01"]
)

for rank, item in enumerate(results, start=1):

    print("\n" + "=" * 90)
    print("RESULT", rank)
    print("=" * 90)

    print("Selected for:", item["selected_for"])
    print("Chunk:", item["chunk_id"])
    print("Source:", item["source_id"])
    print("Page:", item["page_number"])
    print("Distance:", round(item["best_distance"], 4))
    print("Matched aspects:", item["matched_aspects"])

    print("\nTEXT:")
    print(item["text"])

==========================================================================================
RESULT 1
==========================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Distance: 0.3153
Matched aspects: ['original', 'rainfall', 'land_use']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

==========================================================================================
RESULT 2
==========================================================================================
Selected for: biodiversity
Chunk: SRC02_P0241_C001
Source: SRC02
Page: 241
Distance: 0.3328
Matched aspects: ['biodiversity']

TEXT:
197 THE STATE OF USE OF BIODIVERSITY FOR FOOD AND AGRICULTURE 5 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Figure 5.1 Perceived impacts on biodiversity for food and agriculture of various management practices and approaches Negative Positive Not known Not reported Neutral 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Landscape management Ecosystem approach to ﬁsheries Restoration practices Diversiﬁcation Home gardens Agroforestry Polyculture/aquaponics Organic agriculture Low external input agriculture Sustainable soil management Management of micro-organisms Conservation agriculture Integrated plant nutrient management Integrated pest management Pollination management Enrichment planting Reduced impact logging Domestication Base broadening Total Number of responses 90 62 70 111 61 68 36 111 69 92 39 67 91 105 50 35 27 57 57 904 Notes: A “response” is the report of an impact by a country for a given combination of practice and production system. Countries were invited to indicate the extent of use of each practice and approach, by production system.

==========================================================================================
RESULT 3
==========================================================================================
Selected for: soc
Chunk: SRC02_P0501_C008
Source: SRC02
Page: 501
Distance: 0.3461
Matched aspects: ['soc']

TEXT:
Bengtsson, J., Ahnström, J. & Weibull, A.-C. 2005. The effects of organic agriculture on biodiversity and abundance: a meta-analysis. Journal of Applied Ecology, 42(2): 261–269.

In [27]:
import re
import pandas as pd


def looks_like_bibliography(text):
    text = str(text).strip()

    # Common bibliography characteristics
    year_matches = re.findall(
        r"\b(?:19|20)\d{2}[a-z]?\b",
        text
    )

    doi_matches = re.findall(
        r"(?:doi\s*:|https?://doi\.org/)",
        text,
        flags=re.IGNORECASE
    )

    # Author-list patterns such as:
    # Smith, J. & Jones, A.
    author_patterns = re.findall(
        r"\b[A-ZÀ-ÖØ-Ý][A-Za-zÀ-ÿ'’-]+,\s*"
        r"[A-Z](?:\.[A-Z])?\.",
        text
    )

    # Journal/reference-style vocabulary
    reference_terms = re.findall(
        r"\b(?:journal|vol\.?|volume|pp\.?|"
        r"proceedings|springer|elsevier|"
        r"wiley|cambridge university press)\b",
        text,
        flags=re.IGNORECASE
    )

    score = 0

    if len(year_matches) >= 3:
        score += 1

    if len(author_patterns) >= 3:
        score += 1

    if len(doi_matches) >= 2:
        score += 1

    if len(reference_terms) >= 2:
        score += 1

    # Require multiple bibliography signals.
    return score >= 2


retrieval_chunks_df["bibliography_like"] = (
    retrieval_chunks_df["text"].apply(looks_like_bibliography)
)

bib_candidates = retrieval_chunks_df[
    retrieval_chunks_df["bibliography_like"]
].copy()


print("Current retrieval chunks:", len(retrieval_chunks_df))
print("Bibliography-like candidates:", len(bib_candidates))

display(
    bib_candidates[
        [
            "chunk_id",
            "source_id",
            "page_number",
            "token_count",
            "text"
        ]
    ].head(30)
)

Current retrieval chunks: 6763
Bibliography-like candidates: 957

,chunk_id,source_id,page_number,token_count,text
678,SRC01_P0192_C003,SRC01,192,213,3.5.6 | WASTEWATER TREATMENT Ecosystems such a...
679,SRC01_P0192_C004,SRC01,192,166,A “solids” component comprised of biological c...
1813,SRC01_P0477_C002,SRC01,477,199,Commercialisation of entomopathogenic nematode...
1814,SRC01_P0477_C003,SRC01,477,211,"Abinandan, S., Subashchandrabose, S.R., Venkat..."
1815,SRC01_P0477_C004,SRC01,477,217,Effect of industrial residues (raw and compost...
1816,SRC01_P0477_C005,SRC01,477,139,2011. Emergence or self-organization?: Look to...
1818,SRC01_P0478_C002,SRC01,478,215,2018. Revisiting risk governance of GM plants:...
1819,SRC01_P0478_C003,SRC01,478,219,2011. Role of arbuscular mycorrhizal fungi (AM...
1820,SRC01_P0478_C004,SRC01,478,213,Agronet.fi [online]. [Cited 2 October 2020]. h...
1821,SRC01_P0478_C005,SRC01,478,207,Balance Social 2018. [online]. [Cited 5 Octobe...
1823,SRC01_P0479_C002,SRC01,479,187,2014. Comparative Study on Effect of Chemical ...
1824,SRC01_P0479_C003,SRC01,479,205,"International Journal of Phytoremediation, 10 ..."
1825,SRC01_P0479_C004,SRC01,479,220,"Alig, R.J., Plantinga, A.J., Ahn, S. & Kline, ..."
1826,SRC01_P0479_C005,SRC01,479,206,Zinc in Soils and Crop Nutrition. Internationa...
1827,SRC01_P0480_C001,SRC01,480,213,State of knowledge of soil biodiversity 450 Am...
1828,SRC01_P0480_C002,SRC01,480,216,2003. Soil diversity and land use in the Unite...
1829,SRC01_P0480_C003,SRC01,480,110,2019. Genetically engineered crops: Importance...
1831,SRC01_P0480_C005,SRC01,480,208,"Soil Biology and Biochemistry, 140: 107638. AN..."
1833,SRC01_P0481_C002,SRC01,481,218,2017. Map and shapefile of the biogeographic p...
1834,SRC01_P0481_C003,SRC01,481,203,2016. Hierarchical filters determine community...
1838,SRC01_P0482_C001,SRC01,482,217,State of knowledge of soil biodiversity 452 At...
1839,SRC01_P0482_C002,SRC01,482,202,"2019. Applications of the Soil, Plant and Rume..."
1840,SRC01_P0482_C003,SRC01,482,206,"Land management and farming in Australia. ABS,..."
1845,SRC01_P0483_C003,SRC01,483,211,2010. Tradeoffs and thresholds in the effects ...
1846,SRC01_P0483_C004,SRC01,483,219,What do we know about soil carbon destabilizat...
1847,SRC01_P0483_C005,SRC01,483,183,"Baliuk, S.A. 2015. Rational use of soil resour..."
1848,SRC01_P0484_C001,SRC01,484,219,State of knowledge of soil biodiversity 454 Ba...
1849,SRC01_P0484_C002,SRC01,484,161,"S., Lee, J.-H., Kwon, O.S., Na, Y.E., Jang, Y...."
1850,SRC01_P0484_C003,SRC01,484,217,"Save our soils. Nature, 474: 151-152. Bao, Z.,..."
1851,SRC01_P0484_C004,SRC01,484,196,"Lamagdeleine-Dent, K.A., Willand, J.E., Jones,..."

In [28]:
bib_candidates.groupby("source_id")["page_number"].agg(
    ["min", "max", "count"]
)

           min  max  count
source_id
SRC01      192  612    512
SRC02      497  573    413
SRC03      149  168     23
SRC05        8    8      9

In [29]:
for source_id in sorted(
    bib_candidates["source_id"].unique()
):

    pages = sorted(
        bib_candidates.loc[
            bib_candidates["source_id"] == source_id,
            "page_number"
        ].unique()
    )

    print("\n", source_id)
    print(pages)

 SRC01
[np.int64(192), np.int64(477), np.int64(478), np.int64(479), np.int64(480), np.int64(481), np.int64(482), np.int64(483), np.int64(484), np.int64(485), np.int64(486), np.int64(487), np.int64(488), np.int64(489), np.int64(490), np.int64(491), np.int64(492), np.int64(493), np.int64(494), np.int64(495), np.int64(496), np.int64(497), np.int64(498), np.int64(499), np.int64(500), np.int64(501), np.int64(502), np.int64(503), np.int64(504), np.int64(505), np.int64(506), np.int64(507), np.int64(508), np.int64(509), np.int64(510), np.int64(511), np.int64(512), np.int64(513), np.int64(514), np.int64(515), np.int64(516), np.int64(517), np.int64(518), np.int64(519), np.int64(520), np.int64(521), np.int64(522), np.int64(523), np.int64(524), np.int64(525), np.int64(526), np.int64(528), np.int64(529), np.int64(530), np.int64(531), np.int64(532), np.int64(533), np.int64(534), np.int64(535), np.int64(536), np.int64(537), np.int64(538), np.int64(539), np.int64(540), np.int64(541), np.int64(542), np.int64(543), np.int64(544), np.int64(545), np.int64(546), np.int64(547), np.int64(548), np.int64(549), np.int64(550), np.int64(551), np.int64(552), np.int64(553), np.int64(554), np.int64(555), np.int64(556), np.int64(557), np.int64(559), np.int64(560), np.int64(561), np.int64(562), np.int64(563), np.int64(564), np.int64(565), np.int64(566), np.int64(567), np.int64(568), np.int64(569), np.int64(570), np.int64(571), np.int64(572), np.int64(573), np.int64(574), np.int64(575), np.int64(576), np.int64(577), np.int64(578), np.int64(579), np.int64(580), np.int64(581), np.int64(582), np.int64(583), np.int64(584), np.int64(585), np.int64(586), np.int64(587), np.int64(588), np.int64(589), np.int64(590), np.int64(591), np.int64(592), np.int64(593), np.int64(594), np.int64(595), np.int64(596), np.int64(597), np.int64(598), np.int64(599), np.int64(600), np.int64(601), np.int64(602), np.int64(603), np.int64(604), np.int64(605), np.int64(606), np.int64(607), np.int64(608), np.int64(609), np.int64(610), np.int64(611), np.int64(612)]

 SRC02
[np.int64(497), np.int64(498), np.int64(499), np.int64(500), np.int64(501), np.int64(502), np.int64(503), np.int64(504), np.int64(505), np.int64(506), np.int64(508), np.int64(509), np.int64(510), np.int64(511), np.int64(512), np.int64(513), np.int64(514), np.int64(515), np.int64(516), np.int64(517), np.int64(524), np.int64(525), np.int64(526), np.int64(527), np.int64(528), np.int64(529), np.int64(530), np.int64(531), np.int64(532), np.int64(533), np.int64(534), np.int64(535), np.int64(536), np.int64(537), np.int64(538), np.int64(539), np.int64(540), np.int64(541), np.int64(542), np.int64(543), np.int64(544), np.int64(545), np.int64(546), np.int64(547), np.int64(548), np.int64(549), np.int64(550), np.int64(551), np.int64(552), np.int64(553), np.int64(554), np.int64(555), np.int64(556), np.int64(557), np.int64(558), np.int64(559), np.int64(560), np.int64(561), np.int64(562), np.int64(563), np.int64(564), np.int64(565), np.int64(566), np.int64(567), np.int64(568), np.int64(569), np.int64(570), np.int64(571), np.int64(572), np.int64(573)]

 SRC03
[np.int64(149), np.int64(150), np.int64(151), np.int64(154), np.int64(155), np.int64(156), np.int64(157), np.int64(158), np.int64(160), np.int64(162), np.int64(165), np.int64(168)]

 SRC05
[np.int64(8)]

In [30]:
# ============================================================
# REMOVE CONFIRMED BIBLIOGRAPHY SECTIONS
# ============================================================

before_bib_cleanup = len(retrieval_chunks_df)

reference_section_mask = (
    # SRC01: references begin at page 477
    (
        (retrieval_chunks_df["source_id"] == "SRC01")
        & (retrieval_chunks_df["page_number"] >= 477)
    )
    |
    # SRC02: references begin around page 497
    (
        (retrieval_chunks_df["source_id"] == "SRC02")
        & (retrieval_chunks_df["page_number"] >= 497)
    )
)

removed_reference_chunks = retrieval_chunks_df[
    reference_section_mask
].copy()

retrieval_chunks_df = retrieval_chunks_df[
    ~reference_section_mask
].copy()

retrieval_chunks_df.reset_index(drop=True, inplace=True)

print("Before bibliography cleanup:", before_bib_cleanup)
print("Reference chunks removed:", len(removed_reference_chunks))
print("Final retrieval chunks:", len(retrieval_chunks_df))

print("\nRemoved by source:")
print(
    removed_reference_chunks["source_id"]
    .value_counts()
)

Before bibliography cleanup: 6763
Reference chunks removed: 1316
Final retrieval chunks: 5447

Removed by source:
source_id
SRC01    730
SRC02    586
Name: count, dtype: int64

In [32]:
print("\nMaximum remaining pages:")
print(
    retrieval_chunks_df.groupby("source_id")["page_number"].max()
)

print("\nRemaining suspicious bibliography candidates:")

remaining_bib = bib_candidates[
    bib_candidates["chunk_id"].isin(
        retrieval_chunks_df["chunk_id"]
    )
]

print(
    remaining_bib.groupby("source_id")["page_number"]
    .agg(["min", "max", "count"])
)

display(
    remaining_bib[
        ["chunk_id", "source_id", "page_number", "text"]
    ].head(30)
)

Maximum remaining pages:
source_id
SRC01    475
SRC02    496
SRC03    172
SRC04      5
SRC05      8
Name: page_number, dtype: int64

Remaining suspicious bibliography candidates:
           min  max  count
source_id
SRC01      192  192      2
SRC03      149  168     23
SRC05        8    8      9

,chunk_id,source_id,page_number,text
678,SRC01_P0192_C003,SRC01,192,3.5.6 | WASTEWATER TREATMENT Ecosystems such a...
679,SRC01_P0192_C004,SRC01,192,A “solids” component comprised of biological c...
3057,SRC03_P0149_C001,SRC03,149,"127 References, further reading, tools and gui..."
3058,SRC03_P0149_C002,SRC03,149,"Aronson, (eds). Restoration ecology: the new f..."
3060,SRC03_P0150_C001,SRC03,150,Global guidelines for the restoration of degra...
3061,SRC03_P0150_C002,SRC03,150,"Buffle, P. & Reij, C. 2012. Land rehabilitatio..."
3063,SRC03_P0150_C004,SRC03,150,Comité permanent Inter-États de lutte contre l...
3064,SRC03_P0151_C002,SRC03,151,Making change happen: what can governments do ...
3073,SRC03_P0154_C001,SRC03,154,Global guidelines for the restoration of degra...
3076,SRC03_P0154_C004,SRC03,154,2011. Dry land tree management for improved ho...
3079,SRC03_P0155_C003,SRC03,155,A guide to the Restoration Opportunities Asses...
3080,SRC03_P0156_C001,SRC03,156,Global guidelines for the restoration of degra...
3081,SRC03_P0156_C002,SRC03,156,"Mansourian, S. 2009. Forests in arid zones: is..."
3083,SRC03_P0157_C002,SRC03,157,Payments for environmental services: a way for...
3084,SRC03_P0157_C003,SRC03,157,The forest landscape restoration handbook. Int...
3085,SRC03_P0158_C001,SRC03,158,Global guidelines for the restoration of degra...
3086,SRC03_P0158_C002,SRC03,158,Applying resilience thinking: seven principles...
3087,SRC03_P0158_C003,SRC03,158,2011. The forgotten billion: MDG achievement i...
3093,SRC03_P0160_C003,SRC03,160,"2005. Restoring forest landscapes. Gland, Swit..."
3094,SRC03_P0160_C004,SRC03,160,A guide for desert and dryland restoration: ne...
3098,SRC03_P0162_C001,SRC03,162,Global guidelines for the restoration of degra...
3099,SRC03_P0162_C002,SRC03,162,"Haglund, E., Ndjeunga, J., Snook, L. & Pastern..."
3102,SRC03_P0165_C001,SRC03,165,﻿ 143 FAO FORESTRY PAPERS 1 Forest utilization...
3105,SRC03_P0165_C004,SRC03,165,"1, 1980 (E) 19/2 Pulping and paper‑making prop..."
3115,SRC03_P0168_C003,SRC03,168,"and study of change processes, 1996 ( e ) 131 ..."
3229,SRC05_P0008_C001,SRC05,8,"Tamburini et al., Sci. Adv. 2020; 6 : eaba1715..."
3231,SRC05_P0008_C003,SRC05,8,"S. Srivastava, S. Naeem, Biodiversity loss and..."
3232,SRC05_P0008_C004,SRC05,8,"Ecol. Soc. 17, 40 (2012). 10. J. Rosa-Schleich..."
3239,SRC05_P0008_C011,SRC05,8,"Parrott, A. Peeters, A. Rossi, M. Schermer, F...."
3240,SRC05_P0008_C012,SRC05,8,"J. Gurevitch, J. Koricheva, S. Nakagawa, G. St..."

In [33]:
# ============================================================
# FINAL STRUCTURAL BACK-MATTER CLEANUP
# ============================================================

before_final_cleanup = len(retrieval_chunks_df)

final_backmatter_mask = (
    # SRC03: references/further reading/back matter starts page 149
    (
        (retrieval_chunks_df["source_id"] == "SRC03")
        & (retrieval_chunks_df["page_number"] >= 149)
    )
    |
    # SRC05: page 8 is the paper's reference section
    (
        (retrieval_chunks_df["source_id"] == "SRC05")
        & (retrieval_chunks_df["page_number"] >= 8)
    )
)

removed_final_backmatter = retrieval_chunks_df[
    final_backmatter_mask
].copy()

retrieval_chunks_df = retrieval_chunks_df[
    ~final_backmatter_mask
].copy()

retrieval_chunks_df.reset_index(drop=True, inplace=True)

print("Before final cleanup:", before_final_cleanup)
print("Additional chunks removed:", len(removed_final_backmatter))
print("FINAL retrieval corpus:", len(retrieval_chunks_df))

print("\nRemoved by source:")
print(removed_final_backmatter["source_id"].value_counts())

print("\nMaximum remaining page per source:")
print(
    retrieval_chunks_df
    .groupby("source_id")["page_number"]
    .max()
)

Before final cleanup: 5447
Additional chunks removed: 83
FINAL retrieval corpus: 5364

Removed by source:
source_id
SRC03    66
SRC05    17
Name: count, dtype: int64

Maximum remaining page per source:
source_id
SRC01    475
SRC02    496
SRC03    147
SRC04      5
SRC05      7
Name: page_number, dtype: int64

In [34]:
print("FINAL CORPUS VALIDATION")
print("-----------------------")
print("Total chunks:", len(retrieval_chunks_df))
print("Sources:", retrieval_chunks_df["source_id"].nunique())
print("Duplicate IDs:", retrieval_chunks_df["chunk_id"].duplicated().sum())
print("Missing text:", retrieval_chunks_df["text"].isna().sum())
print("Empty text:", (retrieval_chunks_df["text"].str.strip() == "").sum())

# Confirm known bad chunks are gone
known_bad = [
    "SRC01_P0601_C005",
    "SRC02_P0501_C008",
    "SRC03_P0149_C001",
    "SRC05_P0008_C001"
]

print("\nKnown bad chunk check:")
for chunk_id in known_bad:
    print(
        chunk_id,
        "PRESENT" if chunk_id in set(retrieval_chunks_df["chunk_id"])
        else "REMOVED ✓"
    )

FINAL CORPUS VALIDATION
-----------------------
Total chunks: 5364
Sources: 5
Duplicate IDs: 0
Missing text: 0
Empty text: 0

Known bad chunk check:
SRC01_P0601_C005 REMOVED ✓
SRC02_P0501_C008 REMOVED ✓
SRC03_P0149_C001 REMOVED ✓
SRC05_P0008_C001 REMOVED ✓

In [35]:
final_texts = retrieval_chunks_df["text"].tolist()

print("Chunks to embed:", len(final_texts))

final_embeddings = embedding_model.encode(
    final_texts,
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("\nEmbedding generation complete.")
print("Embedding matrix shape:", final_embeddings.shape)

Chunks to embed: 5364

Batches:   0%|          | 0/168 [00:00<?, ?it/s]

Embedding generation complete.
Embedding matrix shape: (5364, 384)

In [36]:
import numpy as np

print("Chunks:", len(retrieval_chunks_df))
print("Embeddings:", len(final_embeddings))
print("Dimensions:", final_embeddings.shape[1])
print("Contains NaN:", np.isnan(final_embeddings).any())
print("Contains infinity:", np.isinf(final_embeddings).any())

Chunks: 5364
Embeddings: 5364
Dimensions: 384
Contains NaN: False
Contains infinity: False

In [37]:
collection_name = "biodiversity_knowledge_clean"

try:
    client.delete_collection(collection_name)
    print("Old collection deleted.")
except Exception:
    pass

collection = client.create_collection(
    name=collection_name,
    metadata={"hnsw:space": "cosine"}
)

print("Fresh collection created.")

Old collection deleted.
Fresh collection created.

In [38]:
batch_size = 500

for start in range(0, len(retrieval_chunks_df), batch_size):

    end = min(
        start + batch_size,
        len(retrieval_chunks_df)
    )

    batch_df = retrieval_chunks_df.iloc[start:end]
    batch_embeddings = final_embeddings[start:end]

    collection.add(
        ids=batch_df["chunk_id"].tolist(),
        documents=batch_df["text"].tolist(),
        embeddings=batch_embeddings.tolist(),
        metadatas=[
            {
                "source_id": row["source_id"],
                "filename": row["filename"],
                "page_number": int(row["page_number"]),
                "chunk_index": int(row["chunk_index"])
            }
            for _, row in batch_df.iterrows()
        ]
    )

    print(f"Stored {end}/{len(retrieval_chunks_df)} chunks")

Stored 500/5364 chunks
Stored 1000/5364 chunks
Stored 1500/5364 chunks
Stored 2000/5364 chunks
Stored 2500/5364 chunks
Stored 3000/5364 chunks
Stored 3500/5364 chunks
Stored 4000/5364 chunks
Stored 4500/5364 chunks
Stored 5000/5364 chunks
Stored 5364/5364 chunks

In [39]:
print("Expected:", len(retrieval_chunks_df))
print("Stored:", collection.count())

assert collection.count() == len(retrieval_chunks_df)

print("\nFINAL ChromaDB validation passed.")

Expected: 5364
Stored: 5364

FINAL ChromaDB validation passed.

In [40]:
results = retrieve_balanced_top3(
    test_cases["GC01"]
)

for rank, item in enumerate(results, start=1):

    print("\n" + "=" * 90)
    print("RESULT", rank)
    print("=" * 90)

    print("Selected for:", item["selected_for"])
    print("Chunk:", item["chunk_id"])
    print("Source:", item["source_id"])
    print("Page:", item["page_number"])
    print("Distance:", round(item["best_distance"], 4))
    print("Matched aspects:", item["matched_aspects"])

    print("\nTEXT:")
    print(item["text"])

==========================================================================================
RESULT 1
==========================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Distance: 0.3153
Matched aspects: ['original', 'rainfall', 'land_use']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

==========================================================================================
RESULT 2
==========================================================================================
Selected for: biodiversity
Chunk: SRC02_P0241_C001
Source: SRC02
Page: 241
Distance: 0.3328
Matched aspects: ['biodiversity']

TEXT:
197 THE STATE OF USE OF BIODIVERSITY FOR FOOD AND AGRICULTURE 5 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Figure 5.1 Perceived impacts on biodiversity for food and agriculture of various management practices and approaches Negative Positive Not known Not reported Neutral 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Landscape management Ecosystem approach to ﬁsheries Restoration practices Diversiﬁcation Home gardens Agroforestry Polyculture/aquaponics Organic agriculture Low external input agriculture Sustainable soil management Management of micro-organisms Conservation agriculture Integrated plant nutrient management Integrated pest management Pollination management Enrichment planting Reduced impact logging Domestication Base broadening Total Number of responses 90 62 70 111 61 68 36 111 69 92 39 67 91 105 50 35 27 57 57 904 Notes: A “response” is the report of an impact by a country for a given combination of practice and production system. Countries were invited to indicate the extent of use of each practice and approach, by production system.

==========================================================================================
RESULT 3
==========================================================================================
Selected for: soc
Chunk: SRC01_P0233_C003
Source: SRC01
Page: 233
Distance: 0.3544
Matched aspects: ['soc']

TEXT:
For example, conversion of natural ecosystems to agricultural lands has resulted in substantial environmental costs, including land degradation, increased emissions of greenhouse gases, decreased organic matter in soils, loss of biodiversity and alterations of biogeochemical and hydrological cycles (Balmford et al., 2005). Modern agriculture thus faces great challenges not only in terms of meeting the food, fibre and fuel demands of an ever-increasing human population, but also in mitigating environmental costs, particularly in the context of inappropriate management practices, a changing environment and growing competition for land, water and energy (Chen et al., 2014). Understanding the mechanisms that control the extent to which soil properties and biological communities change following the conversion of natural to agricultural systems and management practices is of paramount importance to comprehend the consequences of land use changes for soil functions and agricultural productivity (Sala et al., 2000). Agricultural management practices act and interact with each other in different ways, and affect the soil ecosystem to different degrees and to different extents.

In [41]:
all_golden_results = {}

for case_id, question in test_cases.items():

    print("\n" + "#" * 100)
    print(case_id)
    print("QUESTION:", question)
    print("#" * 100)

    results = retrieve_balanced_top3(question)

    all_golden_results[case_id] = results

    for rank, item in enumerate(results, start=1):

        print("\n" + "=" * 80)
        print(f"RESULT {rank}")
        print("=" * 80)

        print("Selected for:", item["selected_for"])
        print("Chunk:", item["chunk_id"])
        print("Source:", item["source_id"])
        print("Page:", item["page_number"])
        print("Distance:", round(item["best_distance"], 4))
        print("Matched aspects:", item["matched_aspects"])

        print("\nTEXT:")
        print(item["text"])

####################################################################################################
GC01
QUESTION: A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Distance: 0.3153
Matched aspects: ['original', 'rainfall', 'land_use']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

================================================================================
RESULT 2
================================================================================
Selected for: biodiversity
Chunk: SRC02_P0241_C001
Source: SRC02
Page: 241
Distance: 0.3328
Matched aspects: ['biodiversity']

TEXT:
197 THE STATE OF USE OF BIODIVERSITY FOR FOOD AND AGRICULTURE 5 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Figure 5.1 Perceived impacts on biodiversity for food and agriculture of various management practices and approaches Negative Positive Not known Not reported Neutral 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Landscape management Ecosystem approach to ﬁsheries Restoration practices Diversiﬁcation Home gardens Agroforestry Polyculture/aquaponics Organic agriculture Low external input agriculture Sustainable soil management Management of micro-organisms Conservation agriculture Integrated plant nutrient management Integrated pest management Pollination management Enrichment planting Reduced impact logging Domestication Base broadening Total Number of responses 90 62 70 111 61 68 36 111 69 92 39 67 91 105 50 35 27 57 57 904 Notes: A “response” is the report of an impact by a country for a given combination of practice and production system. Countries were invited to indicate the extent of use of each practice and approach, by production system.

================================================================================
RESULT 3
================================================================================
Selected for: soc
Chunk: SRC01_P0233_C003
Source: SRC01
Page: 233
Distance: 0.3544
Matched aspects: ['soc']

TEXT:
For example, conversion of natural ecosystems to agricultural lands has resulted in substantial environmental costs, including land degradation, increased emissions of greenhouse gases, decreased organic matter in soils, loss of biodiversity and alterations of biogeochemical and hydrological cycles (Balmford et al., 2005). Modern agriculture thus faces great challenges not only in terms of meeting the food, fibre and fuel demands of an ever-increasing human population, but also in mitigating environmental costs, particularly in the context of inappropriate management practices, a changing environment and growing competition for land, water and energy (Chen et al., 2014). Understanding the mechanisms that control the extent to which soil properties and biological communities change following the conversion of natural to agricultural systems and management practices is of paramount importance to comprehend the consequences of land use changes for soil functions and agricultural productivity (Sala et al., 2000). Agricultural management practices act and interact with each other in different ways, and affect the soil ecosystem to different degrees and to different extents.

####################################################################################################
GC02
QUESTION: My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: soc
Chunk: SRC01_P0180_C005
Source: SRC01
Page: 180
Distance: 0.3369
Matched aspects: ['original', 'soc', 'land_use']

TEXT:
Healthy soils unify productive and natural systems by focusing on maintaining an intact, diverse below-ground ecosystem that ensures the flow of carbon, nutrients, and energy necessary for resilient landscapes (Kibblewhite et al., 2008). As a terrestrial system accrues soil organic matter, both soil health and soil organic carbon increase and a multitude of co-benefits emerge. Future plans, challenges and gaps While the potential for synergies from harnessing soil biodiversity for climate action with other global agendas is enormous, transformative policies and action and enabling conditions are necessary for success. Existing nature protection policies need to be fully implemented, and there is a pressing need for support and security of tenure for those at the front line of protecting, restoring and caring for land and soil and conserving its biodiversity, including indigenous peoples and local communities. There is also a need for education and awareness raising, capacity strengthening and full engagement across the public and private sector towards overcoming financial barriers and implementing natural capital accounting and payment for ecosystem services.

================================================================================
RESULT 2
================================================================================
Selected for: land_use
Chunk: SRC01_P0007_C001
Source: SRC01
Page: 7
Distance: 0.339
Matched aspects: ['soc', 'land_use']

TEXT:
v 3. 6. 2 | aesthetic appreciation and inspiration for culture, art and design 175 3. 6. 3 | cultural heritage, knowledge and education 180 3. 6. 4 | recreation and mental and physical health 180 3. 7 | economic value of soil biodiversity 182 3. 7. 1 | the challenge of valuing soil organisms 185 chapter 4 threats to soil biodiversity - global and regional trends 191 4. 1 | introduction 191 4. 2 | threats to soil biodiversity 198 4. 2. 1 | deforestation 198 4. 2. 2 | urbanization 200 4. 2. 3 | agricultural intensification 202 4. 2. 4 | loss of soil organic matter and soil organic carbon 205 4. 2. 5 | soil compaction and sealing 210 4. 2. 6 | soil acidification and nutrient imbalances 213 4. 2. 7 | pollution 216 4. 2. 8 | salinization and sodification 221 4. 2. 9 | fire 224 4. 2. 10 | erosion and landslides 226 4. 2. 11 | climate change 232 4

================================================================================
RESULT 3
================================================================================
Selected for: biodiversity
Chunk: SRC01_P0189_C004
Source: SRC01
Page: 189
Distance: 0.3457
Matched aspects: ['original', 'soc', 'rainfall', 'land_use', 'biodiversity']

TEXT:
General guidelines to make soils more resilient to climate change should include the following: (1) Conservation of C-rich soils like peatlands, forest soils and permanent grasslands should become a priority. (2) Improve SOC pool by adopting less intensive agricultural practices that limit/exclude agrochemical use and maintain a live plant cover (such as conservation agriculture) or use organic amendments such as mulch, compost. (3) Adopting ‘paludiculture’ practices to cultivate organic soils without drainage, whereas land use practices that require drainage should, if possible, be relocated to areas with mineral soils. (4) Increase soil biodiversity by protecting natural areas, keeping habitat heterogeneity and diversifying land use options. The great recent advances in collating and mapping soil biodiversity data at global scales (see for example Tedersoo et al., 2014; van den Hoogen et al., 2019; Phillips et al., 2019) means that it will now be possible to link specific soil biota groups to terrestrial carbon stocks.

####################################################################################################
GC04
QUESTION: We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: soc
Chunk: SRC01_P0236_C003
Source: SRC01
Page: 236
Distance: 0.3169
Matched aspects: ['soc']

TEXT:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

================================================================================
RESULT 2
================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Distance: 0.3905
Matched aspects: ['original', 'rainfall', 'land_use']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

================================================================================
RESULT 3
================================================================================
Selected for: land_use
Chunk: SRC05_P0004_C007
Source: SRC05
Page: 4
Distance: 0.4025
Matched aspects: ['land_use']

TEXT:
This would allow a comprehensive understanding for effects of or- ganic amendments on climate change. A key challenge for sustain- able crop production is hence to seek diversification solutions that simultaneously sustain soil health, crop yield, and mitigation of climate change. We show that agricultural diversification promotes biodiversity and the delivery of ecosystem services without compromising crop yield. This suggests several pathways for future sustainable food production and demonstrates how mainstream, high-yielding crop production can benefit from management that bolsters biodiversity. Large areas of cropland with monocultures in vast crop fields, such as in Australia, and North and South America (3), could benefit by the implementation of longer crop rotations, intercropping, and higher noncrop species diversity that enhance aboveground bio- diversity and the provisioning of regulating services, such as pollina- tion, pest control, and water regulation. Belowground biodiversity and services associated with soil quality are mainly supported by organic amendment and reduced tillage.

####################################################################################################
GC06
QUESTION: Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now.
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: soc
Chunk: SRC01_P0324_C001
Source: SRC01
Page: 324
Distance: 0.3082
Matched aspects: ['soc']

TEXT:
State of knowledge of soil biodiversity 294 5.4.3 | SOIL BIODIVERSITY AS A FARMER’S TOOL The adoption of soil conservation practices such as reduced tillage, improved residue management, reduced bare fallow and conservation reserve plantings have stabilized, and partially reversed, soil organic carbon (SOC) loss in North American agricultural soils (Paustian et al., 2016). Improved grazing management, fertilization, and sowing legumes and improved grass species are additional ways to increase soil C by as much as 1 Mg C/ ha/yr in best cases (Conant et al., 2016). Restoration of late-successional grassland plant diversity leads to accelerating annual carbon storage rates on degraded and abandoned agricultural lands that, by the second period (years 13 to 22), are 200 percent greater in the highest diversity treatment than during succession at this site, and 70 percent greater than in monocultures.

================================================================================
RESULT 2
================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Distance: 0.3153
Matched aspects: ['original', 'rainfall', 'land_use', 'biodiversity']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

================================================================================
RESULT 3
================================================================================
Selected for: biodiversity
Chunk: SRC02_P0113_C007
Source: SRC02
Page: 113
Distance: 0.357
Matched aspects: ['biodiversity']

TEXT:
For the remaining drivers (markets, trade and the private sector, and changing economic, sociopolitical and cul- tural factors) responses are more mixed, but with negative responses the more frequent. With regard to knowledge of wild foods, reports of positive impacts are more frequent than other responses in the case of the following drivers: advancements and innovations in science and technology; policies; markets, trade and the private sector; and changing economic, socio- political and cultural factors. For diversity, the only two drivers for which positive responses outnumber negative are policies, and advance- ments in science and technologies. 3.3 Economic and social drivers • Information from countries indicates that population growth and urbanization, and associated habitat destruction and land conversion, are having a negative effect on biodiversity for food and agriculture (BFA) and ecosystem services, with forests and coastal habitats appearing to be particularly threatened. • Outmigration from rural areas is tending to lead to changes in management practices and land use, in some cases leading to the decline of traditional, biodiverse production systems.

####################################################################################################
GC07
QUESTION: Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Distance: 0.2712
Matched aspects: ['original', 'rainfall', 'land_use']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0344_C001
Source: SRC01
Page: 344
Distance: 0.2877
Matched aspects: ['original', 'soc', 'rainfall', 'land_use', 'biodiversity']

TEXT:
State of knowledge of soil biodiversity 314 10 0 20 What are the major practices in this country that might have negatively impacted soil biodiversity in the last 10 years (1 being the lowest important and 5 being the highest)?

================================================================================
RESULT 3
================================================================================
Selected for: biodiversity
Chunk: SRC01_P0348_C002
Source: SRC01
Page: 348
Distance: 0.3186
Matched aspects: ['biodiversity']

TEXT:
HIGHLIGHTS • There is an overall interest in promoting sustainable soil management as well as sustainable agriculture and/or sustainable intensification practices through policies, laws and other activities. • There is a growing interest in examining and understanding the connections between soil biodiversity and other topics such as human health and ecosystem restoration. • There are some direct and indirect references to soil biodiversity in countries’ National Biodiversity Strategies and Action Plans (NBSAPs) and other global commitments. • There is some direct and indirect integration of soil biodiversity in sectoral and/or cross-sectoral policies. • Some countries are starting to integrate soil biodiversity in different areas such as food security, environment, forestry, agriculture, protected areas, land management, climate change, indigenous peoples and local communities and family farmers. • There is a general lack of specific policies, programmes and actions that take into account the particularities of soil biodiversity, as well as measures to promote its conservation and sustainable use.

In [42]:
question = test_cases["GC07"]

queries = decompose_query(question)

for aspect, query in queries.items():

    print("\n" + "=" * 90)
    print("ASPECT:", aspect.upper())
    print("=" * 90)

    results = retrieve(query, top_k=10)

    for rank, item in enumerate(results, start=1):

        print(
            rank,
            item["chunk_id"],
            item["source_id"],
            "Page", item["page_number"],
            "Distance", round(item["distance"], 4)
        )

        print(item["text"][:350].replace("\n", " "))
        print()

==========================================================================================
ASPECT: ORIGINAL
==========================================================================================

NameError: name 'retrieve' is not defined

In [44]:
# ============================================================
# GC07 DIAGNOSTIC — TOP 10 PER ASPECT
# ============================================================

question = test_cases["GC07"]

queries = decompose_query(question)

for aspect, query in queries.items():

    print("\n" + "=" * 90)
    print("ASPECT:", aspect.upper())
    print("=" * 90)

    # Embed query using the SAME MiniLM model
    query_embedding = embedding_model.encode(
        query,
        normalize_embeddings=True
    ).tolist()

    # Search final Chroma collection
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=10,
        include=["documents", "metadatas", "distances"]
    )

    for rank in range(len(results["ids"][0])):

        chunk_id = results["ids"][0][rank]
        text = results["documents"][0][rank]
        metadata = results["metadatas"][0][rank]
        distance = results["distances"][0][rank]

        print(
            f"\n{rank + 1}. "
            f"{chunk_id} | "
            f"{metadata['source_id']} | "
            f"Page {metadata['page_number']} | "
            f"Distance {distance:.4f}"
        )

        print(text[:500])

==========================================================================================
ASPECT: ORIGINAL
==========================================================================================

1. SRC01_P0344_C001 | SRC01 | Page 344 | Distance 0.2901
State of knowledge of soil biodiversity 314 10 0 20 What are the major practices in this country that might have negatively impacted soil biodiversity in the last 10 years (1 being the lowest important and 5 being the highest)?

2. SRC01_P0270_C005 | SRC01 | Page 270 | Distance 0.3163
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low

3. SRC01_P0449_C004 | SRC01 | Page 449 | Distance 0.3310
For example, the commercial inoculation of crop legumes grown with selected efficient bacteria has been shown to improve overall sustainable crop production and nutrition, while also benefiting the environment (Stagnari, Maggio, Galieni et al., 2017). The United States of America reported that soil biodiversity has a number of practical applications, ranging from biological nitrogen fixation, carbon cycling (including sequestration, but also CH4 and CO2 emissions), to the creation and stabilizat

4. SRC01_P0297_C001 | SRC01 | Page 297 | Distance 0.3344
Responses and opportunities 267 Figure 5.1.1 (previous page) | Management of soil biodiversity Along with other strategies, some environmental problems and crop needs can be tackled with nature-based solutions. The development of these types of solutions should be based on comprehensive approaches that consider the interactions of plants with soil biodiversity as well as the management of beneficial and harmful organisms. 5.2 | ECOSYSTEM RESTORATION: STARTING FROM THE GROUND AND LEVERAGING SOIL

5. SRC02_P0143_C001 | SRC02 | Page 143 | Distance 0.3360
99 Drivers of change of biodiversity for food and agriculture 3 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE characteristics and the diversity of the local soil fauna and flora. Soil biodiversity is greatly influenced by the quantity and quality of organic matter present in the soil. The biodiversity in overexploited soils is less abundant, dominated by fewer species and characterized by simpler trophic networks (Creamer et al., 2016). Loss of soil organic matter may lead to we

6. SRC01_P0302_C001 | SRC01 | Page 302 | Distance 0.3401
State of knowledge of soil biodiversity 272 5.2.2 | NOVEL WHOLE-ECOSYSTEM APPROACHES FOR SOIL RESTORATION AND SOIL MANAGEMENT Human management of agricultural land and other soils is known to reduce soil biodiversity. Examples include negative effects of tillage (Tsiafouli et al., 2015), mineral fertilizers (Ramirez et al., 2012) and pesticides (Thiele-Bruhn et al., 2012) on field level (functional) soil diversity. Insufficient return of organic matter to agricultural soils has led to severe deg

7. SRC02_P0191_C001 | SRC02 | Page 191 | Distance 0.3496
147 THE STATus AND TRENDS OF BIODIVERSITY FOR FOOD AND AGRICULTURE 4 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Table 4.8 Summary of regional extent, trends and uncertainties of soil-biodiversity loss presented in the Status of the World’s Soil Resources Condition and trend Confidence Region Summary Very poor Poor Fair Good Very good In condition In trend Sub-Saharan Africa Sub-Saharan Africa suffers a high rate of deforestation. The areas most affected are those in the moist

8. SRC01_P0294_C005 | SRC01 | Page 294 | Distance 0.3505
Knowledge on how the physical, chemical and biological components interact is needed in order to restore and manage the integrity and functioning of soils, and how soil biodiversity enhances soil multi-functionality. The FAO and ITPS (2015) Status of the World Soil Resources Report states that 33 percent of land is “moderately to highly degraded.” This calls for immediate action to restore degraded lands through the implementation of sustainable soil management, particularly in regions where fra

9. SRC02_P0297_C005 | SRC02 | Page 297 | Distance 0.3520
Interventions can involve both the direct manipulation of the biological community (e.g. introduction of beneficial organisms) and indirect interventions that alter or maintain the environ- ment in ways that favour the presence of benefi- cial species or biodiversity in general. The impacts of various management practices on soil biodiver- sity are reviewed by Beed et al. (2017), Briones and Schmidt (2017), Cock et al. (2012), D’Hose et al. (2018), FAO and ITPS (2015), Lehmann et al. (2011), Org

10. SRC02_P0299_C001 | SRC02 | Page 299 | Distance 0.3522
255 THE STATE OF USE OF BIODIVERSITY FOR FOOD AND AGRICULTURE 5 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE of such practices.62 Of the 91 reporting countries, 39 reported the adoption of sustainable soil man- agement practices. Responses are summarized in Table 5.1 and Table 5.2. Sustainable soil manage- ment practices are reported for all land-based production-system categories. In each case, increases in implementation are indicated more frequently than decreases. Depending

==========================================================================================
ASPECT: SOC
==========================================================================================

1. SRC01_P0344_C001 | SRC01 | Page 344 | Distance 0.2915
State of knowledge of soil biodiversity 314 10 0 20 What are the major practices in this country that might have negatively impacted soil biodiversity in the last 10 years (1 being the lowest important and 5 being the highest)?

2. SRC01_P0227_C001 | SRC01 | Page 227 | Distance 0.3162
Threats to soil biodiversity - global and regional trends 197 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 C C C C C C C C C C C Impacts on soil biodiversity Erosion and landslides drivers and effects on soils • Detachment, transport and deposition of soil particles by water or wind. • Loss of organic matter and changes in soil physical and chemical properties. • Creation of degraded and enriched depositional environments. • Inhabitants of upper soil layers may be eliminated or displaced. • Loss

3. SRC02_P0143_C001 | SRC02 | Page 143 | Distance 0.3179
99 Drivers of change of biodiversity for food and agriculture 3 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE characteristics and the diversity of the local soil fauna and flora. Soil biodiversity is greatly influenced by the quantity and quality of organic matter present in the soil. The biodiversity in overexploited soils is less abundant, dominated by fewer species and characterized by simpler trophic networks (Creamer et al., 2016). Loss of soil organic matter may lead to we

4. SRC01_P0344_C002 | SRC01 | Page 344 | Distance 0.3251
10 0 20 Over-use of chemical control mechanisms (e.g. pesticides, antibiotics, etc.) Monoculture Inappropriate soil management Practices leading to soil and water degradation Inappropriate water management Over-grazing Over-exploitation Changes in land use Over-use of fertilizers or other external inputs Forest clearing and habitat fragmentation 1 2 3 4 5 COUNTRIES THAT REPLIED COUNTRIES THAT REPLIED Figure 6.1.3 | Major practices that have a negative impact on soil biodiversity (Survey Question

5. SRC01_P0449_C004 | SRC01 | Page 449 | Distance 0.3258
For example, the commercial inoculation of crop legumes grown with selected efficient bacteria has been shown to improve overall sustainable crop production and nutrition, while also benefiting the environment (Stagnari, Maggio, Galieni et al., 2017). The United States of America reported that soil biodiversity has a number of practical applications, ranging from biological nitrogen fixation, carbon cycling (including sequestration, but also CH4 and CO2 emissions), to the creation and stabilizat

6. SRC01_P0226_C001 | SRC01 | Page 226 | Distance 0.3309
State of knowledge of soil biodiversity 196 • Soil sealing, increasing water runoff and reducing infiltration. • Pollution. • Topsoil removal or replacement, and addition of anthropogenic materials. • Reduced habitat for soil biota, and increased spatial heterogeneity and fragmentation. • Alteration in soil communities and food web dynamics. • Drastic alteration of the environment where soil organisms live. Urbanization drivers and effects on soils • Decreases macropore volume. • Increases resis

7. SRC02_P0297_C005 | SRC02 | Page 297 | Distance 0.3311
Interventions can involve both the direct manipulation of the biological community (e.g. introduction of beneficial organisms) and indirect interventions that alter or maintain the environ- ment in ways that favour the presence of benefi- cial species or biodiversity in general. The impacts of various management practices on soil biodiver- sity are reviewed by Beed et al. (2017), Briones and Schmidt (2017), Cock et al. (2012), D’Hose et al. (2018), FAO and ITPS (2015), Lehmann et al. (2011), Org

8. SRC01_P0343_C002 | SRC01 | Page 343 | Distance 0.3318
Please provide additional information to support the answers in the comments area below. Soil formation Nutrient cycling Control soil erosion Atmospheric composition and climate regulation CO2 sequestration and CC responses Regulation of water supply and quality Pollutant degradation and soil remediation Recycling of biomass, nutrients and water 10 0 20 30 Restoration of degraded lands and ecosystems Nitrogen fixation Pest and disease regulation Landscape support Enhance agricultural productivit

9. SRC01_P0297_C001 | SRC01 | Page 297 | Distance 0.3343
Responses and opportunities 267 Figure 5.1.1 (previous page) | Management of soil biodiversity Along with other strategies, some environmental problems and crop needs can be tackled with nature-based solutions. The development of these types of solutions should be based on comprehensive approaches that consider the interactions of plants with soil biodiversity as well as the management of beneficial and harmful organisms. 5.2 | ECOSYSTEM RESTORATION: STARTING FROM THE GROUND AND LEVERAGING SOIL

10. SRC01_P0424_C001 | SRC01 | Page 424 | Distance 0.3398
State of knowledge of soil biodiversity 394 a study was conducted on soils with different agricultural uses such as corn, sugar cane, milky, grass and natural forest. The results indicated that in the cases managed with low organic matter content or intensive management, the nitrogen-fixing bacteria were better developed and in those with higher phosphorus content, either through organic or inorganic fertilization, a better development of phosphorus-solubilizing bacteria. It was also verified th

==========================================================================================
ASPECT: RAINFALL
==========================================================================================

1. SRC01_P0270_C005 | SRC01 | Page 270 | Distance 0.2712
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low

2. SRC01_P0344_C001 | SRC01 | Page 344 | Distance 0.3219
State of knowledge of soil biodiversity 314 10 0 20 What are the major practices in this country that might have negatively impacted soil biodiversity in the last 10 years (1 being the lowest important and 5 being the highest)?

3. SRC01_P0297_C001 | SRC01 | Page 297 | Distance 0.3506
Responses and opportunities 267 Figure 5.1.1 (previous page) | Management of soil biodiversity Along with other strategies, some environmental problems and crop needs can be tackled with nature-based solutions. The development of these types of solutions should be based on comprehensive approaches that consider the interactions of plants with soil biodiversity as well as the management of beneficial and harmful organisms. 5.2 | ECOSYSTEM RESTORATION: STARTING FROM THE GROUND AND LEVERAGING SOIL

4. SRC02_P0066_C001 | SRC02 | Page 66 | Distance 0.3553
22 Part A Overview the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Bommarco, Kleijn and Potts, 2013; Hooper et al., 2005; Kremen and Miles, 2012; Tscharntke et al., 2005). Diversity among the species, varieties and breeds of crops, livestock or aquatic animals raised in a given area can hinder the spread of diseases and help to reduce the risk of devastating losses (see Section 2.3 for further discussion). Water-related ecosystem services Ecosystems used for food and agriculture a

5. SRC01_P0014_C002 | SRC01 | Page 14 | Distance 0.3589
2. 8. 1 | salinization 222 4. 2. 10. 1 | satellite images of natural and anthropogenic - enhanced water erosion 230 4. 2. 10. 2 | satellite images of soil erosion 231 4. 3. 1 | terrestrial ecoregions of the world used for the assessment of regional threats 238 4. 3. 3. 1 | importance of threats to soil biodiversity in europe 245 4. 4. 1 | estimated levels of current potential threats to soil biodiversity worldwide 260 5. 1. 1 | management of soil biodiversity 267 5. 2. 1. 1 | soil biodiversity a

6. SRC01_P0273_C003 | SRC01 | Page 273 | Distance 0.3592
table 4. 3. 2. 1 | threats to soil biodiversity in asian ecoregions the main threats to soil biodiversity and function, and the level of scientific knowledge of the impacts of these threats on soil biodiversity in each of the ecoregions of asia ecoregion main threats knowledge level tropical and subtropical forest deforestation agricultural intensification loss of som and soc high high fair tropical and subtropical grassland deforestation loss of som and soc soil compaction and sealing fire eros

7. SRC01_P0271_C001 | SRC01 | Page 271 | Distance 0.3609
Threats to soil biodiversity - global and regional trends 241 Table 4.3.1.1 | Threats to soil biodiversity in Sub-Saharan African Ecoregions The main threats to soil biodiversity and function, and the level of scientific knowledge of the impacts of these threats on soil biodiversity in each of the ecoregions of sub-Saharan Africa (SSA) Ecoregion Main threats Knowledge level Tropical and subtropical forest Deforestation Agricultural intensification Loss of SOM and SOC Erosion and landslides High

8. SRC01_P0439_C001 | SRC01 | Page 439 | Distance 0.3662
Country Responses to the Soil Biodiversity Survey 409 4.1.4 | MAJOR PRACTICES NEGATIVELY IMPACTING SOIL BIODIVERSITY In the Syrian Arab Republic, a large number of negative practices affect the soil, including the overuse of chemical fertilizers and pesticides, the use of surface irrigation, over-cutting of forests and overgrazing in the Syrian Badia, especially during the crisis in Syria, soil stress through cultivation of stressful crops of the soil, the use of wastewater in agriculture, espec

9. SRC02_P0241_C001 | SRC02 | Page 241 | Distance 0.3686
197 THE STATE OF USE OF BIODIVERSITY FOR FOOD AND AGRICULTURE 5 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Figure 5.1 Perceived impacts on biodiversity for food and agriculture of various management practices and approaches Negative Positive Not known Not reported Neutral 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Landscape management Ecosystem approach to ﬁsheries Restoration practices Diversiﬁcation Home gardens Agroforestry Polyculture/aquaponics Organic agriculture Low e

10. SRC01_P0472_C003 | SRC01 | Page 472 | Distance 0.3722
Please link any relevant publications, documents or websites used in compiling these data. III | MAINSTREAMING: POLICIES, REGULATIONS AND GOVERNMENTAL FRAMEWORKS 4.1 List any policies, programmes, regulation, enabling frameworks or any legal instrument that contain reference to soil biodiversity (name of the instrument, date of establishment, ministry, extent of implementation, links to global frameworks and agreements, indication of how exactly soil biodiversity is addressed, obstacles in devel

==========================================================================================
ASPECT: LAND_USE
==========================================================================================

1. SRC01_P0344_C001 | SRC01 | Page 344 | Distance 0.3021
State of knowledge of soil biodiversity 314 10 0 20 What are the major practices in this country that might have negatively impacted soil biodiversity in the last 10 years (1 being the lowest important and 5 being the highest)?

2. SRC01_P0270_C005 | SRC01 | Page 270 | Distance 0.3064
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low

3. SRC01_P0344_C002 | SRC01 | Page 344 | Distance 0.3343
10 0 20 Over-use of chemical control mechanisms (e.g. pesticides, antibiotics, etc.) Monoculture Inappropriate soil management Practices leading to soil and water degradation Inappropriate water management Over-grazing Over-exploitation Changes in land use Over-use of fertilizers or other external inputs Forest clearing and habitat fragmentation 1 2 3 4 5 COUNTRIES THAT REPLIED COUNTRIES THAT REPLIED Figure 6.1.3 | Major practices that have a negative impact on soil biodiversity (Survey Question

4. SRC02_P0241_C001 | SRC02 | Page 241 | Distance 0.3368
197 THE STATE OF USE OF BIODIVERSITY FOR FOOD AND AGRICULTURE 5 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE Figure 5.1 Perceived impacts on biodiversity for food and agriculture of various management practices and approaches Negative Positive Not known Not reported Neutral 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Landscape management Ecosystem approach to ﬁsheries Restoration practices Diversiﬁcation Home gardens Agroforestry Polyculture/aquaponics Organic agriculture Low e

5. SRC01_P0302_C001 | SRC01 | Page 302 | Distance 0.3394
State of knowledge of soil biodiversity 272 5.2.2 | NOVEL WHOLE-ECOSYSTEM APPROACHES FOR SOIL RESTORATION AND SOIL MANAGEMENT Human management of agricultural land and other soils is known to reduce soil biodiversity. Examples include negative effects of tillage (Tsiafouli et al., 2015), mineral fertilizers (Ramirez et al., 2012) and pesticides (Thiele-Bruhn et al., 2012) on field level (functional) soil diversity. Insufficient return of organic matter to agricultural soils has led to severe deg

6. SRC02_P0299_C001 | SRC02 | Page 299 | Distance 0.3419
255 THE STATE OF USE OF BIODIVERSITY FOR FOOD AND AGRICULTURE 5 the state OF THE WORLD'S biodiversity FOr FOOD AND AGRICULTURE of such practices.62 Of the 91 reporting countries, 39 reported the adoption of sustainable soil man- agement practices. Responses are summarized in Table 5.1 and Table 5.2. Sustainable soil manage- ment practices are reported for all land-based production-system categories. In each case, increases in implementation are indicated more frequently than decreases. Depending

7. SRC01_P0297_C001 | SRC01 | Page 297 | Distance 0.3468

In [45]:
import re


# ============================================================
# EVIDENCE QUALITY PENALTY
# ============================================================

def evidence_quality_penalty(text):
    """
    Lower = better.

    Adds penalties to chunks that are semantically similar
    but structurally poor evidence, such as survey questions,
    TOC fragments, figure-heavy chunks, etc.
    """

    t = text.lower().strip()

    penalty = 0.0

    # Survey / questionnaire material
    survey_patterns = [
        "survey question",
        "countries that replied",
        "please select",
        "please provide additional information",
        "what are the major practices in this country",
        "country responses to the soil biodiversity survey"
    ]

    if any(pattern in t for pattern in survey_patterns):
        penalty += 0.12

    # Table of contents / navigation fragments
    toc_patterns = [
        "table of contents",
        "chapter 1",
        "chapter 2",
        "chapter 3",
        "chapter 4",
        "chapter 5",
        "chapter 6",
        "chapter 7",
        "annex i"
    ]

    if any(pattern in t for pattern in toc_patterns):
        penalty += 0.10

    # Figure/table extraction rather than explanatory prose
    if (
        ("figure " in t or "table " in t)
        and len(t.split()) < 180
    ):
        penalty += 0.035

    # Question-heavy text
    question_count = text.count("?")

    if question_count >= 2:
        penalty += 0.08
    elif question_count == 1:
        penalty += 0.025

    return penalty

In [46]:
def retrieve_candidates(question, per_aspect=10):

    queries = decompose_query(question)

    candidates = {}

    for aspect, query in queries.items():

        query_embedding = embedding_model.encode(
            query,
            normalize_embeddings=True
        ).tolist()

        results = collection.query(
            query_embeddings=[query_embedding],
            n_results=per_aspect,
            include=["documents", "metadatas", "distances"]
        )

        for i, chunk_id in enumerate(results["ids"][0]):

            text = results["documents"][0][i]
            metadata = results["metadatas"][0][i]
            distance = results["distances"][0][i]

            if chunk_id not in candidates:

                candidates[chunk_id] = {
                    "chunk_id": chunk_id,
                    "text": text,
                    "source_id": metadata["source_id"],
                    "page_number": metadata["page_number"],
                    "distances": {},
                    "matched_aspects": []
                }

            candidates[chunk_id]["distances"][aspect] = distance
            candidates[chunk_id]["matched_aspects"].append(aspect)

    return candidates

In [47]:
def rerank_candidates(question, per_aspect=10):

    candidates = retrieve_candidates(
        question,
        per_aspect=per_aspect
    )

    reranked = []

    for item in candidates.values():

        best_distance = min(item["distances"].values())

        penalty = evidence_quality_penalty(
            item["text"]
        )

        final_score = best_distance + penalty

        item["best_distance"] = best_distance
        item["quality_penalty"] = penalty
        item["final_score"] = final_score

        reranked.append(item)

    reranked.sort(
        key=lambda x: x["final_score"]
    )

    return reranked

In [48]:
def retrieve_quality_balanced_top3(question):

    candidates = rerank_candidates(
        question,
        per_aspect=10
    )

    selected = []
    selected_ids = set()

    # --------------------------------------------------
    # 1. Rainfall
    # --------------------------------------------------

    rainfall_candidates = [
        item for item in candidates
        if "rainfall" in item["matched_aspects"]
    ]

    if rainfall_candidates:

        item = rainfall_candidates[0].copy()
        item["selected_for"] = "rainfall"

        selected.append(item)
        selected_ids.add(item["chunk_id"])

    # --------------------------------------------------
    # 2. SOC
    # --------------------------------------------------

    soc_candidates = [
        item for item in candidates
        if (
            "soc" in item["matched_aspects"]
            and item["chunk_id"] not in selected_ids
        )
    ]

    if soc_candidates:

        item = soc_candidates[0].copy()
        item["selected_for"] = "soc"

        selected.append(item)
        selected_ids.add(item["chunk_id"])

    # --------------------------------------------------
    # 3. Land use / biodiversity
    # --------------------------------------------------

    management_candidates = [
        item for item in candidates
        if (
            (
                "land_use" in item["matched_aspects"]
                or
                "biodiversity" in item["matched_aspects"]
            )
            and item["chunk_id"] not in selected_ids
        )
    ]

    if management_candidates:

        item = management_candidates[0].copy()
        item["selected_for"] = "management/biodiversity"

        selected.append(item)
        selected_ids.add(item["chunk_id"])

    # --------------------------------------------------
    # Fill if fewer than 3
    # --------------------------------------------------

    for item in candidates:

        if len(selected) >= 3:
            break

        if item["chunk_id"] not in selected_ids:

            new_item = item.copy()
            new_item["selected_for"] = "general"

            selected.append(new_item)
            selected_ids.add(item["chunk_id"])

    return selected[:3]

In [49]:
results = retrieve_quality_balanced_top3(
    test_cases["GC07"]
)

for rank, item in enumerate(results, start=1):

    print("\n" + "=" * 90)
    print("RESULT", rank)
    print("=" * 90)

    print("Selected for:", item["selected_for"])
    print("Chunk:", item["chunk_id"])
    print("Source:", item["source_id"])
    print("Page:", item["page_number"])

    print(
        "Semantic distance:",
        round(item["best_distance"], 4)
    )

    print(
        "Quality penalty:",
        round(item["quality_penalty"], 4)
    )

    print(
        "Final score:",
        round(item["final_score"], 4)
    )

    print(
        "Matched aspects:",
        item["matched_aspects"]
    )

    print("\nTEXT:")
    print(item["text"])

==========================================================================================
RESULT 1
==========================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Semantic distance: 0.2712
Quality penalty: 0.035
Final score: 0.3062
Matched aspects: ['original', 'rainfall', 'land_use', 'biodiversity']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

==========================================================================================
RESULT 2
==========================================================================================
Selected for: soc
Chunk: SRC01_P0227_C001
Source: SRC01
Page: 227
Semantic distance: 0.3162
Quality penalty: 0.0
Final score: 0.3162
Matched aspects: ['soc']

TEXT:
Threats to soil biodiversity - global and regional trends 197 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 C C C C C C C C C C C Impacts on soil biodiversity Erosion and landslides drivers and effects on soils • Detachment, transport and deposition of soil particles by water or wind. • Loss of organic matter and changes in soil physical and chemical properties. • Creation of degraded and enriched depositional environments. • Inhabitants of upper soil layers may be eliminated or displaced. • Loss of habitat and decrese in its quality for soil biota. • Spread of pests and pathogens. • Reduced soil biodiversity and functioning.

==========================================================================================
RESULT 3
==========================================================================================
Selected for: management/biodiversity
Chunk: SRC01_P0348_C002
Source: SRC01
Page: 348
Semantic distance: 0.3186
Quality penalty: 0.0
Final score: 0.3186
Matched aspects: ['biodiversity']

TEXT:
HIGHLIGHTS • There is an overall interest in promoting sustainable soil management as well as sustainable agriculture and/or sustainable intensification practices through policies, laws and other activities. • There is a growing interest in examining and understanding the connections between soil biodiversity and other topics such as human health and ecosystem restoration. • There are some direct and indirect references to soil biodiversity in countries’ National Biodiversity Strategies and Action Plans (NBSAPs) and other global commitments. • There is some direct and indirect integration of soil biodiversity in sectoral and/or cross-sectoral policies. • Some countries are starting to integrate soil biodiversity in different areas such as food security, environment, forestry, agriculture, protected areas, land management, climate change, indigenous peoples and local communities and family farmers. • There is a general lack of specific policies, programmes and actions that take into account the particularities of soil biodiversity, as well as measures to promote its conservation and sustainable use.

In [50]:
quality_results = {}

for case_id in ["GC01", "GC02", "GC04", "GC06", "GC07"]:

    print("\n" + "#" * 100)
    print(case_id)
    print("QUESTION:", test_cases[case_id])
    print("#" * 100)

    results = retrieve_quality_balanced_top3(
        test_cases[case_id]
    )

    quality_results[case_id] = results

    for rank, item in enumerate(results, start=1):

        print("\n" + "=" * 80)
        print("RESULT", rank)
        print("=" * 80)

        print("Selected for:", item["selected_for"])
        print("Chunk:", item["chunk_id"])
        print("Source:", item["source_id"])
        print("Page:", item["page_number"])
        print(
            "Semantic distance:",
            round(item["best_distance"], 4)
        )
        print(
            "Quality penalty:",
            round(item["quality_penalty"], 4)
        )
        print(
            "Final score:",
            round(item["final_score"], 4)
        )
        print(
            "Matched aspects:",
            item["matched_aspects"]
        )

        print("\nTEXT:")
        print(item["text"])

####################################################################################################
GC01
QUESTION: A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Semantic distance: 0.3153
Quality penalty: 0.035
Final score: 0.3503
Matched aspects: ['original', 'rainfall', 'land_use', 'biodiversity']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC02_P0297_C005
Source: SRC02
Page: 297
Semantic distance: 0.3518
Quality penalty: 0.0
Final score: 0.3518
Matched aspects: ['soc', 'biodiversity']

TEXT:
Interventions can involve both the direct manipulation of the biological community (e.g. introduction of beneficial organisms) and indirect interventions that alter or maintain the environ- ment in ways that favour the presence of benefi- cial species or biodiversity in general. The impacts of various management practices on soil biodiver- sity are reviewed by Beed et al. (2017), Briones and Schmidt (2017), Cock et al. (2012), D’Hose et al. (2018), FAO and ITPS (2015), Lehmann et al. (2011), Orgiazzi et al., eds. (2016) and Tsiafouli et al. (2015). Key means of benefiting soil bio- diversity include reducing the use of synthetic fertilizers, pesticides and herbicides, maintaining or increasing soil organic matter, and minimizing soil erosion and disturbance.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC02_P0135_C001
Source: SRC02
Page: 135
Semantic distance: 0.3382
Quality penalty: 0.0
Final score: 0.3382
Matched aspects: ['land_use', 'biodiversity']

TEXT:
91 drivers of change of biodiversity for food and agriculture 3 the state of the world ' s biodiversity for food and agriculture production systems where reported ( in decreasing order of frequency ) impact on bfa ( number of responses ) impact on ecosystem services ( number of responses ) species ( latin name ) common english name number of countries negative neutral positive negative neutral positive pistia stratiotes water lettuce 6 self - recruiting capture fisheries, culture - based fisheries, irrigated crop systems ( rice ), mixed systems ( livestock, crop, forest and / or aquatic and fisheries ), naturally regenerated forests 3 0 1 3 0 1 tuta absoluta tomato leafminer 6 irrigated crop systems ( non - rice ), rainfed crop systems, irrigated crop systems ( rice ), naturally regenerated forests 1 0 1 0 0 1 leucaena leucocephala white leadtree 6 mixed systems ( livestock, crop, forest and / or aquatic and fisheries ), naturally regenerated forests, livestock grassland - based systems 3 0 0 3 0

####################################################################################################
GC02
QUESTION: My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0180_C005
Source: SRC01
Page: 180
Semantic distance: 0.3369
Quality penalty: 0.0
Final score: 0.3369
Matched aspects: ['original', 'soc', 'rainfall', 'land_use', 'biodiversity']

TEXT:
Healthy soils unify productive and natural systems by focusing on maintaining an intact, diverse below-ground ecosystem that ensures the flow of carbon, nutrients, and energy necessary for resilient landscapes (Kibblewhite et al., 2008). As a terrestrial system accrues soil organic matter, both soil health and soil organic carbon increase and a multitude of co-benefits emerge. Future plans, challenges and gaps While the potential for synergies from harnessing soil biodiversity for climate action with other global agendas is enormous, transformative policies and action and enabling conditions are necessary for success. Existing nature protection policies need to be fully implemented, and there is a pressing need for support and security of tenure for those at the front line of protecting, restoring and caring for land and soil and conserving its biodiversity, including indigenous peoples and local communities. There is also a need for education and awareness raising, capacity strengthening and full engagement across the public and private sector towards overcoming financial barriers and implementing natural capital accounting and payment for ecosystem services.

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0189_C004
Source: SRC01
Page: 189
Semantic distance: 0.3457
Quality penalty: 0.0
Final score: 0.3457
Matched aspects: ['original', 'soc', 'rainfall', 'land_use', 'biodiversity']

TEXT:
General guidelines to make soils more resilient to climate change should include the following: (1) Conservation of C-rich soils like peatlands, forest soils and permanent grasslands should become a priority. (2) Improve SOC pool by adopting less intensive agricultural practices that limit/exclude agrochemical use and maintain a live plant cover (such as conservation agriculture) or use organic amendments such as mulch, compost. (3) Adopting ‘paludiculture’ practices to cultivate organic soils without drainage, whereas land use practices that require drainage should, if possible, be relocated to areas with mineral soils. (4) Increase soil biodiversity by protecting natural areas, keeping habitat heterogeneity and diversifying land use options. The great recent advances in collating and mapping soil biodiversity data at global scales (see for example Tedersoo et al., 2014; van den Hoogen et al., 2019; Phillips et al., 2019) means that it will now be possible to link specific soil biota groups to terrestrial carbon stocks.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC01_P0294_C005
Source: SRC01
Page: 294
Semantic distance: 0.3672
Quality penalty: 0.0
Final score: 0.3672
Matched aspects: ['soc', 'land_use']

TEXT:
Knowledge on how the physical, chemical and biological components interact is needed in order to restore and manage the integrity and functioning of soils, and how soil biodiversity enhances soil multi-functionality. The FAO and ITPS (2015) Status of the World Soil Resources Report states that 33 percent of land is “moderately to highly degraded.” This calls for immediate action to restore degraded lands through the implementation of sustainable soil management, particularly in regions where fragile and degraded soils impose great constraints on soil functions and ecosystem-wide provided services. Increasing or maintaining soil biodiversity is one effective solution that can assist in soil restoration, provided that the causes of soil degradation have been solved. Strategies to enhance soil biodiversity for agriculture, land management, crop growth or ecosystem services may involve soil tillage, irrigation, organic matter addition, crop and tree species, and crop rotational and intercropping systems. These management approaches are environment-specific and need to be adjusted to the local soil, climate and land use history and to the socio- economic system.

####################################################################################################
GC04
QUESTION: We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0324_C001
Source: SRC01
Page: 324
Semantic distance: 0.3391
Quality penalty: 0.0
Final score: 0.3391
Matched aspects: ['original', 'soc', 'rainfall', 'land_use']

TEXT:
State of knowledge of soil biodiversity 294 5.4.3 | SOIL BIODIVERSITY AS A FARMER’S TOOL The adoption of soil conservation practices such as reduced tillage, improved residue management, reduced bare fallow and conservation reserve plantings have stabilized, and partially reversed, soil organic carbon (SOC) loss in North American agricultural soils (Paustian et al., 2016). Improved grazing management, fertilization, and sowing legumes and improved grass species are additional ways to increase soil C by as much as 1 Mg C/ ha/yr in best cases (Conant et al., 2016). Restoration of late-successional grassland plant diversity leads to accelerating annual carbon storage rates on degraded and abandoned agricultural lands that, by the second period (years 13 to 22), are 200 percent greater in the highest diversity treatment than during succession at this site, and 70 percent greater than in monocultures.

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0236_C003
Source: SRC01
Page: 236
Semantic distance: 0.3169
Quality penalty: 0.0
Final score: 0.3169
Matched aspects: ['soc']

TEXT:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC05_P0004_C007
Source: SRC05
Page: 4
Semantic distance: 0.4025
Quality penalty: 0.0
Final score: 0.4025
Matched aspects: ['land_use']

TEXT:
This would allow a comprehensive understanding for effects of or- ganic amendments on climate change. A key challenge for sustain- able crop production is hence to seek diversification solutions that simultaneously sustain soil health, crop yield, and mitigation of climate change. We show that agricultural diversification promotes biodiversity and the delivery of ecosystem services without compromising crop yield. This suggests several pathways for future sustainable food production and demonstrates how mainstream, high-yielding crop production can benefit from management that bolsters biodiversity. Large areas of cropland with monocultures in vast crop fields, such as in Australia, and North and South America (3), could benefit by the implementation of longer crop rotations, intercropping, and higher noncrop species diversity that enhance aboveground bio- diversity and the provisioning of regulating services, such as pollina- tion, pest control, and water regulation. Belowground biodiversity and services associated with soil quality are mainly supported by organic amendment and reduced tillage.

####################################################################################################
GC06
QUESTION: Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now.
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0324_C001
Source: SRC01
Page: 324
Semantic distance: 0.3082
Quality penalty: 0.0
Final score: 0.3082
Matched aspects: ['original', 'soc', 'rainfall', 'land_use']

TEXT:
State of knowledge of soil biodiversity 294 5.4.3 | SOIL BIODIVERSITY AS A FARMER’S TOOL The adoption of soil conservation practices such as reduced tillage, improved residue management, reduced bare fallow and conservation reserve plantings have stabilized, and partially reversed, soil organic carbon (SOC) loss in North American agricultural soils (Paustian et al., 2016). Improved grazing management, fertilization, and sowing legumes and improved grass species are additional ways to increase soil C by as much as 1 Mg C/ ha/yr in best cases (Conant et al., 2016). Restoration of late-successional grassland plant diversity leads to accelerating annual carbon storage rates on degraded and abandoned agricultural lands that, by the second period (years 13 to 22), are 200 percent greater in the highest diversity treatment than during succession at this site, and 70 percent greater than in monocultures.

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0227_C001
Source: SRC01
Page: 227
Semantic distance: 0.3167
Quality penalty: 0.0
Final score: 0.3167
Matched aspects: ['soc']

TEXT:
Threats to soil biodiversity - global and regional trends 197 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 C C C C C C C C C C C Impacts on soil biodiversity Erosion and landslides drivers and effects on soils • Detachment, transport and deposition of soil particles by water or wind. • Loss of organic matter and changes in soil physical and chemical properties. • Creation of degraded and enriched depositional environments. • Inhabitants of upper soil layers may be eliminated or displaced. • Loss of habitat and decrese in its quality for soil biota. • Spread of pests and pathogens. • Reduced soil biodiversity and functioning.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Semantic distance: 0.3153
Quality penalty: 0.035
Final score: 0.3503
Matched aspects: ['original', 'soc', 'rainfall', 'land_use', 'biodiversity']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

####################################################################################################
GC07
QUESTION: Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Semantic distance: 0.2712
Quality penalty: 0.035
Final score: 0.3062
Matched aspects: ['original', 'rainfall', 'land_use', 'biodiversity']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0227_C001
Source: SRC01
Page: 227
Semantic distance: 0.3162
Quality penalty: 0.0
Final score: 0.3162
Matched aspects: ['soc']

TEXT:
Threats to soil biodiversity - global and regional trends 197 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 C C C C C C C C C C C Impacts on soil biodiversity Erosion and landslides drivers and effects on soils • Detachment, transport and deposition of soil particles by water or wind. • Loss of organic matter and changes in soil physical and chemical properties. • Creation of degraded and enriched depositional environments. • Inhabitants of upper soil layers may be eliminated or displaced. • Loss of habitat and decrese in its quality for soil biota. • Spread of pests and pathogens. • Reduced soil biodiversity and functioning.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC01_P0348_C002
Source: SRC01
Page: 348
Semantic distance: 0.3186
Quality penalty: 0.0
Final score: 0.3186
Matched aspects: ['biodiversity']

TEXT:

In [51]:
def decompose_query(question):

    q = question.lower()

    queries = {
        "original": question
    }

    # ============================================================
    # SOC
    # ============================================================

    if (
        "soil carbon" in q
        or "soil organic carbon" in q
        or "soc" in q
    ):

        if (
            "very low" in q
            or "low soil" in q
            or "0.3%" in q
            or "0.4%" in q
        ):
            queries["soc"] = (
                question
                + " Effects of low soil organic carbon on soil health, "
                "soil biodiversity, soil organisms and ecosystem functioning."
            )

        elif (
            "good soil carbon" in q
            or "high soil carbon" in q
        ):
            queries["soc"] = (
                question
                + " Healthy soil organic carbon, soil biodiversity, "
                "soil ecosystem stability and maintenance."
            )

        else:
            queries["soc"] = (
                question
                + " Relationship between soil organic carbon, "
                "soil biodiversity and soil health."
            )

    # ============================================================
    # RAINFALL
    # ============================================================

    if (
        "rainfall" in q
        or "semi-arid" in q
        or "semi arid" in q
    ):

        if (
            "low rainfall" in q
            or "rainfall is low" in q
            or "semi-arid" in q
            or "semi arid" in q
        ):
            queries["rainfall"] = (
                question
                + " Low rainfall semi-arid dryland restoration, "
                "water limitation, soil water availability and "
                "vegetation establishment."
            )

        elif (
            "high rainfall" in q
            or "rainfall here is high" in q
        ):
            queries["rainfall"] = (
                question
                + " High rainfall non-water-limited agricultural soil "
                "restoration, vegetation and management practices."
            )

        else:
            queries["rainfall"] = (
                question
                + " Adequate rainfall and water availability for "
                "agricultural soil restoration and vegetation establishment."
            )

    # ============================================================
    # LAND USE / MANAGEMENT
    # ============================================================

    if (
        "wheat" in q
        or "corn" in q
        or "maize" in q
        or "monoculture" in q
        or "agroforestry" in q
    ):

        if "wheat" in q and "monoculture" in q:
            queries["land_use"] = (
                question
                + " Wheat monoculture agricultural management interventions: "
                "crop diversification, crop rotation, intercropping, "
                "agroforestry, organic amendments, reduced tillage, "
                "cover crops and practices that improve soil biodiversity "
                "and soil organic carbon."
            )

        elif (
            ("corn" in q or "maize" in q)
            and "monoculture" in q
        ):
            queries["land_use"] = (
                question
                + " Corn maize monoculture agricultural management interventions: "
                "crop diversification, crop rotation, intercropping, "
                "cover crops, organic amendments, reduced tillage and "
                "practices that improve soil biodiversity and "
                "soil organic carbon."
            )

        elif "agroforestry" in q:
            queries["land_use"] = (
                question
                + " Existing agroforestry systems, biodiversity, soil health, "
                "ecosystem services and sustainable maintenance."
            )

        else:
            queries["land_use"] = (
                question
                + " Agricultural land-use diversification, crop rotation, "
                "intercropping, agroforestry and sustainable soil management."
            )

    # ============================================================
    # BIODIVERSITY
    # ============================================================

    if (
        "biodiversity" in q
        or "species" in q
        or "species count" in q
        or "species diversity" in q
    ):

        if (
            "low species" in q
            or "declining" in q
        ):
            queries["biodiversity"] = (
                question
                + " Evidence-based agricultural management practices that "
                "increase or restore biodiversity, including crop diversification, "
                "intercropping, crop rotation, agroforestry, organic amendments, "
                "reduced tillage and habitat diversification."
            )

        elif (
            "high species" in q
            or "fine for now" in q
            or "stable" in q
        ):
            queries["biodiversity"] = (
                question
                + " Evidence-based agricultural management practices that "
                "maintain existing biodiversity and ecosystem stability, "
                "including crop diversification, intercropping, crop rotation, "
                "agroforestry, organic amendments, reduced tillage and "
                "habitat diversification."
            )

        else:
            queries["biodiversity"] = (
                question
                + " Evidence-based agricultural management practices that "
                "increase or maintain biodiversity, including crop diversification, "
                "intercropping, crop rotation, agroforestry, organic amendments, "
                "reduced tillage and habitat diversification."
            )

    return queries

In [52]:
for case_id in ["GC01", "GC02", "GC04", "GC06", "GC07"]:

    print("\n" + "=" * 80)
    print(case_id)
    print("=" * 80)

    queries = decompose_query(test_cases[case_id])

    for aspect, query in queries.items():
        print(f"\n{aspect.upper()}:")
        print(query)

================================================================================
GC01
================================================================================

ORIGINAL:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?

SOC:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition? Effects of low soil organic carbon on soil health, soil biodiversity, soil organisms and ecosystem functioning.

RAINFALL:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition? Low rainfall semi-arid dryland restoration, water limitation, soil water availability and vegetation establishment.

LAND_USE:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition? Wheat monoculture agricultural management interventions: crop diversification, crop rotation, intercropping, agroforestry, organic amendments, reduced tillage, cover crops and practices that improve soil biodiversity and soil organic carbon.

BIODIVERSITY:
A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition? Evidence-based agricultural management practices that increase or restore biodiversity, including crop diversification, intercropping, crop rotation, agroforestry, organic amendments, reduced tillage and habitat diversification.

================================================================================
GC02
================================================================================

ORIGINAL:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do?

SOC:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do? Healthy soil organic carbon, soil biodiversity, soil ecosystem stability and maintenance.

RAINFALL:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do? Adequate rainfall and water availability for agricultural soil restoration and vegetation establishment.

LAND_USE:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do? Existing agroforestry systems, biodiversity, soil health, ecosystem services and sustainable maintenance.

BIODIVERSITY:
My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do? Evidence-based agricultural management practices that increase or maintain biodiversity, including crop diversification, intercropping, crop rotation, agroforestry, organic amendments, reduced tillage and habitat diversification.

================================================================================
GC04
================================================================================

ORIGINAL:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?

SOC:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do? Relationship between soil organic carbon, soil biodiversity and soil health.

RAINFALL:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do? Adequate rainfall and water availability for agricultural soil restoration and vegetation establishment.

LAND_USE:
We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do? Agricultural land-use diversification, crop rotation, intercropping, agroforestry and sustainable soil management.

================================================================================
GC06
================================================================================

ORIGINAL:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now.

SOC:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now. Effects of low soil organic carbon on soil health, soil biodiversity, soil organisms and ecosystem functioning.

RAINFALL:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now. High rainfall non-water-limited agricultural soil restoration, vegetation and management practices.

LAND_USE:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now. Corn maize monoculture agricultural management interventions: crop diversification, crop rotation, intercropping, cover crops, organic amendments, reduced tillage and practices that improve soil biodiversity and soil organic carbon.

BIODIVERSITY:
Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now. Evidence-based agricultural management practices that maintain existing biodiversity and ecosystem stability, including crop diversification, intercropping, crop rotation, agroforestry, organic amendments, reduced tillage and habitat diversification.

================================================================================
GC07
================================================================================

ORIGINAL:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health?

SOC:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health? Effects of low soil organic carbon on soil health, soil biodiversity, soil organisms and ecosystem functioning.

RAINFALL:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health? Low rainfall semi-arid dryland restoration, water limitation, soil water availability and vegetation establishment.

LAND_USE:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health? Wheat monoculture agricultural management interventions: crop diversification, crop rotation, intercropping, agroforestry, organic amendments, reduced tillage, cover crops and practices that improve soil biodiversity and soil organic carbon.

BIODIVERSITY:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health? Evidence-based agricultural management practices that increase or maintain biodiversity, including crop diversification, intercropping, crop rotation, agroforestry, organic amendments, reduced tillage and habitat diversification.

In [53]:
quality_results = {}

for case_id in ["GC01", "GC02", "GC04", "GC06", "GC07"]:

    print("\n" + "#" * 100)
    print(case_id)
    print("QUESTION:", test_cases[case_id])
    print("#" * 100)

    results = retrieve_quality_balanced_top3(
        test_cases[case_id]
    )

    quality_results[case_id] = results

    for rank, item in enumerate(results, start=1):

        print("\n" + "=" * 80)
        print("RESULT", rank)
        print("=" * 80)

        print("Selected for:", item["selected_for"])
        print("Chunk:", item["chunk_id"])
        print("Source:", item["source_id"])
        print("Page:", item["page_number"])
        print("Final score:", round(item["final_score"], 4))
        print("Matched aspects:", item["matched_aspects"])

        print("\nTEXT:")
        print(item["text"])

####################################################################################################
GC01
QUESTION: A farm has low soil organic carbon, low rainfall, monoculture wheat, and low species counts. What intervention could improve its condition?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0233_C003
Source: SRC01
Page: 233
Final score: 0.3354
Matched aspects: ['original', 'soc', 'rainfall', 'land_use', 'biodiversity']

TEXT:
For example, conversion of natural ecosystems to agricultural lands has resulted in substantial environmental costs, including land degradation, increased emissions of greenhouse gases, decreased organic matter in soils, loss of biodiversity and alterations of biogeochemical and hydrological cycles (Balmford et al., 2005). Modern agriculture thus faces great challenges not only in terms of meeting the food, fibre and fuel demands of an ever-increasing human population, but also in mitigating environmental costs, particularly in the context of inappropriate management practices, a changing environment and growing competition for land, water and energy (Chen et al., 2014). Understanding the mechanisms that control the extent to which soil properties and biological communities change following the conversion of natural to agricultural systems and management practices is of paramount importance to comprehend the consequences of land use changes for soil functions and agricultural productivity (Sala et al., 2000). Agricultural management practices act and interact with each other in different ways, and affect the soil ecosystem to different degrees and to different extents.

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC02_P0297_C005
Source: SRC02
Page: 297
Final score: 0.3408
Matched aspects: ['soc', 'biodiversity']

TEXT:
Interventions can involve both the direct manipulation of the biological community (e.g. introduction of beneficial organisms) and indirect interventions that alter or maintain the environ- ment in ways that favour the presence of benefi- cial species or biodiversity in general. The impacts of various management practices on soil biodiver- sity are reviewed by Beed et al. (2017), Briones and Schmidt (2017), Cock et al. (2012), D’Hose et al. (2018), FAO and ITPS (2015), Lehmann et al. (2011), Orgiazzi et al., eds. (2016) and Tsiafouli et al. (2015). Key means of benefiting soil bio- diversity include reducing the use of synthetic fertilizers, pesticides and herbicides, maintaining or increasing soil organic matter, and minimizing soil erosion and disturbance.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC02_P0492_C004
Source: SRC02
Page: 492
Final score: 0.328
Matched aspects: ['biodiversity']

TEXT:
This appears to be the case, for example, for organic agriculture, low external input agriculture, man- agement practices implemented with the aim of preserving and enhancing soil biodiversity, conservation agriculture, integrated plant nutri- ent management, integrated pest management, pollination management and sustainable forest management practices. Nevertheless, the avail- ability of global data on the levels of imple- mentation of many of these practices remains limited, and knowledge of their impacts on BFA and the supply of ecosystem services needs to be improved. Biodiversity-based and biodiversity-friendly management practices generally require detailed knowledge of local production systems and eco- systems and are often relatively labour inten- sive. Consequently, their implementation tends to require the active participation of producers and their organizations, as well as the presence of effective extension services. Management interventions often need to extend beyond farm boundaries into the broader landscape or sea- scape. Attention needs to be paid to maintaining or restoring ecosystems that deliver services to food and agriculture and conserving the species and genetic diversity that will allow adaptation to changing conditions.

####################################################################################################
GC02
QUESTION: My land already has good soil carbon, decent rainfall, and agroforestry. Species counts are high. Is there anything more I should do?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0180_C005
Source: SRC01
Page: 180
Final score: 0.3369
Matched aspects: ['original', 'soc', 'rainfall', 'land_use']

TEXT:
Healthy soils unify productive and natural systems by focusing on maintaining an intact, diverse below-ground ecosystem that ensures the flow of carbon, nutrients, and energy necessary for resilient landscapes (Kibblewhite et al., 2008). As a terrestrial system accrues soil organic matter, both soil health and soil organic carbon increase and a multitude of co-benefits emerge. Future plans, challenges and gaps While the potential for synergies from harnessing soil biodiversity for climate action with other global agendas is enormous, transformative policies and action and enabling conditions are necessary for success. Existing nature protection policies need to be fully implemented, and there is a pressing need for support and security of tenure for those at the front line of protecting, restoring and caring for land and soil and conserving its biodiversity, including indigenous peoples and local communities. There is also a need for education and awareness raising, capacity strengthening and full engagement across the public and private sector towards overcoming financial barriers and implementing natural capital accounting and payment for ecosystem services.

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0189_C004
Source: SRC01
Page: 189
Final score: 0.3457
Matched aspects: ['original', 'soc', 'rainfall', 'land_use']

TEXT:
General guidelines to make soils more resilient to climate change should include the following: (1) Conservation of C-rich soils like peatlands, forest soils and permanent grasslands should become a priority. (2) Improve SOC pool by adopting less intensive agricultural practices that limit/exclude agrochemical use and maintain a live plant cover (such as conservation agriculture) or use organic amendments such as mulch, compost. (3) Adopting ‘paludiculture’ practices to cultivate organic soils without drainage, whereas land use practices that require drainage should, if possible, be relocated to areas with mineral soils. (4) Increase soil biodiversity by protecting natural areas, keeping habitat heterogeneity and diversifying land use options. The great recent advances in collating and mapping soil biodiversity data at global scales (see for example Tedersoo et al., 2014; van den Hoogen et al., 2019; Phillips et al., 2019) means that it will now be possible to link specific soil biota groups to terrestrial carbon stocks.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC02_P0492_C004
Source: SRC02
Page: 492
Final score: 0.3359
Matched aspects: ['biodiversity']

TEXT:
This appears to be the case, for example, for organic agriculture, low external input agriculture, man- agement practices implemented with the aim of preserving and enhancing soil biodiversity, conservation agriculture, integrated plant nutri- ent management, integrated pest management, pollination management and sustainable forest management practices. Nevertheless, the avail- ability of global data on the levels of imple- mentation of many of these practices remains limited, and knowledge of their impacts on BFA and the supply of ecosystem services needs to be improved. Biodiversity-based and biodiversity-friendly management practices generally require detailed knowledge of local production systems and eco- systems and are often relatively labour inten- sive. Consequently, their implementation tends to require the active participation of producers and their organizations, as well as the presence of effective extension services. Management interventions often need to extend beyond farm boundaries into the broader landscape or sea- scape. Attention needs to be paid to maintaining or restoring ecosystems that deliver services to food and agriculture and conserving the species and genetic diversity that will allow adaptation to changing conditions.

####################################################################################################
GC04
QUESTION: We get decent rainfall but our soil carbon is low and we grow only wheat. What should we do?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0324_C001
Source: SRC01
Page: 324
Final score: 0.3391
Matched aspects: ['original', 'soc', 'rainfall', 'land_use']

TEXT:
State of knowledge of soil biodiversity 294 5.4.3 | SOIL BIODIVERSITY AS A FARMER’S TOOL The adoption of soil conservation practices such as reduced tillage, improved residue management, reduced bare fallow and conservation reserve plantings have stabilized, and partially reversed, soil organic carbon (SOC) loss in North American agricultural soils (Paustian et al., 2016). Improved grazing management, fertilization, and sowing legumes and improved grass species are additional ways to increase soil C by as much as 1 Mg C/ ha/yr in best cases (Conant et al., 2016). Restoration of late-successional grassland plant diversity leads to accelerating annual carbon storage rates on degraded and abandoned agricultural lands that, by the second period (years 13 to 22), are 200 percent greater in the highest diversity treatment than during succession at this site, and 70 percent greater than in monocultures.

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0236_C003
Source: SRC01
Page: 236
Final score: 0.3169
Matched aspects: ['soc']

TEXT:
Nonetheless, the generally positive relationship between soil C stock and soil biodiversity suggests that soil carbon loss is a threat to soil biodiversity. In this regard, Orgiazzi et al. (2016a) identified SOC decline as a major threat to both soil microbial and fauna biodiversity. But the underlying causes may be different, as the main drivers of SOC loss, land use change and climate change (see below) also directly impact soil biodiversity. For instance, soil biodiversity was higher in agricultural soils than in carbon-rich northern forests (Griffiths et al., 2016), but the main factor explaining biodiversity was pH, and low pH soils tend to have higher carbon content. Several authors also highlight the importance of soil carbon quality in addition to quantity for below-ground diversity on a global scale (Crowther et al., 2019). For instance, Szoboszlay et al. (2017) found evidence of associations between particular SOC fractions (especially particulate organic matter) and specific bacterial taxa across a large range of European soil with various land uses.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC01_P0180_C005
Source: SRC01
Page: 180
Final score: 0.3548
Matched aspects: ['soc', 'rainfall', 'land_use']

TEXT:
Healthy soils unify productive and natural systems by focusing on maintaining an intact, diverse below-ground ecosystem that ensures the flow of carbon, nutrients, and energy necessary for resilient landscapes (Kibblewhite et al., 2008). As a terrestrial system accrues soil organic matter, both soil health and soil organic carbon increase and a multitude of co-benefits emerge. Future plans, challenges and gaps While the potential for synergies from harnessing soil biodiversity for climate action with other global agendas is enormous, transformative policies and action and enabling conditions are necessary for success. Existing nature protection policies need to be fully implemented, and there is a pressing need for support and security of tenure for those at the front line of protecting, restoring and caring for land and soil and conserving its biodiversity, including indigenous peoples and local communities. There is also a need for education and awareness raising, capacity strengthening and full engagement across the public and private sector towards overcoming financial barriers and implementing natural capital accounting and payment for ecosystem services.

####################################################################################################
GC06
QUESTION: Rainfall here is high, but soil carbon is very low and it's monoculture corn. Species diversity seems fine for now.
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC05_P0004_C008
Source: SRC05
Page: 4
Final score: 0.288
Matched aspects: ['rainfall', 'land_use', 'biodiversity']

TEXT:
Large areas of cropland with monocultures in vast crop fields, such as in Australia, and North and South America (3), could benefit by the implementation of longer crop rotations, intercropping, and higher noncrop species diversity that enhance aboveground bio- diversity and the provisioning of regulating services, such as pollina- tion, pest control, and water regulation. Belowground biodiversity and services associated with soil quality are mainly supported by organic amendment and reduced tillage. Further, our results indicate that combining diversification practices is potentially advantageous for the provisioning of multiple ecosystem services and biodiversity conservation (Fig. 2).

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0324_C001
Source: SRC01
Page: 324
Final score: 0.3082
Matched aspects: ['original', 'soc', 'rainfall', 'land_use', 'biodiversity']

TEXT:
State of knowledge of soil biodiversity 294 5.4.3 | SOIL BIODIVERSITY AS A FARMER’S TOOL The adoption of soil conservation practices such as reduced tillage, improved residue management, reduced bare fallow and conservation reserve plantings have stabilized, and partially reversed, soil organic carbon (SOC) loss in North American agricultural soils (Paustian et al., 2016). Improved grazing management, fertilization, and sowing legumes and improved grass species are additional ways to increase soil C by as much as 1 Mg C/ ha/yr in best cases (Conant et al., 2016). Restoration of late-successional grassland plant diversity leads to accelerating annual carbon storage rates on degraded and abandoned agricultural lands that, by the second period (years 13 to 22), are 200 percent greater in the highest diversity treatment than during succession at this site, and 70 percent greater than in monocultures.

================================================================================
RESULT 3
================================================================================
Selected for: management/biodiversity
Chunk: SRC05_P0004_C007
Source: SRC05
Page: 4
Final score: 0.2915
Matched aspects: ['land_use', 'biodiversity']

TEXT:
This would allow a comprehensive understanding for effects of or- ganic amendments on climate change. A key challenge for sustain- able crop production is hence to seek diversification solutions that simultaneously sustain soil health, crop yield, and mitigation of climate change. We show that agricultural diversification promotes biodiversity and the delivery of ecosystem services without compromising crop yield. This suggests several pathways for future sustainable food production and demonstrates how mainstream, high-yielding crop production can benefit from management that bolsters biodiversity. Large areas of cropland with monocultures in vast crop fields, such as in Australia, and North and South America (3), could benefit by the implementation of longer crop rotations, intercropping, and higher noncrop species diversity that enhance aboveground bio- diversity and the provisioning of regulating services, such as pollina- tion, pest control, and water regulation. Belowground biodiversity and services associated with soil quality are mainly supported by organic amendment and reduced tillage.

####################################################################################################
GC07
QUESTION: Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health?
####################################################################################################

================================================================================
RESULT 1
================================================================================
Selected for: rainfall
Chunk: SRC01_P0270_C005
Source: SRC01
Page: 270
Final score: 0.3062
Matched aspects: ['original', 'rainfall']

TEXT:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

================================================================================
RESULT 2
================================================================================
Selected for: soc
Chunk: SRC01_P0227_C001
Source: SRC01
Page: 227
Final score: 0.3162
Matched aspects: ['soc']

TEXT:
Threats to soil biodiversity - global and regional trends 197 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 C C C C C C C C C C C Impacts on soil biodiversity Erosion and landslides drivers and effects on soils • Detachment, transport and deposition of soil particles by water or wind. • Loss of organic matter and changes in soil physical and chemical properties. • Creation of degraded and enriched depositional environments. • Inhabitants of upper soil layers may be eliminated or displaced. • Loss of habitat and decrese in its quality for soil biota. • Spread of pests and pathogens. • Reduced soil biodiversity and functioning.


In [54]:
# ============================================================
# GOLDEN CASE TOP-3 RETRIEVAL EVALUATION
# ============================================================

eval_cases = {
    "GC01": {
        "required_concepts": [
            ["soil organic carbon", "organic matter", "soil carbon"],
            ["biodiversity", "soil biodiversity"],
            ["management", "intervention", "diversification",
             "tillage", "organic amendment", "agroforestry",
             "intercropping", "crop rotation"]
        ]
    },

    "GC02": {
        "required_concepts": [
            ["soil organic carbon", "organic matter", "soil carbon"],
            ["biodiversity", "soil biodiversity"],
            ["maintain", "maintenance", "conservation",
             "sustainable", "protect"]
        ]
    },

    "GC04": {
        "required_concepts": [
            ["soil organic carbon", "organic matter", "soil carbon"],
            ["biodiversity", "soil biodiversity"],
            ["management", "reduced tillage", "residue",
             "diversification", "crop rotation",
             "intercropping", "agroforestry"]
        ]
    },

    "GC06": {
        "required_concepts": [
            ["soil organic carbon", "organic matter", "soil carbon"],
            ["biodiversity", "soil biodiversity"],
            ["monoculture", "diversification", "crop rotation",
             "intercropping", "cover crops",
             "organic amendment", "reduced tillage"]
        ]
    },

    "GC07": {
        "required_concepts": [
            ["soil organic carbon", "organic matter", "soil carbon"],
            ["biodiversity", "soil biodiversity"],
            ["rainfall", "water", "semi-arid", "dryland", "drought"],
            ["management", "conservation", "diversification",
             "intercropping", "agroforestry", "restoration"]
        ]
    }
}


def evaluate_case(case_id, results):

    combined_text = " ".join(
        item["text"] for item in results
    ).lower()

    concept_results = []

    for alternatives in eval_cases[case_id]["required_concepts"]:

        found = any(
            term.lower() in combined_text
            for term in alternatives
        )

        concept_results.append(found)

    covered = sum(concept_results)
    total = len(concept_results)

    coverage = covered / total

    # Case passes if at least 75% of its required
    # scientific concepts appear in retrieved Top-3 evidence
    passed = coverage >= 0.75

    return {
        "case_id": case_id,
        "concepts_covered": covered,
        "total_concepts": total,
        "coverage": coverage,
        "passed": passed
    }


evaluation_results = []

for case_id in eval_cases:

    results = quality_results[case_id]

    evaluation_results.append(
        evaluate_case(case_id, results)
    )


evaluation_df = pd.DataFrame(evaluation_results)

display(evaluation_df)


passed_cases = evaluation_df["passed"].sum()
total_cases = len(evaluation_df)

top3_success_rate = (
    passed_cases / total_cases
) * 100


print("\n" + "=" * 60)
print("GOLDEN CASE RETRIEVAL EVALUATION")
print("=" * 60)

print("Passed cases:", passed_cases, "/", total_cases)
print(f"Top-3 success rate: {top3_success_rate:.1f}%")

if top3_success_rate >= 80:
    print("TARGET ACHIEVED ✓")
else:
    print("TARGET NOT YET ACHIEVED")

  case_id  concepts_covered  total_concepts  coverage  passed
0    GC01                 3               3       1.0    True
1    GC02                 3               3       1.0    True
2    GC04                 3               3       1.0    True
3    GC06                 3               3       1.0    True
4    GC07                 4               4       1.0    True

============================================================
GOLDEN CASE RETRIEVAL EVALUATION
============================================================
Passed cases: 5 / 5
Top-3 success rate: 100.0%
TARGET ACHIEVED ✓

In [55]:
def build_rag_context(results):

    context_parts = []

    for i, item in enumerate(results, start=1):

        context_parts.append(
            f"""
SOURCE {i}
Source ID: {item['source_id']}
Page: {item['page_number']}
Chunk ID: {item['chunk_id']}

Evidence:
{item['text']}
""".strip()
        )

    return "\n\n".join(context_parts)

In [56]:
question = test_cases["GC07"]

results = retrieve_quality_balanced_top3(question)

context = build_rag_context(results)

print(context)

SOURCE 1
Source ID: SRC01
Page: 270
Chunk ID: SRC01_P0270_C005

Evidence:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

SOURCE 2
Source ID: SRC01
Page: 227
Chunk ID: SRC01_P0227_C001

Evidence:
Threats to soil biodiversity - global and regional trends 197 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 C C C C C C C C C C C Impacts on soil biodiversity Erosion and landslides drivers and effects on soils • Detachment, transport and deposition of soil particles by water or wind. • Loss of organic matter and changes in soil physical and chemical properties. • Creation of degraded and enriched depositional environments. • Inhabitants of upper soil layers may be eliminated or displaced. • Loss of habitat and decrese in its quality for soil biota. • Spread of pests and pathogens. • Reduced soil biodiversity and functioning.

SOURCE 3
Source ID: SRC02
Page: 292
Chunk ID: SRC02_P0292_C006

Evidence:
5.6 Management practices and production approaches • Countries report that management practices and production approaches promoting the conservation and sustainable use of biodiversity for food and agriculture (BFA) are increasingly being used. • Organic agriculture continues to expand with support from governments and NGOs. Certified organic agriculture now (2018) covers 58 million ha worldwide, more than 1 percent of global agricultural land. Monitoring non-certified organic agriculture is difficult and this reduces the accuracy of trend data. • A wide variety of management practices are increasingly being used to preserve and enhance soil biodiversity, although global data on implementation are uneven and limited. Countries generally identify the need to expand monitoring of beneficial soil species and improve the development and application of sustainable soil management practices. • Conservation agriculture (an approach based on minimizing soil disturbance, maintaining soil cover

In [ ]:
def build_rag_prompt(question, context):

    prompt = f"""
You are an evidence-grounded agricultural biodiversity and soil-health assistant.

Answer the user's question using ONLY the scientific evidence provided in the context below.

RULES:
1. Do not invent facts, numerical improvements, percentages, or timelines.
2. Do not make claims that are unsupported by the retrieved evidence.
3. Consider the user's stated soil organic carbon, rainfall, land use, and biodiversity conditions.
4. If important information is missing, clearly state what information is needed.
5. Give practical recommendations only when they are supported by the evidence.
6. If current conditions are already positive, do not recommend unnecessary drastic intervention.
7. Mention uncertainty when the evidence is insufficient.
8. Cite supporting evidence using [Source ID, Page X].
9. Keep the answer clear and understandable for a farmer or land manager.
10. Clearly distinguish between:
    - facts stated by the user,
    - findings reported by the scientific sources,
    - recommendations inferred from those findings.

11. Do not present a risk, threat, or condition mentioned in a source
    as if it definitely exists on the user's farm unless the user
    explicitly stated it.

12. Prefer cautious wording such as "the evidence indicates",
    "may help", "is associated with", or "is a potential risk"
    when the evidence does not establish a farm-specific fact.

13. Never claim that a specific user condition causes or is associated
    with an outcome unless the retrieved scientific context explicitly
    supports that relationship. Do not combine separate facts from the
    user and source into a new causal claim.
USER QUESTION:
{question}

SCIENTIFIC CONTEXT:
{context}

Provide the answer in this structure:

Assessment:
Briefly explain what the available conditions indicate.

Recommendation:
Give the most appropriate evidence-supported action or management approach.

Why:
Explain how the recommendation relates to soil health, biodiversity, rainfall,
or land use using the retrieved evidence.

Evidence:
List the sources used in the form [Source ID, Page X].

Limitations:
Mention any important missing information or uncertainty.
"""

    return prompt

In [77]:
question = test_cases["GC07"]

results = retrieve_quality_balanced_top3(question)

context = build_rag_context(results)

prompt = build_rag_prompt(
    question,
    context
)

print(prompt)

You are an evidence-grounded agricultural biodiversity and soil-health assistant.

Answer the user's question using ONLY the scientific evidence provided in the context below.

RULES:
1. Do not invent facts, numerical improvements, percentages, or timelines.
2. Do not make claims that are unsupported by the retrieved evidence.
3. Consider the user's stated soil organic carbon, rainfall, land use, and biodiversity conditions.
4. If important information is missing, clearly state what information is needed.
5. Give practical recommendations only when they are supported by the evidence.
6. If current conditions are already positive, do not recommend unnecessary drastic intervention.
7. Mention uncertainty when the evidence is insufficient.
8. Cite supporting evidence using [Source ID, Page X].
9. Keep the answer clear and understandable for a farmer or land manager.
10. Clearly distinguish between:
    - facts stated by the user,
    - findings reported by the scientific sources,
    - recommendations inferred from those findings.

11. Do not present a risk, threat, or condition mentioned in a source
    as if it definitely exists on the user's farm unless the user
    explicitly stated it.

12. Prefer cautious wording such as "the evidence indicates",
    "may help", "is associated with", or "is a potential risk"
    when the evidence does not establish a farm-specific fact.

13. Never claim that a specific user condition causes or is associated
    with an outcome unless the retrieved scientific context explicitly
    supports that relationship. Do not combine separate facts from the
    user and source into a new causal claim.
USER QUESTION:
Semi-arid region, soil organic carbon 0.3%, rainfall is low, crop is monoculture wheat. What should I do to improve biodiversity and soil health?

SCIENTIFIC CONTEXT:
SOURCE 1
Source ID: SRC01
Page: 270
Chunk ID: SRC01_P0270_C005

Evidence:
Where rainfall is higher and more reliable in the semi-arid zone, there is better vegetation cover of open low-tree grassland and a relatively healthy environment for humans and livestock. Cropping and crop–livestock systems dominate these areas and farmers commonly grow millet, sorghum, groundnut, maize and cowpeas. Threats to soil biodiversity in this ecoregion include wind and water erosion, loss of soil organic matter and soil nutrients, salinization and sodification and waterlogging in low areas (Table 4.3.1.1).

SOURCE 2
Source ID: SRC01
Page: 227
Chunk ID: SRC01_P0227_C001

Evidence:
Threats to soil biodiversity - global and regional trends 197 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 CO2 C C C C C C C C C C C Impacts on soil biodiversity Erosion and landslides drivers and effects on soils • Detachment, transport and deposition of soil particles by water or wind. • Loss of organic matter and changes in soil physical and chemical properties. • Creation of degraded and enriched depositional environments. • Inhabitants of upper soil layers may be eliminated or displaced. • Loss of habitat and decrese in its quality for soil biota. • Spread of pests and pathogens. • Reduced soil biodiversity and functioning.

SOURCE 3
Source ID: SRC02
Page: 292
Chunk ID: SRC02_P0292_C006

Evidence:
5.6 Management practices and production approaches • Countries report that management practices and production approaches promoting the conservation and sustainable use of biodiversity for food and agriculture (BFA) are increasingly being used. • Organic agriculture continues to expand with support from governments and NGOs. Certified organic agriculture now (2018) covers 58 million ha worldwide, more than 1 percent of global agricultural land. Monitoring non-certified organic agriculture is difficult and this reduces the accuracy of trend data. • A wide variety of management practices are increasingly being used to preserve and enhance soil biodiversity, although global data on implementation are uneven and limited. Countries generally identify the need to expand monitoring of beneficial soil species and improve the development and application of sustainable soil management practices. • Conservation agriculture (an approach based on minimizing soil disturbance, maintaining soil cover

Provide the answer in this structure:

Assessment:
Briefly explain what the available conditions indicate.

Recommendation:
Give the most appropriate evidence-supported action or management approach.

Why:
Explain how the recommendation relates to soil health, biodiversity, rainfall,
or land use using the retrieved evidence.

Evidence:
List the sources used in the form [Source ID, Page X].

Limitations:
Mention any important missing information or uncertainty.

In [59]:
%pip install -U google-genai python-dotenv

Collecting google-genai
  Downloading google_genai-2.24.0-py3-none-any.whl.metadata (56 kB)
Requirement already satisfied: python-dotenv in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (1.2.3)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from google-genai) (4.15.1)
Collecting google-auth<3.0.0,>=2.56.0 (from google-auth[requests]<3.0.0,>=2.56.0->google-genai)
  Downloading google_auth-2.58.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.12.5 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from google-genai) (2.13.5)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from google-genai) (9.1.4)
Collecting websockets<17.0,>=13.0.0 (from google-genai)
  Downloading websockets-16.1.1-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from google-genai) (4.16.0)
Collecting distro<2,>=1.7.0 (from google-genai)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting sniffio (from google-genai)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: idna>=2.8 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.19)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai)
  Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Requirement already satisfied: certifi in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.8.0)
Requirement already satisfied: cffi>=2.0.0 in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.1.1)
Requirement already satisfied: pycparser in c:\Users\shubham chavan\OneDrive\Documents\Desktop\biodiversity-intelligence-ai\.venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (3.0)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai)
  Downloading pyasn1-0.6.4-py3-none-any.whl.metadata (8.4 kB)
Downloading google_genai-2.24.0-py3-none-any.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   ------------------ --------------------- 0.5/1.1 MB 1.3 MB/s eta 0:00:01
   --------------------------- ------------ 0.8/1.1 MB 1.3 MB/s eta 0:00:01
   --------------------------- ------------ 0.8/1.1 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 1.1/1.1 MB 1.1 MB/s  0:00:00
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading google_auth-2.58.0-py3-none-any.whl (262 kB)
Downloading websockets-16.1.1-cp311-cp311-win_amd64.whl (180 kB)
Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.8 MB 1.3 MB/s eta 0:00:03
   ----- ---------------------------------- 0.5/3.8 MB 1.3 MB/s eta 0:00:03
   -------- ------------------------------- 0.8/3.8 MB 987.4 kB/s eta 0:00:04
   ---------- ----------------------------- 1.0/3.8 MB 1.1 MB/s eta 0:00:03
   ------------- -------------------------- 1.3/3.8 MB 1.1 MB/s eta 0:00:03
   ---------------- ----------------------- 1.6/3.8 MB 1.2 MB/s eta 0:00:02
   ------------------- -------------------- 1.8/3.8 MB 1.2 MB/s eta 0:00:02
   --------------------- ------------------ 2.1/3.8 MB 1.2 MB/s eta 0:00:02
   ------------------------ --------------- 2.4/3.8 MB 1.1 MB/s eta 0:00:02
   --------------------------- ------------ 2.6/3.8 MB 1.2 MB/s eta 0:00:02
   ------------------------------ --------- 2.9/3.8 MB 1.2 MB/s eta 0:00:01
   -------------------------------- ------- 3.1/3.8 MB 1.2 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 1.2 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 1.1 MB/s  0:00:03
Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pyasn1-0.6.4-py3-none-any.whl (84 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: websockets, sniffio, pyasn1, distro, pyasn1-modules, cryptography, google-auth, google-genai

  Attempting uninstall: websockets

    Found existing installation: websockets 17.1

    Uninstalling websockets-17.1:

      Successfully uninstalled websockets-17.1

   ---------------------------------------- 0/8 [websockets]
   ---------------------------------------- 0/8 [websockets]
   ---------------------------------------- 0/8 [websockets]
   ---------------------------------------- 0/8 [websockets]
   ---------------------------------------- 0/8 [websockets]
   ---------------------------------------- 0/8 [websockets]
   ---------------------------------------- 0/8 [websockets]
   ---------------------------------------- 0/8 [websockets]
   ---------- ----------------------------- 2/8 [pyasn1]
   ---------- ----------------------------- 2/8 [pyasn1]
   ---------- ----------------------------- 2/8 [pyasn1]
   ---------- ----------------------------- 2/8 [pyasn1]
   --------------- ------------------------ 3/8 [distro]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   -------------------- ------------------- 4/8 [pyasn1-modules]
   ------------------------- -------------- 5/8 [cryptography]
   ------------------------- -------------- 5/8 [cryptography]
   ------------------------- -------------- 5/8 [cryptography]
   ------------------------- -------------- 5/8 [cryptography]
   ------------------------- -------------- 5/8 [cryptography]
   ------------------------- -------------- 5/8 [cryptography]
   ------------------------- -------------- 5/8 [cryptography]
   ------------------------- -------------- 5/8 [cryptography]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ------------------------------ --------- 6/8 [google-auth]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ----------------------------------- ---- 7/8 [google-genai]
   ---------------------------------------- 8/8 [google-genai]

Successfully installed cryptography-50.0.1 distro-1.9.0 google-auth-2.58.0 google-genai-2.24.0 pyasn1-0.6.4 pyasn1-modules-0.4.2 sniffio-1.3.1 websockets-16.1.1
Note: you may need to restart the kernel to use updated packages.

In [60]:
import os
from dotenv import load_dotenv

load_dotenv("../.env")

api_key = os.getenv("GEMINI_API_KEY")

if api_key:
    print("API key loaded successfully ✓")
else:
    print("API key NOT found ✗")

API key loaded successfully ✓

In [61]:
from google import genai

client = genai.Client(api_key=api_key)

print("Gemini client initialized ✓")

Gemini client initialized ✓

In [62]:
response = client.models.generate_content(
    model="gemini-3.8-flash",
    contents="Reply with exactly: Gemini connection successful"
)

print(response.text)

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

Gemini connection successful

In [65]:
import time
from google.genai import errors


def rag_answer(question):

    # 1. Retrieve evidence
    results = retrieve_quality_balanced_top3(question)

    # 2. Build context
    context = build_rag_context(results)

    # 3. Build prompt
    prompt = build_rag_prompt(question, context)

    # 4. Try Gemini with automatic retry
    max_retries = 3

    for attempt in range(max_retries):

        try:
            response = client.models.generate_content(
                model="gemini-3.8-flash",
                contents=prompt
            )

            return response.text

        except errors.ServerError as e:

            if attempt < max_retries - 1:
                wait_time = 2 ** attempt

                print(
                    f"Gemini temporarily unavailable. "
                    f"Retrying in {wait_time}s..."
                )

                time.sleep(wait_time)

            else:
                raise e

In [66]:
question = test_cases["GC07"]

answer = rag_answer(question)

print(answer)

Gemini temporarily unavailable. Retrying in 1s...
Gemini temporarily unavailable. Retrying in 2s...

ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

In [67]:
response = client.models.generate_content(
    model="gemini-3.5-flash-lite",
    contents="Reply with exactly: Gemini connection successful"
)

print(response.text)

Gemini connection successful

In [68]:
import time
from google.genai import errors


def rag_answer(question):

    # Retrieve Top-3 scientific evidence
    results = retrieve_quality_balanced_top3(question)

    # Build scientific context
    context = build_rag_context(results)

    # Build grounded RAG prompt
    prompt = build_rag_prompt(question, context)

    # Fast model first, stronger Flash models as fallback
    models = [
        "gemini-3.5-flash-lite",
        "gemini-3.6-flash",
        "gemini-3.8-flash"
    ]

    last_error = None

    for model_name in models:

        try:
            print(f"Trying {model_name}...")

            response = client.models.generate_content(
                model=model_name,
                contents=prompt
            )

            if response.text:
                print(f"Answer generated using {model_name} ✓")
                return response.text

        except errors.ServerError as e:
            last_error = e
            print(f"{model_name} temporarily unavailable.")

            time.sleep(1)

        except errors.ClientError as e:
            last_error = e
            print(f"{model_name} unavailable for this API key.")

    raise RuntimeError(
        "All Gemini models failed. Last error: "
        + str(last_error)
    )

In [78]:
question = test_cases["GC07"]

answer = rag_answer(question)

print("\nFINAL RAG ANSWER:\n")
print(answer)

Trying gemini-3.5-flash-lite...
Answer generated using gemini-3.5-flash-lite ✓

FINAL RAG ANSWER:

Assessment:
You are operating in a semi-arid region with low rainfall, a soil organic carbon level of 0.3%, and your current land use is monoculture wheat [User Question].

Findings reported by the scientific sources indicate that threats to soil biodiversity include erosion (water and wind), loss of soil organic matter and soil nutrients, salinization, sodification, and waterlogging [SRC01, Page 270]. Erosion can cause detachment, transport, and deposition of soil particles, loss of organic matter, changes in physical and chemical properties, elimination or displacement of upper soil layer inhabitants, loss of habitat quality, spread of pests and pathogens, and reduced soil biodiversity and functioning [SRC02, Page 227]. Additionally, management practices and production approaches promoting the conservation and sustainable use of biodiversity for food and agriculture are increasingly being used [SRC02, Page 292].

Recommendation:
Based on the evidence, conservation agriculture—an approach based on minimizing soil disturbance and maintaining soil cover—is a management approach identified for preserving and enhancing soil biodiversity [SRC02, Page 292].

Why:
The evidence indicates that conservation agriculture is based on minimizing soil disturbance and maintaining soil cover to preserve and enhance soil biodiversity [SRC02, Page 292]. Conversely, the evidence notes that threats such as erosion lead to the loss of organic matter, decreased habitat quality, and reduced soil biodiversity and functioning [SRC02, Page 227]. Furthermore, loss of soil organic matter is identified as a threat to soil biodiversity in the semi-arid zone [SRC01, Page 270].

Evidence:
[SRC01, Page 270], [SRC02, Page 227], [SRC02, Page 292]

Limitations:
Important missing information includes specific data on how reliable rainfall is within your particular semi-arid location, the local presence or absence of specific erosion or pest threats, and detailed baseline data on beneficial soil species. There is also uncertainty regarding global data on implementation of soil management practices, which are uneven and limited [SRC02, Page 292].